package location

import (
	"bufio"
	_ "embed"
	"strconv"
	"strings"
)

// citiesTSV is the GeoNames-derived city dataset, generated by cmd/gen-cities and
// committed so the build never depends on that tool. Columns are tab-separated:
// canonical-name, ISO country code, and a '|'-joined list of lowercase aliases.
// Rows are population-sorted (most-populous first) so the loader's first-wins alias
// registration picks the largest place for a shared name.
//
//go:embed cities1000.tsv
var citiesTSV string

// cityEntry is a resolved city: its canonical display name (feeds the cities facet),
// its ISO 3166-1 alpha-2 country code, and whether more than one country claims the
// alias.
//
// Country is always the most-populous claimant, contested or not, because
// isRecognizedUSCACity asks a different question — "does the parser know this name as
// a North American place?" — where a shared name is still evidence. Contested is what
// gates *emitting* that country as the posting's geography: "Birmingham" (gb, us),
// "Valencia" (six countries) and "Burlington" (ca, us) state nothing, while
// "Colorado Springs", "Eden Prairie" and "Benidorm" — 98% of the dictionary's 238k
// aliases — state theirs.
type cityEntry struct {
	Name      string
	Country   string
	Contested bool
}

// cityDict maps a lowercase city alias to its canonical name + country, built once
// at init from the embedded dataset with the curated overrides layered on top.
var cityDict = loadCityDict(citiesTSV, cityOverrides)

// statingPopulation is the population a place must have before the dictionary lets it
// STATE anything — a canonical city name or a country. Below it a place is evidence
// only: it can mark an alias contested, but never claims it.
//
// The split exists because the two jobs want opposite datasets. Contest detection
// wants every hamlet: the Taft in California (pop. 9,000) is what stops the Iranian
// Taft from confidently mislabelling a US posting, and the same holds for "Somerset",
// "San" and "Young". Stating wants only real places: GeoNames at pop>=1,000 contains
// villages named "Engineer", "California" and "Attica", and letting those claim a
// name put junk into the cities facet and made unrelated slug fragments look like
// locations. 15,000 is where the dataset used to be cut, so what the parser asserts
// is exactly what it asserted before — only its scepticism grew.
const statingPopulation = 15000

// loadCityDict parses the embedded TSV into the alias lookup. An alias already seen
// keeps its first entry (first-wins → most-populous, since the file is population
// sorted), but seeing it again under a different country marks it Contested: a name
// two countries share cannot state one. A place below statingPopulation contests but
// never registers. Comment/blank lines are skipped. Overrides are applied last and win
// outright, uncontested — they are hand-pinned spellings, so their country is asserted
// rather than inferred.
func loadCityDict(tsv string, overrides map[string]cityEntry) map[string]cityEntry {
	dict := map[string]cityEntry{}
	// claims records the one country holding an alias, or "" once a second country
	// turns up. It counts EVERY row including the sub-threshold ones that never
	// register, so two hamlets in different countries still contest a name no large
	// city claims.
	claims := map[string]string{}
	sc := bufio.NewScanner(strings.NewReader(tsv))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20) // the widest alias row (Shanghai) is a few KB
	for sc.Scan() {
		line := strings.TrimSuffix(sc.Text(), "\r") // tolerate a CRLF checkout
		if line == "" || line[0] == '#' {
			continue
		}
		// Four columns are the format, not a suggestion: a row without population would
		// otherwise read as population zero and silently register nothing at all.
		parts := strings.SplitN(line, "\t", 4)
		if len(parts) < 4 {
			continue
		}
		pop, _ := strconv.ParseInt(strings.TrimSpace(parts[3]), 10, 64)
		entry := cityEntry{Name: parts[0], Country: parts[1]}
		for _, alias := range strings.Split(parts[2], "|") {
			if prev, seen := claims[alias]; !seen {
				claims[alias] = entry.Country
			} else if prev != "" && prev != entry.Country {
				claims[alias] = ""
			}
			if pop < statingPopulation {
				continue // evidence only: contests, never claims
			}
			if _, seen := dict[alias]; !seen {
				dict[alias] = entry
			}
		}
	}
	// Marking is a separate pass because a third row can contest an alias the second
	// row agreed with, and the flag must end up set either way. Walking dict rather
	// than claims also skips names known only to hamlets — those stay absent entirely.
	for alias, e := range dict {
		if claims[alias] == "" {
			e.Contested = true
			dict[alias] = e
		}
	}
	for alias, e := range overrides {
		dict[alias] = e
	}
	return dict
}
