package location

import (
	"bufio"
	_ "embed"
	"strings"
)

// citiesTSV is the GeoNames-derived city dataset, generated by cmd/gen-cities and
// committed so the build never depends on that tool. Columns are tab-separated:
// canonical-name, ISO country code, and a '|'-joined list of lowercase aliases.
// Rows are population-sorted (most-populous first) so the loader's first-wins alias
// registration picks the largest place for a shared name.
//
//go:embed cities15000.tsv
var citiesTSV string

// cityEntry is a resolved city: its canonical display name (feeds the cities facet)
// and ISO 3166-1 alpha-2 country code (feeds countries/regions).
type cityEntry struct {
	Name    string
	Country string
}

// cityDict maps a lowercase city alias to its canonical name + country, built once
// at init from the embedded dataset with the curated overrides layered on top.
var cityDict = loadCityDict(citiesTSV, cityOverrides)

// loadCityDict parses the embedded TSV into the alias lookup. An alias already seen
// is not overwritten (first-wins → most-populous, since the file is population
// sorted); comment/blank lines are skipped. Overrides are applied last and win.
func loadCityDict(tsv string, overrides map[string]cityEntry) map[string]cityEntry {
	dict := map[string]cityEntry{}
	sc := bufio.NewScanner(strings.NewReader(tsv))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20) // the widest alias row (Shanghai) is a few KB
	for sc.Scan() {
		line := strings.TrimSuffix(sc.Text(), "\r") // tolerate a CRLF checkout
		if line == "" || line[0] == '#' {
			continue
		}
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) < 3 {
			continue
		}
		entry := cityEntry{Name: parts[0], Country: parts[1]}
		for _, alias := range strings.Split(parts[2], "|") {
			if _, seen := dict[alias]; !seen {
				dict[alias] = entry
			}
		}
	}
	for alias, e := range overrides {
		dict[alias] = e
	}
	return dict
}
