// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_customer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStripeCustomerID = `-- name: GetStripeCustomerID :one
SELECT stripe_customer_id
FROM users
WHERE id = $1
`

// Which customer to ask the provider about for this account. NULL means the account has
// never transacted, which is the same answer the provider gives for an id it does not know.
func (q *Queries) GetStripeCustomerID(ctx context.Context, id int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerID, id)
	var stripe_customer_id pgtype.Text
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const getUserIDByStripeCustomer = `-- name: GetUserIDByStripeCustomer :one
SELECT id
FROM users
WHERE stripe_customer_id = $1::text
`

// Resolve a provider customer back to one of our accounts. This is the direction a webhook
// needs: a delivery names the customer, never the user.
//
// No rows means the customer is not ours — a dashboard test object, or a customer created
// outside this integration. The caller records the event and reports it rather than
// guessing.
func (q *Queries) GetUserIDByStripeCustomer(ctx context.Context, stripeCustomerID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByStripeCustomer, stripeCustomerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSubscribersNearProExpiryStripe = `-- name: ListSubscribersNearProExpiryStripe :many
SELECT id, stripe_customer_id, pro_until
FROM users
WHERE stripe_customer_id IS NOT NULL
  AND pro_until >= $1
  AND pro_until < $2
LIMIT $3
`

type ListSubscribersNearProExpiryStripeParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	MaxRows  int32              `json:"max_rows"`
}

type ListSubscribersNearProExpiryStripeRow struct {
	ID               int64              `json:"id"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	ProUntil         pgtype.Timestamptz `json:"pro_until"`
}

// The reconciler's second pass: accounts bound to a provider customer whose plan expiry
// falls inside a window around now, so a renewal whose webhook was never delivered is
// repaired on the next run.
//
// It walks users rather than billing_events because the binding column is what makes the
// question answerable at all — and it is indexed, so the scan is over the accounts that
// have transacted rather than over all of them.
func (q *Queries) ListSubscribersNearProExpiryStripe(ctx context.Context, arg ListSubscribersNearProExpiryStripeParams) ([]ListSubscribersNearProExpiryStripeRow, error) {
	rows, err := q.db.Query(ctx, listSubscribersNearProExpiryStripe, arg.FromTime, arg.ToTime, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersNearProExpiryStripeRow{}
	for rows.Next() {
		var i ListSubscribersNearProExpiryStripeRow
		if err := rows.Scan(&i.ID, &i.StripeCustomerID, &i.ProUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :exec
UPDATE users
SET stripe_customer_id = $1::text
WHERE id = $2
  AND stripe_customer_id IS NULL
`

type SetStripeCustomerIDParams struct {
	StripeCustomerID string `json:"stripe_customer_id"`
	ID               int64  `json:"id"`
}

// Bind an account to the payment provider's customer, ONCE, when it first transacts.
//
// IS NULL, so this writes a binding and never REPLACES one. That is a security property,
// not a tidiness one. An account's customer is resolved two ways (see Service.resolveUser):
// from the stored binding, and — only when there is no binding yet — from the account
// reference the provider echoes back. That reference is attacker-supplied on one path: a
// Stripe Payment Link takes `?client_reference_id=` from whoever opens it. With a bare
// assignment, somebody who paid for their own subscription while naming SOMEBODY ELSE'S
// account id would overwrite that account's binding, orphan the subscription it was
// actually paying for — nothing reads a customer no user points at, so the reconciler
// never touches it again — and then hold the victim's plan hostage to their own card.
//
// Refusing the write costs nothing the system needs. The self-healing rebind in
// Service.Apply is precisely the NULL case, and an account that genuinely has to move to a
// new customer is a support ticket and one UPDATE, not a path a webhook should offer.
//
// Also subsumes the cheaper reason the predicate was here before: the webhook and the
// reconciler both take this path and both usually write the value already present, and a
// write that changes nothing should not wake a trigger or bloat a row.
func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setStripeCustomerID, arg.StripeCustomerID, arg.ID)
	return err
}
