// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBillingEventsForUser = `-- name: DeleteBillingEventsForUser :exec
DELETE FROM billing_events WHERE user_id = $1
`

// Erase one user's billing events. Account deletion calls this; the foreign key cascades,
// but deletion states what it erases explicitly rather than relying on a constraint to
// mean it.
func (q *Queries) DeleteBillingEventsForUser(ctx context.Context, userID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteBillingEventsForUser, userID)
	return err
}

const insertBillingEvent = `-- name: InsertBillingEvent :one
INSERT INTO billing_events (provider, event_id, app_user_id, user_id, event_type, payload)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4,
    $5::text,
    $6
)
ON CONFLICT (provider, event_id) DO NOTHING
RETURNING id
`

type InsertBillingEventParams struct {
	Provider  string      `json:"provider"`
	EventID   string      `json:"event_id"`
	AppUserID string      `json:"app_user_id"`
	UserID    pgtype.Int8 `json:"user_id"`
	EventType string      `json:"event_type"`
	Payload   []byte      `json:"payload"`
}

// Record a received webhook event, once. See the add-pro-subscription change.
//
// ON CONFLICT DO NOTHING against the (provider, event_id) unique index is the whole of the
// idempotency: the provider retries a delivery it did not get a 200 for and reuses the
// same event id, and says outright that duplicates are possible and delivery is unordered.
// A redelivery therefore returns NO ROWS, which the caller reads as "already recorded" and
// answers 200 to — not as an error.
//
// user_id is passed already resolved and may be NULL: a dashboard TEST event, an event for
// an account since deleted, and an identifier that was never one of ours all still get
// recorded. A row we cannot attribute is evidence; a row we refused to write is nothing.
func (q *Queries) InsertBillingEvent(ctx context.Context, arg InsertBillingEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBillingEvent,
		arg.Provider,
		arg.EventID,
		arg.AppUserID,
		arg.UserID,
		arg.EventType,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSubscribersNearProExpiry = `-- name: ListSubscribersNearProExpiry :many
SELECT DISTINCT b.user_id, u.pro_until
FROM billing_events b
JOIN users u ON u.id = b.user_id
WHERE b.user_id IS NOT NULL
  AND u.pro_until >= $1
  AND u.pro_until < $2
LIMIT $3
`

type ListSubscribersNearProExpiryParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	MaxRows  int32              `json:"max_rows"`
}

type ListSubscribersNearProExpiryRow struct {
	UserID   pgtype.Int8        `json:"user_id"`
	ProUntil pgtype.Timestamptz `json:"pro_until"`
}

// The reconciler's second pass: subscribers whose plan expiry falls inside a window around
// now, so a renewal whose webhook was never delivered is repaired within an hour.
//
// IT WALKS billing_events, NOT users. Two reasons, and the second is the one that matters.
//
// Cheapness: only an account that has actually transacted appears here, so the candidate
// set is the subscriber base rather than the 8M-row users table, and it is reached through
// an index that already exists. A predicate on users.pro_until would want an index on
// users, and building one on a table that size means either blocking writes to the account
// table or a CONCURRENTLY build with its own failure mode.
//
// Correctness: reading a subscriber's state from the provider CREATES that subscriber if
// the identifier is unknown to them — a GET with a write's consequences. Starting from
// events makes "we only ever ask about someone who has transacted" a property of the
// query rather than a rule the worker has to remember.
func (q *Queries) ListSubscribersNearProExpiry(ctx context.Context, arg ListSubscribersNearProExpiryParams) ([]ListSubscribersNearProExpiryRow, error) {
	rows, err := q.db.Query(ctx, listSubscribersNearProExpiry, arg.FromTime, arg.ToTime, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersNearProExpiryRow{}
	for rows.Next() {
		var i ListSubscribersNearProExpiryRow
		if err := rows.Scan(&i.UserID, &i.ProUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedBillingEvents = `-- name: ListUnprocessedBillingEvents :many
SELECT id, provider, event_id, app_user_id, user_id, event_type, received_at
FROM billing_events
WHERE processed_at IS NULL
ORDER BY received_at
LIMIT $1
`

type ListUnprocessedBillingEventsRow struct {
	ID         int64              `json:"id"`
	Provider   string             `json:"provider"`
	EventID    string             `json:"event_id"`
	AppUserID  string             `json:"app_user_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	EventType  string             `json:"event_type"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

// The reconciler's first pass: events recorded but never applied, oldest first, served by
// the partial index on (received_at) WHERE processed_at IS NULL.
//
// Rows with a NULL user_id come back too. They are not skipped in SQL because "an event we
// could not attribute" is a decision the worker should make visibly and log, not something
// a WHERE clause silently disposes of.
func (q *Queries) ListUnprocessedBillingEvents(ctx context.Context, maxRows int32) ([]ListUnprocessedBillingEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnprocessedBillingEvents, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnprocessedBillingEventsRow{}
	for rows.Next() {
		var i ListUnprocessedBillingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.EventID,
			&i.AppUserID,
			&i.UserID,
			&i.EventType,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingEventProcessed = `-- name: MarkBillingEventProcessed :exec
UPDATE billing_events
SET processed_at = now()
WHERE id = $1
`

// Stamp an event as applied. Idempotent by shape: re-stamping a processed row writes the
// same fact, and the reconciler's own query no longer returns it.
func (q *Queries) MarkBillingEventProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markBillingEventProcessed, id)
	return err
}
