// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest_schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueRuns = `-- name: ClaimDueRuns :many
WITH candidate AS (
    SELECT rs.provider,
           rs.shard,
           -- The shard COUNT is how many run-state rows the provider has, not
           -- ingest_schedule.shards. Reconcile creates exactly one row per shard, so the
           -- rows ARE the count; reading it from the override table instead would be a
           -- second source for one fact, and the two disagree for any provider whose rows
           -- exist while its override row does not. A subquery rather than a window
           -- function, because FOR UPDATE may not be combined with one.
           (SELECT count(*) FROM ingest_run_state peer WHERE peer.provider = rs.provider)::int AS shards,
           COALESCE(s.cadence_sec, $1::int) AS cadence_sec,
           COALESCE(s.timeout_sec, $2::int) AS timeout_sec
    FROM ingest_run_state rs
    LEFT JOIN ingest_schedule s ON s.provider = rs.provider
    WHERE ((rs.claimed_at IS NULL AND rs.next_due_at <= now())
        OR (rs.claimed_at IS NOT NULL
            AND rs.claimed_at < now() - make_interval(
                    secs => COALESCE(s.timeout_sec, $2::int)
                            + $3::int)))
    -- ROLLOUT GATE, removed with the column in task 8.5 of
    -- openspec/changes/ingest-scheduler-in-db. Run state is tracked for every enabled
    -- provider so the stagger and the shadow preview exist from day one; what ` + "`" + `managed` + "`" + `
    -- decides is whether the SCHEDULER may launch it, or whether its static timer still
    -- owns it. COALESCE to false: while the column exists, a provider nobody has handed
    -- over is still the static timer's.
    AND COALESCE(s.managed, false)
    ORDER BY rs.next_due_at
    LIMIT $4
    FOR UPDATE OF rs SKIP LOCKED
)
UPDATE ingest_run_state rs
SET claimed_at      = now(),
    last_started_at = now(),
    next_due_at     = now() + make_interval(secs => c.cadence_sec)
FROM candidate c
WHERE rs.provider = c.provider AND rs.shard = c.shard
RETURNING rs.provider, rs.shard, c.shards, c.timeout_sec
`

type ClaimDueRunsParams struct {
	DefaultCadenceSec int32 `json:"default_cadence_sec"`
	DefaultTimeoutSec int32 `json:"default_timeout_sec"`
	GraceSec          int32 `json:"grace_sec"`
	MaxRuns           int32 `json:"max_runs"`
}

type ClaimDueRunsRow struct {
	Provider   string `json:"provider"`
	Shard      int32  `json:"shard"`
	Shards     int32  `json:"shards"`
	TimeoutSec int32  `json:"timeout_sec"`
}

// Take up to max_runs due runs, exactly once each.
//
// The CTE resolves each candidate's cadence and timeout through the same LEFT JOIN and
// defaults as the listing above, so a claim can never use different numbers from the
// report. FOR UPDATE ... SKIP LOCKED is what makes two overlapping scheduler ticks safe:
// the second skips the rows the first holds rather than blocking on them or double-claiming.
// `OF rs` names only the run-state table, since FOR UPDATE may not be applied to the
// nullable side of an outer join.
//
// A row is claimable when it is due and unclaimed, or when its claim has outlived that
// provider's own timeout plus the grace window — a scheduler killed between claiming and
// launching, and a run systemd killed at its timeout, both recover through that second arm
// with no operator.
//
// next_due_at advances to now() + cadence, not to next_due_at + cadence. Advancing at
// claim stops a 40-minute crawl from halving its own frequency; advancing from now() caps
// catch-up at ONE run, so a six-hour outage does not owe six.
func (q *Queries) ClaimDueRuns(ctx context.Context, arg ClaimDueRunsParams) ([]ClaimDueRunsRow, error) {
	rows, err := q.db.Query(ctx, claimDueRuns,
		arg.DefaultCadenceSec,
		arg.DefaultTimeoutSec,
		arg.GraceSec,
		arg.MaxRuns,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueRunsRow{}
	for rows.Next() {
		var i ClaimDueRunsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Shard,
			&i.Shards,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRunStateForUnlistedProviders = `-- name: DeleteRunStateForUnlistedProviders :exec
DELETE FROM ingest_run_state
WHERE provider <> ALL ($1::text[])
  AND claimed_at IS NULL
`

// Forget the providers that are no longer eligible — every board retired, or the adapter
// gone. This is the sweep gen-ingest-timers.sh promised in its header and never had: under
// it, a provider's timer survived forever and kept crawling nothing (careerspage ran empty
// from 18 July).
//
// A CLAIMED row survives, for the same reason as the surplus-shard delete above: it is the
// only record that a crawl is still running, and losing it makes the fleet under-count
// itself. A provider disabled mid-crawl keeps its row for one more tick, until the reap.
func (q *Queries) DeleteRunStateForUnlistedProviders(ctx context.Context, providers []string) error {
	_, err := q.db.Exec(ctx, deleteRunStateForUnlistedProviders, providers)
	return err
}

const deleteSurplusRunStateShards = `-- name: DeleteSurplusRunStateShards :exec
DELETE FROM ingest_run_state
WHERE provider = $1
  AND shard > $2::int
  AND claimed_at IS NULL
`

type DeleteSurplusRunStateShardsParams struct {
	Provider string `json:"provider"`
	Shards   int32  `json:"shards"`
}

// Drop the shards left over from a higher shard count.
//
// A CLAIMED row is left alone. Deleting one would erase the scheduler's only record that a
// crawl is still executing, so the fleet would under-count itself and launch past its cap —
// and the surviving run would finish with nothing to report to. The row goes on the next
// tick after it is reaped, which costs one minute and cannot lose a slot.
func (q *Queries) DeleteSurplusRunStateShards(ctx context.Context, arg DeleteSurplusRunStateShardsParams) error {
	_, err := q.db.Exec(ctx, deleteSurplusRunStateShards, arg.Provider, arg.Shards)
	return err
}

const ensureRunStateShards = `-- name: EnsureRunStateShards :exec
INSERT INTO ingest_run_state (provider, shard, next_due_at)
SELECT $1, g, now()
FROM generate_series(1, $2::int) AS g
ON CONFLICT (provider, shard) DO NOTHING
`

type EnsureRunStateShardsParams struct {
	Provider string `json:"provider"`
	Shards   int32  `json:"shards"`
}

// Materialise the (provider, 1..shards) rows a provider needs. ON CONFLICT DO NOTHING is
// load-bearing: an existing shard keeps its next_due_at, which is the fleet's stagger, and
// resetting it would bunch a provider's whole cycle onto one minute.
//
// A new shard is due immediately. That is deliberate — a shard that has never run has no
// schedule to respect, and the concurrency cap is what keeps a fresh 24-way provider from
// taking the whole fleet at once.
func (q *Queries) EnsureRunStateShards(ctx context.Context, arg EnsureRunStateShardsParams) error {
	_, err := q.db.Exec(ctx, ensureRunStateShards, arg.Provider, arg.Shards)
	return err
}

const listInFlightRuns = `-- name: ListInFlightRuns :many
SELECT rs.provider,
       rs.shard,
       (SELECT count(*) FROM ingest_run_state peer WHERE peer.provider = rs.provider)::int AS shards,
       COALESCE(s.timeout_sec, $1::int) AS timeout_sec
FROM ingest_run_state rs
LEFT JOIN ingest_schedule s ON s.provider = rs.provider
WHERE rs.claimed_at IS NOT NULL
ORDER BY rs.claimed_at
`

type ListInFlightRunsRow struct {
	Provider   string `json:"provider"`
	Shard      int32  `json:"shard"`
	Shards     int32  `json:"shards"`
	TimeoutSec int32  `json:"timeout_sec"`
}

// Every claimed run, with what the scheduler needs to ask the service manager about it.
//
// Rows, not a count. A transient unit finishes and tells nobody, so claimed_at is set at
// claim and cleared by nothing until the scheduler reaps: a plain count would include every
// run that ever succeeded, and the fleet's concurrency cap would fill permanently after
// Cap launches with every check still green.
//
// This is what replaces ingest-slot.sh's flock semaphore. 279 independent timers could not
// see each other, so the ceiling had to live in a wrapper script; one scheduler can count —
// but only if it also notices when a run has ended.
func (q *Queries) ListInFlightRuns(ctx context.Context, defaultTimeoutSec int32) ([]ListInFlightRunsRow, error) {
	rows, err := q.db.Query(ctx, listInFlightRuns, defaultTimeoutSec)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInFlightRunsRow{}
	for rows.Next() {
		var i ListInFlightRunsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Shard,
			&i.Shards,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulableProviders = `-- name: ListSchedulableProviders :many
SELECT b.provider,
       s.shards,
       s.cadence_sec,
       s.timeout_sec,
       s.enabled,
       s.disabled_reason,
       s.notes,
       s.managed
FROM (SELECT DISTINCT provider FROM boards WHERE status IN ('pending', 'active')) b
LEFT JOIN ingest_schedule s ON s.provider = b.provider
ORDER BY b.provider
`

type ListSchedulableProvidersRow struct {
	Provider       string      `json:"provider"`
	Shards         pgtype.Int4 `json:"shards"`
	CadenceSec     pgtype.Int4 `json:"cadence_sec"`
	TimeoutSec     pgtype.Int4 `json:"timeout_sec"`
	Enabled        pgtype.Bool `json:"enabled"`
	DisabledReason pgtype.Text `json:"disabled_reason"`
	Notes          pgtype.Text `json:"notes"`
	Managed        pgtype.Bool `json:"managed"`
}

// Every provider the scheduler may run, with its override if it has one.
//
// The roster is boards, and the LEFT JOIN is what makes ingest_schedule a set of
// OVERRIDES rather than the roster: a provider with a live board and no schedule row comes
// back with NULLs, which the caller resolves to documented defaults. An INNER JOIN here
// would silently unschedule every unconfigured provider, which is the exact failure this
// table was built to remove.
func (q *Queries) ListSchedulableProviders(ctx context.Context) ([]ListSchedulableProvidersRow, error) {
	rows, err := q.db.Query(ctx, listSchedulableProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulableProvidersRow{}
	for rows.Next() {
		var i ListSchedulableProvidersRow
		if err := rows.Scan(
			&i.Provider,
			&i.Shards,
			&i.CadenceSec,
			&i.TimeoutSec,
			&i.Enabled,
			&i.DisabledReason,
			&i.Notes,
			&i.Managed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previewDueRuns = `-- name: PreviewDueRuns :many
SELECT rs.provider,
       rs.shard,
       (SELECT count(*) FROM ingest_run_state peer WHERE peer.provider = rs.provider)::int AS shards,
       COALESCE(s.timeout_sec, $1::int) AS timeout_sec
FROM ingest_run_state rs
LEFT JOIN ingest_schedule s ON s.provider = rs.provider
WHERE ((rs.claimed_at IS NULL AND rs.next_due_at <= now())
    OR (rs.claimed_at IS NOT NULL
        AND rs.claimed_at < now() - make_interval(
                secs => COALESCE(s.timeout_sec, $1::int)
                        + $2::int)))
    -- ROLLOUT GATE, removed with the column in task 8.5 of
    -- openspec/changes/ingest-scheduler-in-db. Run state is tracked for every enabled
    -- provider so the stagger and the shadow preview exist from day one; what ` + "`" + `managed` + "`" + `
    -- decides is whether the SCHEDULER may launch it, or whether its static timer still
    -- owns it. COALESCE to false: while the column exists, a provider nobody has handed
    -- over is still the static timer's.
    AND COALESCE(s.managed, false)
ORDER BY rs.next_due_at
LIMIT $3
`

type PreviewDueRunsParams struct {
	DefaultTimeoutSec int32 `json:"default_timeout_sec"`
	GraceSec          int32 `json:"grace_sec"`
	MaxRuns           int32 `json:"max_runs"`
}

type PreviewDueRunsRow struct {
	Provider   string `json:"provider"`
	Shard      int32  `json:"shard"`
	Shards     int32  `json:"shards"`
	TimeoutSec int32  `json:"timeout_sec"`
}

// What ClaimDueRuns WOULD take, without taking it. Shadow mode's read: the first
// deployment lands underneath a fleet still driven by the static timers, so a tick that
// advanced a due time would desynchronise state the real timers know nothing about.
//
// The predicate is copied from ClaimDueRuns rather than shared, because sqlc has no way to
// share one. A divergence between the two would make the shadow run a measurement of
// something other than what apply mode does, so they are asserted equivalent by an
// integration test rather than by inspection.
func (q *Queries) PreviewDueRuns(ctx context.Context, arg PreviewDueRunsParams) ([]PreviewDueRunsRow, error) {
	rows, err := q.db.Query(ctx, previewDueRuns, arg.DefaultTimeoutSec, arg.GraceSec, arg.MaxRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PreviewDueRunsRow{}
	for rows.Next() {
		var i PreviewDueRunsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Shard,
			&i.Shards,
			&i.TimeoutSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRunFinish = `-- name: RecordRunFinish :exec
UPDATE ingest_run_state
SET claimed_at       = NULL,
    last_finished_at = now(),
    last_exit_code   = $1::int,
    last_error       = NULLIF($2::text, '')
WHERE provider = $3 AND shard = $4::int
`

type RecordRunFinishParams struct {
	ExitCode  int32  `json:"exit_code"`
	LastError string `json:"last_error"`
	Provider  string `json:"provider"`
	Shard     int32  `json:"shard"`
}

// Store how a run ended and release its claim, so the row is claimable again at its next
// due time. Clearing claimed_at here is what keeps the reclaim window for genuinely stuck
// runs rather than for every run that took a while.
func (q *Queries) RecordRunFinish(ctx context.Context, arg RecordRunFinishParams) error {
	_, err := q.db.Exec(ctx, recordRunFinish,
		arg.ExitCode,
		arg.LastError,
		arg.Provider,
		arg.Shard,
	)
	return err
}

const reportIngestSchedule = `-- name: ReportIngestSchedule :many
SELECT b.provider,
       s.shards,
       s.cadence_sec,
       s.timeout_sec,
       s.enabled,
       s.disabled_reason,
       s.notes,
       s.managed,
       COALESCE(rs.shards_in_state, 0)::int AS shards_in_state,
       COALESCE(rs.in_flight, 0)::int       AS in_flight,
       rs.next_due_at,
       rs.last_finished_at
FROM (SELECT DISTINCT provider FROM boards WHERE status IN ('pending', 'active')) b
LEFT JOIN ingest_schedule s ON s.provider = b.provider
LEFT JOIN (
    SELECT provider,
           count(*)                                        AS shards_in_state,
           count(*) FILTER (WHERE claimed_at IS NOT NULL)  AS in_flight,
           min(next_due_at)::timestamptz                   AS next_due_at,
           max(last_finished_at)::timestamptz              AS last_finished_at
    FROM ingest_run_state
    GROUP BY provider
) rs ON rs.provider = b.provider
ORDER BY b.provider
`

type ReportIngestScheduleRow struct {
	Provider       string             `json:"provider"`
	Shards         pgtype.Int4        `json:"shards"`
	CadenceSec     pgtype.Int4        `json:"cadence_sec"`
	TimeoutSec     pgtype.Int4        `json:"timeout_sec"`
	Enabled        pgtype.Bool        `json:"enabled"`
	DisabledReason pgtype.Text        `json:"disabled_reason"`
	Notes          pgtype.Text        `json:"notes"`
	Managed        pgtype.Bool        `json:"managed"`
	ShardsInState  int32              `json:"shards_in_state"`
	InFlight       int32              `json:"in_flight"`
	NextDueAt      pgtype.Timestamptz `json:"next_due_at"`
	LastFinishedAt pgtype.Timestamptz `json:"last_finished_at"`
}

// The whole schedule as an operator reads it: every eligible provider, its override if it
// has one, and what its runs have actually been doing. Aggregated per provider rather than
// per shard, because the question this answers is "is anything not running?" and 24
// paylocity rows would bury the answer.
//
// shards_in_state is counted from run state rather than read from the override, for the
// same reason ClaimDueRuns counts it: the rows ARE the shard count, and a report that read
// the intended number instead would show a healthy 24 while 12 rows existed.
func (q *Queries) ReportIngestSchedule(ctx context.Context) ([]ReportIngestScheduleRow, error) {
	rows, err := q.db.Query(ctx, reportIngestSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportIngestScheduleRow{}
	for rows.Next() {
		var i ReportIngestScheduleRow
		if err := rows.Scan(
			&i.Provider,
			&i.Shards,
			&i.CadenceSec,
			&i.TimeoutSec,
			&i.Enabled,
			&i.DisabledReason,
			&i.Notes,
			&i.Managed,
			&i.ShardsInState,
			&i.InFlight,
			&i.NextDueAt,
			&i.LastFinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngestSchedule = `-- name: UpsertIngestSchedule :exec
INSERT INTO ingest_schedule (provider, shards, cadence_sec, timeout_sec,
                             enabled, disabled_reason, notes, managed)
VALUES ($1,
        COALESCE($2::int, 1),
        COALESCE($3::int, 3600),
        COALESCE($4::int, 3000),
        COALESCE($5::boolean, true),
        $6::text,
        $7::text,
        COALESCE($8::boolean, false))
ON CONFLICT (provider) DO UPDATE SET
    shards          = COALESCE($2::int, ingest_schedule.shards),
    cadence_sec     = COALESCE($3::int, ingest_schedule.cadence_sec),
    timeout_sec     = COALESCE($4::int, ingest_schedule.timeout_sec),
    enabled         = COALESCE($5::boolean, ingest_schedule.enabled),
    disabled_reason = COALESCE($6::text, ingest_schedule.disabled_reason),
    notes           = COALESCE($7::text, ingest_schedule.notes),
    managed         = COALESCE($8::boolean, ingest_schedule.managed),
    updated_at      = now()
`

type UpsertIngestScheduleParams struct {
	Provider       string      `json:"provider"`
	Shards         pgtype.Int4 `json:"shards"`
	CadenceSec     pgtype.Int4 `json:"cadence_sec"`
	TimeoutSec     pgtype.Int4 `json:"timeout_sec"`
	Enabled        pgtype.Bool `json:"enabled"`
	DisabledReason pgtype.Text `json:"disabled_reason"`
	Notes          pgtype.Text `json:"notes"`
	Managed        pgtype.Bool `json:"managed"`
}

// Write one provider's override. Every argument is optional: a NULL means "leave this
// alone" on an existing row and "use the documented default" on a new one, so a curator
// changing only the shard count does not silently reset the cadence someone measured.
//
// The CHECK on the table still decides whether the result is legal — disabling without a
// reason is refused here exactly as it is in psql, which is the point of putting the rule
// in the schema.
func (q *Queries) UpsertIngestSchedule(ctx context.Context, arg UpsertIngestScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertIngestSchedule,
		arg.Provider,
		arg.Shards,
		arg.CadenceSec,
		arg.TimeoutSec,
		arg.Enabled,
		arg.DisabledReason,
		arg.Notes,
		arg.Managed,
	)
	return err
}
