// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limitnudge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLimitHitUsersMissingNudgeEmail = `-- name: ListLimitHitUsersMissingNudgeEmail :many
SELECT u.id, u.email
FROM (
    SELECT DISTINCT user_id
    FROM plan_limit_hits
    WHERE day > current_date - make_interval(days => $1::int)
) h
JOIN users u ON u.id = h.user_id
LEFT JOIN notification_settings ns ON ns.user_id = u.id
WHERE u.email_verified
  AND u.limit_nudge_sent_at IS NULL
  AND (u.pro_until IS NULL OR u.pro_until <= now())
  AND (u.ultra_until IS NULL OR u.ultra_until <= now())
  AND COALESCE(ns.news_email_enabled, true)
ORDER BY u.id
LIMIT $2::int
`

type ListLimitHitUsersMissingNudgeEmailParams struct {
	WindowDays int32 `json:"window_days"`
	MaxRows    int32 `json:"max_rows"`
}

type ListLimitHitUsersMissingNudgeEmailRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

// Free-tier accounts that hit a plan ceiling at least once in the last window_days,
// verified, opted in to news mail, and not yet sent the one-time nudge.
//
// Driven from plan_limit_hits rather than from users: the hits table only ever holds
// free-tier refusals, so it is the selective side of the join — reading it first and
// joining out to users is a handful of rows, where starting from users and testing
// each one against it would be a sequential scan of the whole table.
//
// The tier check mirrors plan.TierOf's own rule directly rather than calling it: free
// is "neither until reaches past now", and a NULL until reads the same as a past one.
func (q *Queries) ListLimitHitUsersMissingNudgeEmail(ctx context.Context, arg ListLimitHitUsersMissingNudgeEmailParams) ([]ListLimitHitUsersMissingNudgeEmailRow, error) {
	rows, err := q.db.Query(ctx, listLimitHitUsersMissingNudgeEmail, arg.WindowDays, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLimitHitUsersMissingNudgeEmailRow{}
	for rows.Next() {
		var i ListLimitHitUsersMissingNudgeEmailRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPlanLimitHit = `-- name: RecordPlanLimitHit :exec

INSERT INTO plan_limit_hits (user_id, feature, day)
VALUES ($1, $2::text, $3)
ON CONFLICT (user_id, feature, day) DO NOTHING
`

type RecordPlanLimitHitParams struct {
	UserID  int64       `json:"user_id"`
	Feature string      `json:"feature"`
	Day     pgtype.Date `json:"day"`
}

// Queries for the limit-nudge feature (internal/engage/limitnudge): one personal mail,
// sent once per account, to a free-tier user who has run into a plan ceiling.
// Records that a real plan-ceiling refusal happened for (user, feature, day) — any
// tier, see migration 0178 — deduped by the primary key, so a retried request that
// hits the same wall again the same day writes nothing further. Called from
// plan.Store.Consume on every real refusal (not FairUse, not Shadowed); see that
// file for the distinction.
func (q *Queries) RecordPlanLimitHit(ctx context.Context, arg RecordPlanLimitHitParams) error {
	_, err := q.db.Exec(ctx, recordPlanLimitHit, arg.UserID, arg.Feature, arg.Day)
	return err
}

const setLimitNudgeSent = `-- name: SetLimitNudgeSent :execrows
UPDATE users
SET limit_nudge_sent_at = now()
WHERE id = $1
  AND limit_nudge_sent_at IS NULL
`

// Claims the nudge send for one account. Guarded by IS NULL so a concurrent or
// repeated run never re-sends; 0 rows affected means somebody already claimed it.
func (q *Queries) SetLimitNudgeSent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setLimitNudgeSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
