// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumptionExists = `-- name: ConsumptionExists :one
SELECT EXISTS (
    SELECT 1 FROM usage_ledger
    WHERE user_id = $1
      AND kind = 'consume'
      AND feature = $2::text
      AND ref = $3::text
)
`

type ConsumptionExistsParams struct {
	UserID  int64  `json:"user_id"`
	Feature string `json:"feature"`
	Ref     string `json:"ref"`
}

// Whether this (feature, ref) was already charged. True means the caller is retrying,
// reconnecting, or recomputing work already paid for, and must not be charged again.
func (q *Queries) ConsumptionExists(ctx context.Context, arg ConsumptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, consumptionExists, arg.UserID, arg.Feature, arg.Ref)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countConsumptionsByRefPrefix = `-- name: CountConsumptionsByRefPrefix :one
SELECT count(*)
FROM usage_ledger
WHERE user_id = $1
  AND kind = 'consume'
  AND feature = $2::text
  AND ref LIKE $3::text || '%'
`

type CountConsumptionsByRefPrefixParams struct {
	UserID    int64  `json:"user_id"`
	Feature   string `json:"feature"`
	RefPrefix string `json:"ref_prefix"`
}

// How many consumptions a user holds for refs beginning with a prefix. This is what makes
// the tailoring turn ceiling need no column of its own: a session's charges are written
// as '<session_id>#1', '#2', and so on, so counting them gives the number of ceilings
// bought, and the ceiling in force is that count times the per-session turn allowance.
//
// The prefix is passed already terminated by the caller (the session id plus '#'), so a
// session id that is a prefix of another cannot borrow its charges.
func (q *Queries) CountConsumptionsByRefPrefix(ctx context.Context, arg CountConsumptionsByRefPrefixParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsumptionsByRefPrefix, arg.UserID, arg.Feature, arg.RefPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConsumption = `-- name: DeleteConsumption :execrows
DELETE FROM usage_ledger
WHERE user_id = $1
  AND kind = 'consume'
  AND feature = $2::text
  AND ref = $3::text
`

type DeleteConsumptionParams struct {
	UserID  int64  `json:"user_id"`
	Feature string `json:"feature"`
	Ref     string `json:"ref"`
}

// Void a consumption taken as a RESERVATION for work that then produced nothing.
//
// It deletes rather than appending a compensating row, and the unique index forces that:
// at most one consumption may exist per (user, feature, ref), so a compensating entry
// would leave the ref permanently spent and the user's retry would find it already
// charged and never re-reserve. Deleting frees the ref.
//
// Returns the number of rows removed, so the caller gives the allowance back exactly when
// it really took one — a double release, or a release of something already voided,
// removes nothing and returns 0. That is what lets every failure path call this without
// first working out whether it owes one.
func (q *Queries) DeleteConsumption(ctx context.Context, arg DeleteConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConsumption, arg.UserID, arg.Feature, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUsageDailyForUser = `-- name: DeleteUsageDailyForUser :exec
DELETE FROM usage_daily WHERE user_id = $1
`

// Erase one user's daily counters. See DeleteUsageForUser.
func (q *Queries) DeleteUsageDailyForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUsageDailyForUser, userID)
	return err
}

const deleteUsageForUser = `-- name: DeleteUsageForUser :exec
DELETE FROM usage_ledger WHERE user_id = $1
`

// Erase one user's consumption ledger. Account deletion calls this alongside the counter
// delete; the foreign keys cascade, but deletion states what it erases explicitly rather
// than relying on a constraint to mean it.
func (q *Queries) DeleteUsageForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUsageForUser, userID)
	return err
}

const ensureUsageDay = `-- name: EnsureUsageDay :exec
INSERT INTO usage_daily (user_id, feature, day, used)
VALUES ($1, $2::text, $3, 0)
ON CONFLICT (user_id, feature, day) DO NOTHING
`

type EnsureUsageDayParams struct {
	UserID  int64       `json:"user_id"`
	Feature string      `json:"feature"`
	Day     pgtype.Date `json:"day"`
}

// Seed today's counter for (user, feature) so the SELECT ... FOR UPDATE below always has
// a row to lock. That lock is what serialises two simultaneous first-ever consumptions,
// so an allowance can never be oversold by a race. An existing row is left untouched.
func (q *Queries) EnsureUsageDay(ctx context.Context, arg EnsureUsageDayParams) error {
	_, err := q.db.Exec(ctx, ensureUsageDay, arg.UserID, arg.Feature, arg.Day)
	return err
}

const getConsumptionDay = `-- name: GetConsumptionDay :one
SELECT day
FROM usage_ledger
WHERE user_id = $1
  AND kind = 'consume'
  AND feature = $2::text
  AND ref = $3::text
`

type GetConsumptionDayParams struct {
	UserID  int64  `json:"user_id"`
	Feature string `json:"feature"`
	Ref     string `json:"ref"`
}

// Which day a consumption was recorded against, read WITHOUT a lock.
//
// A release must decrement the counter of the day the charge landed on, not of the day
// the release happens — otherwise a reservation taken at 23:59 and released at 00:01
// gives back an allowance the user never spent today, and the day it really spent stays
// spent. Reading it first is also what keeps the lock order the same in both directions:
// every path takes usage_daily before usage_ledger, so a consumption and a release for
// the same user cannot deadlock each other.
//
// No rows means nothing was charged under this reference, and the release is a no-op.
func (q *Queries) GetConsumptionDay(ctx context.Context, arg GetConsumptionDayParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getConsumptionDay, arg.UserID, arg.Feature, arg.Ref)
	var day pgtype.Date
	err := row.Scan(&day)
	return day, err
}

const getProUntil = `-- name: GetProUntil :one
SELECT pro_until
FROM users
WHERE id = $1
`

// The whole of a user's plan. A timestamp in the future means pro; NULL or a past one
// means free. Read on the request path of every metered action, which is why it is a
// column read and never a call to a billing provider: a provider that is slow must not
// be able to slow down a user's next question.
func (q *Queries) GetProUntil(ctx context.Context, id int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getProUntil, id)
	var pro_until pgtype.Timestamptz
	err := row.Scan(&pro_until)
	return pro_until, err
}

const getUsageDayForUpdate = `-- name: GetUsageDayForUpdate :one
SELECT used
FROM usage_daily
WHERE user_id = $1
  AND feature = $2::text
  AND day = $3
FOR UPDATE
`

type GetUsageDayForUpdateParams struct {
	UserID  int64       `json:"user_id"`
	Feature string      `json:"feature"`
	Day     pgtype.Date `json:"day"`
}

// Lock today's counter for the consumption transaction. EnsureUsageDay guarantees the row
// exists, so this never returns no-rows on that path.
func (q *Queries) GetUsageDayForUpdate(ctx context.Context, arg GetUsageDayForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUsageDayForUpdate, arg.UserID, arg.Feature, arg.Day)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const insertConsumption = `-- name: InsertConsumption :exec
INSERT INTO usage_ledger (user_id, feature, day, kind, delta, ref)
VALUES ($1, $2::text, $3, 'consume', $4, $5::text)
`

type InsertConsumptionParams struct {
	UserID  int64       `json:"user_id"`
	Feature string      `json:"feature"`
	Day     pgtype.Date `json:"day"`
	Delta   int64       `json:"delta"`
	Ref     string      `json:"ref"`
}

// Append the consumption for a metered action; delta is positive and counts units taken.
// The partial unique index on (user_id, feature, ref) WHERE kind='consume' guards against
// a double charge for the same ref even under a race.
func (q *Queries) InsertConsumption(ctx context.Context, arg InsertConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertConsumption,
		arg.UserID,
		arg.Feature,
		arg.Day,
		arg.Delta,
		arg.Ref,
	)
	return err
}

const listUsageForDay = `-- name: ListUsageForDay :many
SELECT feature, used
FROM usage_daily
WHERE user_id = $1
  AND day = $2
`

type ListUsageForDayParams struct {
	UserID int64       `json:"user_id"`
	Day    pgtype.Date `json:"day"`
}

type ListUsageForDayRow struct {
	Feature string `json:"feature"`
	Used    int64  `json:"used"`
}

// Every feature's consumption for one user on one day, for the usage surface. A feature
// the user has not touched today simply does not come back, and the caller reports it as
// untouched rather than as absent.
func (q *Queries) ListUsageForDay(ctx context.Context, arg ListUsageForDayParams) ([]ListUsageForDayRow, error) {
	rows, err := q.db.Query(ctx, listUsageForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageForDayRow{}
	for rows.Next() {
		var i ListUsageForDayRow
		if err := rows.Scan(&i.Feature, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLedger = `-- name: ListUsageLedger :many
SELECT feature, day, kind, delta, ref, created_at
FROM usage_ledger
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUsageLedgerParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListUsageLedgerRow struct {
	Feature   string             `json:"feature"`
	Day       pgtype.Date        `json:"day"`
	Kind      string             `json:"kind"`
	Delta     int64              `json:"delta"`
	Ref       pgtype.Text        `json:"ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The caller's ledger entries, newest first, bounded by a caller-supplied limit and served
// by the (user_id, created_at DESC) index.
func (q *Queries) ListUsageLedger(ctx context.Context, arg ListUsageLedgerParams) ([]ListUsageLedgerRow, error) {
	rows, err := q.db.Query(ctx, listUsageLedger, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageLedgerRow{}
	for rows.Next() {
		var i ListUsageLedgerRow
		if err := rows.Scan(
			&i.Feature,
			&i.Day,
			&i.Kind,
			&i.Delta,
			&i.Ref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProUntil = `-- name: SetProUntil :exec
UPDATE users
SET pro_until = $1
WHERE id = $2
`

type SetProUntilParams struct {
	ProUntil pgtype.Timestamptz `json:"pro_until"`
	ID       int64              `json:"id"`
}

// Move a user's plan expiry. The only writer today is a hand-run statement; the billing
// webhook and its reconciler become the writers in the change that adds them, and they
// write this and nothing else.
func (q *Queries) SetProUntil(ctx context.Context, arg SetProUntilParams) error {
	_, err := q.db.Exec(ctx, setProUntil, arg.ProUntil, arg.ID)
	return err
}

const setUsageDay = `-- name: SetUsageDay :exec
UPDATE usage_daily
SET used = $1, updated_at = now()
WHERE user_id = $2
  AND feature = $3::text
  AND day = $4
`

type SetUsageDayParams struct {
	Used    int64       `json:"used"`
	UserID  int64       `json:"user_id"`
	Feature string      `json:"feature"`
	Day     pgtype.Date `json:"day"`
}

// Persist the post-transaction counter. The row is guaranteed to exist (EnsureUsageDay
// ran first). Yesterday's rows are simply left behind rather than reset: a day that has
// rolled over is answered by a different key, so nothing has to expire anything and no
// scheduled job exists to forget to run.
func (q *Queries) SetUsageDay(ctx context.Context, arg SetUsageDayParams) error {
	_, err := q.db.Exec(ctx, setUsageDay,
		arg.Used,
		arg.UserID,
		arg.Feature,
		arg.Day,
	)
	return err
}
