// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission_domain_blocklist.sql

package db

import (
	"context"
)

const blockHost = `-- name: BlockHost :exec
INSERT INTO submission_domain_blocklist (host, blocked_by, reason)
VALUES ($1, $2::bigint, $3)
ON CONFLICT (host) DO NOTHING
`

type BlockHostParams struct {
	Host      string `json:"host"`
	BlockedBy int64  `json:"blocked_by"`
	Reason    string `json:"reason"`
}

// Add a host to the blocklist, attributed to the blocking moderator. ON CONFLICT DO NOTHING
// makes blocking an already-blocked host a no-op rather than an error (submission.Service.Reject
// calls this every time block_domain is set, whether or not the host is new).
func (q *Queries) BlockHost(ctx context.Context, arg BlockHostParams) error {
	_, err := q.db.Exec(ctx, blockHost, arg.Host, arg.BlockedBy, arg.Reason)
	return err
}

const isHostBlocked = `-- name: IsHostBlocked :one
SELECT EXISTS (
    SELECT 1 FROM submission_domain_blocklist WHERE host = $1
) AS blocked
`

// Whether a normalized host (see submission.normalizeHost) is on the submission blocklist.
func (q *Queries) IsHostBlocked(ctx context.Context, host string) (bool, error) {
	row := q.db.QueryRow(ctx, isHostBlocked, host)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}
