// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package db

import (
	"context"
)

const mineJobTitles = `-- name: MineJobTitles :many
SELECT title, count(*) AS count
FROM jobs
WHERE closed_at IS NULL
  AND title <> ''
GROUP BY title
`

type MineJobTitlesRow struct {
	Title string `json:"title"`
	Count int64  `json:"count"`
}

// Raw posting titles with their counts, the source of the suggestion dictionary
// (cmd/build-suggestions).
//
// Grouped HERE rather than streamed row by row: the open catalogue is ~1.8M postings
// written with far fewer distinct titles, so aggregating in Postgres keeps the wire
// and the worker's memory proportional to the vocabulary rather than to the
// catalogue.
//
// Normalisation is deliberately NOT done here, and neither is the frequency floor.
// `suggest.Title` is one function shared with the query path — a SQL copy would drift
// — and the floor has to be applied AFTER it: "Product Owner", "product owner" and
// "PRODUCT OWNER" are three rows here and one suggestion, so a floor applied to these
// counts would drop a title that clears it comfortably once merged.
func (q *Queries) MineJobTitles(ctx context.Context) ([]MineJobTitlesRow, error) {
	rows, err := q.db.Query(ctx, mineJobTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MineJobTitlesRow{}
	for rows.Next() {
		var i MineJobTitlesRow
		if err := rows.Scan(&i.Title, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestibleCompanies = `-- name: SuggestibleCompanies :many
SELECT slug, name, job_count
FROM companies
WHERE job_count >= $1::int
ORDER BY job_count DESC, name
`

type SuggestibleCompaniesRow struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	JobCount int32  `json:"job_count"`
}

// Companies worth offering as a suggestion, busiest first. Reads the denormalized
// companies.job_count (maintained by cmd/recount-companies), so this does not join
// jobs.
//
// The floor is what keeps the long tail of one-posting slugs — many of them job
// titles that landed in an employer column — out of a dictionary meant to name real
// employers.
func (q *Queries) SuggestibleCompanies(ctx context.Context, minJobs int32) ([]SuggestibleCompaniesRow, error) {
	rows, err := q.db.Query(ctx, suggestibleCompanies, minJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestibleCompaniesRow{}
	for rows.Next() {
		var i SuggestibleCompaniesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
