// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const deleteWebhookConfig = `-- name: DeleteWebhookConfig :execrows
DELETE FROM webhook_configs
WHERE user_id = $1
`

func (q *Queries) DeleteWebhookConfig(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookConfig, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableWebhookConfig = `-- name: DisableWebhookConfig :execrows
UPDATE webhook_configs
SET enabled = false,
    disabled_at = now(),
    updated_at = now()
WHERE user_id = $1 AND enabled
`

// Disables the destination, stamping disabled_at. Used both by the settings
// API (user-initiated) and by the notify delivery engine when a send gets a
// definitive 410 Gone from the destination (see internal/engage/webhooknotify).
// Returns the affected row count: 0 means there was no destination to disable
// (or it was already disabled by an earlier subscription in the same pass).
func (q *Queries) DisableWebhookConfig(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, disableWebhookConfig, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableWebhookConfig = `-- name: EnableWebhookConfig :one
UPDATE webhook_configs
SET enabled = true,
    disabled_at = NULL,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, url, enabled, created_at, updated_at, last_success_at, disabled_at
`

// Re-enables a user-disabled (or auto-disabled) webhook destination without
// changing its URL.
func (q *Queries) EnableWebhookConfig(ctx context.Context, userID int64) (WebhookConfig, error) {
	row := q.db.QueryRow(ctx, enableWebhookConfig, userID)
	var i WebhookConfig
	err := row.Scan(
		&i.UserID,
		&i.URL,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWebhookConfig = `-- name: GetWebhookConfig :one
SELECT user_id, url, enabled, created_at, updated_at, last_success_at, disabled_at
FROM webhook_configs
WHERE user_id = $1
`

// The user's webhook destination, if any. No row means the user has never
// configured one — the caller (both the settings API and delivery's recipient
// resolution) treats absence as "not configured" rather than an error.
func (q *Queries) GetWebhookConfig(ctx context.Context, userID int64) (WebhookConfig, error) {
	row := q.db.QueryRow(ctx, getWebhookConfig, userID)
	var i WebhookConfig
	err := row.Scan(
		&i.UserID,
		&i.URL,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}

const recordWebhookDeliverySuccess = `-- name: RecordWebhookDeliverySuccess :exec
UPDATE webhook_configs
SET last_success_at = now()
WHERE user_id = $1
`

// Stamps last_success_at after a delivery succeeds. Not gated on `enabled` —
// a disabled destination is never delivered to (soft-skipped upstream), so
// this only ever runs for an enabled one.
func (q *Queries) RecordWebhookDeliverySuccess(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, recordWebhookDeliverySuccess, userID)
	return err
}

const upsertWebhookConfig = `-- name: UpsertWebhookConfig :one
INSERT INTO webhook_configs (user_id, url, enabled, updated_at, disabled_at)
VALUES ($1, $2, true, now(), NULL)
ON CONFLICT (user_id) DO UPDATE
SET url = EXCLUDED.url,
    enabled = true,
    disabled_at = NULL,
    updated_at = now()
RETURNING user_id, url, enabled, created_at, updated_at, last_success_at, disabled_at
`

type UpsertWebhookConfigParams struct {
	UserID int64  `json:"user_id"`
	URL    string `json:"url"`
}

// Creates the account's webhook destination, or updates its URL if one
// already exists — there is exactly one row per user (see migration 0135).
// Saving re-enables a previously disabled destination and clears
// disabled_at, since submitting the form is an explicit re-commitment to
// the endpoint.
func (q *Queries) UpsertWebhookConfig(ctx context.Context, arg UpsertWebhookConfigParams) (WebhookConfig, error) {
	row := q.db.QueryRow(ctx, upsertWebhookConfig, arg.UserID, arg.URL)
	var i WebhookConfig
	err := row.Scan(
		&i.UserID,
		&i.URL,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}
