import { GHOST_CRITERION_VALUES } from './generated/contracts';
import type { Ghost, GhostCriterion } from './generated/contracts';
import { timeAgo } from './utils';

/** A rendered ghost badge: a tone, a hedged chip label, the `fired/total` scale, and
 *  the hover justification.
 *
 *  The wording is hedged at every level by design. The system observes facts about a
 *  posting — how long it has been up, whether the employer's own board carries it,
 *  whether people who applied were answered — and never an employer's intent. "Open
 *  240 days, found only on an aggregator" is a claim about observables; "ghost job"
 *  is a claim about a state of mind we cannot see. So the word `ghost` stays in the
 *  code and never reaches the interface. */
export interface GhostBadge {
  tone: 'warn' | 'muted';
  label: string;
  scale: string;
  tooltip: string;
}

/** A rendered gauge: how many segments to draw, how many to fill, and how loudly.
 *
 *  The gauge fills with risk rather than draining like a battery, and only fired
 *  criteria are coloured. The served payload distinguishes a criterion that fired
 *  from one that did not, and never a criterion checked and found clear from one with
 *  no data at all — so an unfilled segment means "not observed" and must not be drawn
 *  in a tone that reads as reassurance. */
export interface GhostGauge {
  segments: number;
  filled: number;
  tone: GhostGaugeTone;
}

/** The escalation ladder, low to severe. Four rungs where the wording has two levels:
 *  the gauge is what tells one-of-four from three-of-four at a glance. */
export type GhostGaugeTone = 'low' | 'elevated' | 'high' | 'severe';

/** One row of the checklist: a criterion, whether it fired, and the facts behind it
 *  where the payload carries any — `detail` is empty for a criterion whose firing IS
 *  the fact, and for every criterion that did not fire.
 *
 *  `short` names the criterion for a list, where `label` states it as a sentence. A
 *  fired criterion earns its own row and reads as the sentence; the unfired ones
 *  collapse into one summary line, and four sentences do not survive being joined by
 *  commas. */
export interface GhostChecklistRow {
  code: string;
  label: string;
  short: string;
  detail: string;
  fired: boolean;
}

/** The criterion codes, as a union rather than `string` — generated by
 *  `cmd/gen-contracts` from `internal/ghost`'s own list, so this IS the classifier's
 *  vocabulary rather than a transcription of it that has to be kept honest by hand.
 *
 *  What it buys: the tables that must have an entry per criterion — the wording below and
 *  the landing's diagram registry — are keyed by this union, so a criterion that joins the
 *  classifier without one is a compile error rather than a blank cell on the page. The
 *  diagram half could not have been a test: vitest here cannot import a `.svelte`
 *  component without test infrastructure this project does not carry. (The landing's prose
 *  explanations stay a test — `ghostSignals.ts` drops an unexplained criterion rather than
 *  half-rendering it, and ghostSignals.test.ts fails on the gap.) */
export type GhostCriterionCode = GhostCriterion;

/** How the interface words each criterion.
 *
 *  A `Record` over the generated union rather than a hand-written array, because drift ran
 *  in two directions and both were real. A code here the classifier never reports rendered
 *  a row that could never fire. A criterion the classifier reports with no entry here was
 *  worse: the gauge fills from `ghost.criteria.length`, so it coloured a segment with no
 *  ticked row beneath it and the count and the list disagreed — the interface asserting
 *  evidence it cannot show, which is the one thing this feature must never do. Keyed this
 *  way, both are type errors.
 *
 *  `short` names the criterion for a list, where `label` states it as a sentence. */
const WORDING: Record<
  GhostCriterionCode,
  { label: string; short: string; tier: 'structural' | 'outcome' }
> = {
  evergreen_posting: {
    label: 'Posting behaves as evergreen',
    short: 'how the posting behaves',
    tier: 'structural',
  },
  ats_absent: {
    label: "Not on the company's own careers board",
    short: "the company's own board",
    tier: 'structural',
  },
  silent_applications: {
    label: 'Applications here went unanswered',
    short: 'applications here',
    tier: 'outcome',
  },
  user_reports: {
    label: 'People reported no response',
    short: 'reports from people',
    tier: 'outcome',
  },
};

/** The criteria in the order the classifier reports them: structural first, then
 *  outcome. The order comes from the generated vocabulary rather than from the way this
 *  file happens to be typed out — it is a fact about `internal/ghost`, and the checklist
 *  renders in it.
 *
 *  Exported because the /features/ghost-jobs landing explains them from this same
 *  array, and a test fails if a criterion joins the vocabulary without being
 *  explained there. A marketing page a test keeps honest. */
export const CRITERIA = GHOST_CRITERION_VALUES.map((code) => ({ code, ...WORDING[code] }));

/** How many criteria must fire, of any tier, before the signal says anything. */
export const CONVERGENCE = 2;

/** How many DISTINCT people must contribute outcome evidence for the stronger claim —
 *  and the reason a contributor count is never served below it. */
export const WITNESS_GATE = 2;

/** The levels the classifier reports. `none` is most of the catalogue. */
export type GhostLevel = 'none' | 'possible' | 'likely';

const OUTCOME_CODES: ReadonlySet<string> = new Set(
  CRITERIA.filter((c) => c.tier === 'outcome').map((c) => c.code),
);

/** ghostLevel derives the level from the criteria that fired and the number of distinct
 *  people behind the outcome evidence. Mirrors internal/ghost, which remains the
 *  authority — the served payload's `level` is what a job actually carries, and this is
 *  here so the /features/ghost-jobs landing can demonstrate the ladder rather than
 *  assert it in prose no test can check.
 *
 *  Two independent gates: convergence, and witnesses. Both pass → `likely`, exactly one
 *  → `possible`, neither → `none`. The witness gate stands on its own because two
 *  strangers independently reporting silence is a stronger fact than any two artifacts of
 *  posting shape, and requiring structural corroboration would leave the only tier that
 *  observes reality unable to mark anything by itself.
 *
 *  The witness gate additionally requires that an outcome criterion actually fired. That
 *  looks redundant — contributors come from outcome evidence, so a real payload cannot
 *  carry one without the other — but the landing's sandbox moves the criteria and the
 *  contributor count independently, and a rule that trusted its caller would render
 *  `likely` from posting shape alone. That is the one claim the feature must never make,
 *  so the guarantee lives here rather than in the caller's discipline. */
export function ghostLevel(criteria: readonly string[], contributors: number): GhostLevel {
  const converged = criteria.length >= CONVERGENCE;
  const witnessed = contributors >= WITNESS_GATE && criteria.some((c) => OUTCOME_CODES.has(c));

  if (converged && witnessed) return 'likely';
  if (converged || witnessed) return 'possible';
  return 'none';
}

const LABELS: Record<string, { tone: 'warn' | 'muted'; label: string }> = {
  possible: { tone: 'muted', label: 'Possibly inactive' },
  likely: { tone: 'warn', label: 'Likely inactive' },
};

/** ghostBadge maps the served signal to a chip, or null when there is nothing to
 *  show. An unrecognised level yields null rather than an empty chip: a badge beside
 *  a job that says nothing is worse than no badge. */
export function ghostBadge(ghost?: Ghost | null): GhostBadge | null {
  if (!ghost) return null;
  const shape = LABELS[ghost.level];
  if (!shape) return null;

  const fired = ghost.criteria.length;
  const tooltip = ghostChecklist(ghost)
    .filter((r) => r.fired)
    .map((r) => r.label)
    .join(' · ');
  return {
    tone: shape.tone,
    label: shape.label,
    scale: `${fired}/${ghost.criteria_total}`,
    tooltip,
  };
}

/** ghostGauge projects the signal onto the segmented gauge the job page renders, or
 *  null wherever the chip itself would show nothing.
 *
 *  The tone comes from the SHARE of criteria that fired, not from `level` and not from
 *  the raw count. Not `level`, because it has two values where the gauge has four
 *  states worth telling apart. Not the raw count, because the denominator is served:
 *  the day the classifier gains a fifth criterion, thresholds pinned to absolute
 *  counts would read three-of-five as loudly as three-of-four. `level` keeps driving
 *  the wording, which stays the authoritative claim — a strongly toned gauge under
 *  "Possibly inactive" is three criteria firing, not a stronger accusation. */
export function ghostGauge(ghost?: Ghost | null): GhostGauge | null {
  if (!ghost || !ghostBadge(ghost)) return null;

  const segments = ghost.criteria_total;
  // A payload claiming more fired criteria than the scale's denominator must not
  // paint segments that do not exist.
  const filled = Math.min(ghost.criteria.length, segments);
  if (segments < 1 || filled < 1) return null;

  return { segments, filled, tone: toneFor(filled / segments) };
}

function toneFor(share: number): GhostGaugeTone {
  if (share >= 1) return 'severe';
  if (share > 0.5) return 'high';
  if (share > 0.25) return 'elevated';
  return 'low';
}

/** supersedesReality reports whether the ghost badge replaces the reality badge.
 *
 *  `evergreen_posting` IS the reality verdict, so rendering both shows one fact
 *  twice, the second time louder. Where ghost is silent the reality badge renders
 *  unchanged. */
export function supersedesReality(ghost?: Ghost | null): boolean {
  return ghostBadge(ghost) !== null;
}

/** ghostChecklist projects every criterion the classifier considers — including the
 *  ones that did not fire.
 *
 *  Accounting for the unfired ones is the point rather than clutter: it tells the
 *  reader WHY the level is not higher, instead of leaving them to guess how serious
 *  this is. The interface renders the fired ones as rows and hands the rest to
 *  ghostUnobserved, which names them in a single line. */
export function ghostChecklist(ghost: Ghost): GhostChecklistRow[] {
  const fired = new Set(ghost.criteria);
  return CRITERIA.map(({ code, label, short }) => ({
    code,
    label,
    short,
    fired: fired.has(code),
    detail: detailFor(code, ghost, fired.has(code)),
  }));
}

/** ghostUnobserved names the criteria that did not fire, in one line, or '' when they
 *  all did.
 *
 *  It claims an absence of OBSERVATION and never an absence of data, because the
 *  payload cannot tell those apart. `evergreen_posting` is derived from a reality class
 *  computed for every job, and `ats_absent` not firing can mean the role IS on the
 *  employer's board — both are criteria checked and found clear, and calling them "no
 *  data" would be simply false. The gauge takes the same care with its unfilled
 *  segments; a line of prose beside it must not give away what the colour withholds. */
export function ghostUnobserved(ghost: Ghost): string {
  const missing = ghostChecklist(ghost).filter((r) => !r.fired);
  if (!missing.length) return '';
  return `Not observed: ${missing.map((r) => r.short).join(', ')}.`;
}

// A fired criterion's fact rides on the criterion's own line, so it is phrased as a
// continuation — lower case, no leading capital. A criterion whose firing IS the whole
// fact gets none: the tick beside it already said "yes", and a second line reading
// "Yes" was type carrying nothing. An unfired criterion gets none either — the row is
// never rendered, and ghostUnobserved names it instead.
function detailFor(code: string, ghost: Ghost, fired: boolean): string {
  if (!fired) return '';
  switch (code) {
    case 'ats_absent': {
      const ago = ghost.ats_checked_at ? timeAgo(ghost.ats_checked_at) : '';
      return ago ? `checked ${ago}` : 'checked against the company board';
    }
    case 'silent_applications':
    case 'user_reports':
      // The contributor count is served only above the anonymity gate, and the UI
      // must not invent one below it: a count of one identifies that applicant to
      // the employer. Absent means absent.
      return ghost.contributors ? `from ${ghost.contributors} people` : 'reported';
    default:
      return '';
  }
}
