// Real brand marks for skill chips and "See also" cards backed by a `skills` facet
// — the technology/cloud/framework side of FILTER_COLLECTIONS (see collections.ts).
// Mirrors backers.ts: a flat, hand-maintained map from our skill dictionary slug to
// a verified source, not an auto-derived guess. Source here is the `simple-icons`
// package (official brand SVG path + brand hex per icon), imported by name so
// unused icons are tree-shaken.
//
// The bulk of the entries below (everything past the original curated ~40) were
// added by intersecting our full skill dictionary (SKILL_LABELS) against every
// simple-icons `slug` for an exact match, then verifying each candidate's `source`
// URL actually points at the tool/language/company our label means — an exact slug
// match is not proof of the same identity. Three exact matches failed that check
// and are deliberately absent despite existing in simple-icons: `elk` (resolves to
// the Elk Mastodon client, not the Elastic ELK stack), `hive` (resolves to the Hive
// smart-thermostat brand, not Apache Hive), and `backbone` (resolves to a
// backbone.com press kit, not Backbone.js). A slug added later should get the same
// source check before being trusted.
//
// Coverage is still intentionally partial: `simple-icons` does not carry AWS,
// Azure, Java, or C# (removed following trademark takedown requests from their
// owners), so those four `skills` slugs have no entry here and render the generic
// tech family icon (in a "See also" card) or nothing (in a skill chip) — the same
// graceful fallback any future skill gets before someone adds it below.
import {
  siActix,
  siAirbyte,
  siAirtable,
  siAndroid,
  siAngular,
  siAnsible,
  siAnsys,
  siAnthropic,
  siApachekafka,
  siAppium,
  siArcgis,
  siAstro,
  siAutocad,
  siBentoml,
  siBitbucket,
  siBlender,
  siC,
  siCircleci,
  siCisco,
  siClickhouse,
  siClojure,
  siCmake,
  siConfluence,
  siContainerd,
  siContentful,
  siCplusplus,
  siCrewai,
  siCss,
  siCucumber,
  siCypress,
  siDart,
  siDask,
  siDatabricks,
  siDatadog,
  siDjango,
  siDocker,
  siDotnet,
  siDynatrace,
  siElasticsearch,
  siElixir,
  siErlang,
  siEthereum,
  siExpress,
  siFastapi,
  siFastify,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siFortran,
  siFsharp,
  siGatling,
  siGin,
  siGit,
  siGithub,
  siGitlab,
  siGo,
  siGooglecloud,
  siGradle,
  siGrafana,
  siGraphql,
  siHaskell,
  siHelm,
  siHootsuite,
  siHubspot,
  siHuggingface,
  siInfluxdb,
  siIonic,
  siIos,
  siIstio,
  siJavascript,
  siJenkins,
  siJest,
  siJira,
  siJquery,
  siJson,
  siJulia,
  siJupyter,
  siK6,
  siKeras,
  siKeycloak,
  siKibana,
  siKicad,
  siKoa,
  siKotlin,
  siKtor,
  siKubernetes,
  siLabview,
  siLangchain,
  siLanggraph,
  siLaravel,
  siLinux,
  siLogstash,
  siLooker,
  siLua,
  siMacos,
  siMailchimp,
  siMariadb,
  siMetabase,
  siMetasploit,
  siMilvus,
  siMiro,
  siMixpanel,
  siMlflow,
  siMobx,
  siMocha,
  siMongodb,
  siMqtt,
  siMysql,
  siN8n,
  siNeo4j,
  siNestjs,
  siNewrelic,
  siNextdotjs,
  siNginx,
  siNim,
  siNodedotjs,
  siNumpy,
  siNuxt,
  siOcaml,
  siOkta,
  siOllama,
  siOnnx,
  siOpencv,
  siOpenid,
  siOpensearch,
  siOpenstack,
  siOpentelemetry,
  siOwasp,
  siPagerduty,
  siPandas,
  siPerl,
  siPhp,
  siPlotly,
  siPodman,
  siPostgresql,
  siPostman,
  siPreact,
  siPresto,
  siPrometheus,
  siPulumi,
  siPuppeteer,
  siPytest,
  siPython,
  siPytorch,
  siQdrant,
  siQgis,
  siQlik,
  siQuarkus,
  siQuickbooks,
  siR,
  siRabbitmq,
  siRancher,
  siReact,
  siRedis,
  siRedux,
  siRemix,
  siRuby,
  siRubyonrails,
  siRust,
  siSap,
  siSass,
  siScala,
  siScipy,
  siScylladb,
  siSelenium,
  siSemrush,
  siSentry,
  siServerless,
  siShopify,
  siSketch,
  siSketchup,
  siSnowflake,
  siSolana,
  siSolidity,
  siSpacy,
  siSplunk,
  siSpring,
  siSqlite,
  siStorybook,
  siSvelte,
  siSwagger,
  siSwift,
  siSymfony,
  siTensorflow,
  siTerraform,
  siTrino,
  siTypescript,
  siUbuntu,
  siUipath,
  siUml,
  siVault,
  siVite,
  siVitest,
  siVllm,
  siVmware,
  siVuedotjs,
  siWebflow,
  siWebgl,
  siWebpack,
  siWireshark,
  siWordpress,
  siXero,
  siXml,
  siYaml,
  siYolo,
  siZapier,
  siZendesk,
  siZig,
} from 'simple-icons';

export type TechMark = {
  title: string;
  path: string;
  hex: string;
};

export const TECH_MARKS: Record<string, TechMark> = {
  python: siPython,
  javascript: siJavascript,
  typescript: siTypescript,
  cpp: siCplusplus,
  go: siGo,
  rust: siRust,
  ruby: siRuby,
  php: siPhp,
  kotlin: siKotlin,
  swift: siSwift,
  scala: siScala,
  nodejs: siNodedotjs,
  clojure: siClojure,
  elixir: siElixir,
  react: siReact,
  angular: siAngular,
  vue: siVuedotjs,
  nextjs: siNextdotjs,
  spring: siSpring,
  rails: siRubyonrails,
  django: siDjango,
  svelte: siSvelte,
  kubernetes: siKubernetes,
  terraform: siTerraform,
  docker: siDocker,
  postgresql: siPostgresql,
  redis: siRedis,
  kafka: siApachekafka,
  graphql: siGraphql,
  mongodb: siMongodb,
  mysql: siMysql,
  elasticsearch: siElasticsearch,
  dotnet: siDotnet,
  laravel: siLaravel,
  flutter: siFlutter,
  gcp: siGooglecloud,
  jenkins: siJenkins,
  ansible: siAnsible,
  pytorch: siPytorch,
  tensorflow: siTensorflow,
  solidity: siSolidity,

  // Everything below was added by the exact-slug-match + source-verification pass
  // described above (alphabetical by slug, not by topic — there are too many for a
  // hand-curated grouping to stay meaningful).
  actix: siActix,
  airbyte: siAirbyte,
  airtable: siAirtable,
  android: siAndroid,
  ansys: siAnsys,
  anthropic: siAnthropic,
  appium: siAppium,
  arcgis: siArcgis,
  astro: siAstro,
  autocad: siAutocad,
  bentoml: siBentoml,
  bitbucket: siBitbucket,
  blender: siBlender,
  c: siC,
  circleci: siCircleci,
  cisco: siCisco,
  clickhouse: siClickhouse,
  cmake: siCmake,
  confluence: siConfluence,
  containerd: siContainerd,
  contentful: siContentful,
  crewai: siCrewai,
  css: siCss,
  cucumber: siCucumber,
  cypress: siCypress,
  dart: siDart,
  dask: siDask,
  databricks: siDatabricks,
  datadog: siDatadog,
  dynatrace: siDynatrace,
  erlang: siErlang,
  ethereum: siEthereum,
  express: siExpress,
  fastapi: siFastapi,
  fastify: siFastify,
  figma: siFigma,
  firebase: siFirebase,
  flask: siFlask,
  fortran: siFortran,
  fsharp: siFsharp,
  gatling: siGatling,
  gin: siGin,
  git: siGit,
  github: siGithub,
  gitlab: siGitlab,
  gradle: siGradle,
  grafana: siGrafana,
  haskell: siHaskell,
  helm: siHelm,
  hootsuite: siHootsuite,
  hubspot: siHubspot,
  huggingface: siHuggingface,
  influxdb: siInfluxdb,
  ionic: siIonic,
  ios: siIos,
  istio: siIstio,
  jest: siJest,
  jira: siJira,
  jquery: siJquery,
  json: siJson,
  julia: siJulia,
  jupyter: siJupyter,
  k6: siK6,
  keras: siKeras,
  keycloak: siKeycloak,
  kibana: siKibana,
  kicad: siKicad,
  koa: siKoa,
  ktor: siKtor,
  labview: siLabview,
  langchain: siLangchain,
  langgraph: siLanggraph,
  linux: siLinux,
  logstash: siLogstash,
  looker: siLooker,
  lua: siLua,
  macos: siMacos,
  mailchimp: siMailchimp,
  mariadb: siMariadb,
  metabase: siMetabase,
  metasploit: siMetasploit,
  milvus: siMilvus,
  miro: siMiro,
  mixpanel: siMixpanel,
  mlflow: siMlflow,
  mobx: siMobx,
  mocha: siMocha,
  mqtt: siMqtt,
  n8n: siN8n,
  neo4j: siNeo4j,
  nestjs: siNestjs,
  newrelic: siNewrelic,
  nginx: siNginx,
  nim: siNim,
  numpy: siNumpy,
  nuxt: siNuxt,
  ocaml: siOcaml,
  okta: siOkta,
  ollama: siOllama,
  onnx: siOnnx,
  opencv: siOpencv,
  openid: siOpenid,
  opensearch: siOpensearch,
  openstack: siOpenstack,
  opentelemetry: siOpentelemetry,
  owasp: siOwasp,
  pagerduty: siPagerduty,
  pandas: siPandas,
  perl: siPerl,
  plotly: siPlotly,
  podman: siPodman,
  postman: siPostman,
  preact: siPreact,
  presto: siPresto,
  prometheus: siPrometheus,
  pulumi: siPulumi,
  puppeteer: siPuppeteer,
  pytest: siPytest,
  qdrant: siQdrant,
  qgis: siQgis,
  qlik: siQlik,
  quarkus: siQuarkus,
  quickbooks: siQuickbooks,
  r: siR,
  rabbitmq: siRabbitmq,
  rancher: siRancher,
  redux: siRedux,
  remix: siRemix,
  sap: siSap,
  sass: siSass,
  scipy: siScipy,
  scylladb: siScylladb,
  selenium: siSelenium,
  semrush: siSemrush,
  sentry: siSentry,
  serverless: siServerless,
  shopify: siShopify,
  sketch: siSketch,
  sketchup: siSketchup,
  snowflake: siSnowflake,
  solana: siSolana,
  spacy: siSpacy,
  splunk: siSplunk,
  sqlite: siSqlite,
  storybook: siStorybook,
  swagger: siSwagger,
  symfony: siSymfony,
  trino: siTrino,
  ubuntu: siUbuntu,
  uipath: siUipath,
  uml: siUml,
  vault: siVault,
  vite: siVite,
  vitest: siVitest,
  vllm: siVllm,
  vmware: siVmware,
  webflow: siWebflow,
  webgl: siWebgl,
  webpack: siWebpack,
  wireshark: siWireshark,
  wordpress: siWordpress,
  xero: siXero,
  xml: siXml,
  yaml: siYaml,
  yolo: siYolo,
  zapier: siZapier,
  zendesk: siZendesk,
  zig: siZig,
};
