-- Retires users.talent_network_public_id, the opaque uuid that addressed the old
-- one-candidate profile page. That route is gone: a member's card is now served at
-- /talent/<handle> (migrations 0147/0148). Two public identifiers for one page is a
-- drift waiting to happen — one of them eventually gets handed out where the other
-- was meant to be — and nothing ever shared the uuid, because the control that
-- minted it was never reachable from the account navigation.
--
-- *** THIS FILE IS APPLIED AFTER THE DEPLOY, NOT BEFORE IT. ***
--
-- Every other migration in this repository runs BEFORE the code that reads it. This
-- one inverts that, and the inversion is the whole reason for this paragraph. The
-- running server still SELECTs this column until the release that stops doing so is
-- live; dropping it first turns every authenticated read of the Talent Network
-- setting into an error, immediately, for as long as the deploy takes.
--
-- So: deploy the app, confirm it is serving, THEN apply this file. If it is applied
-- early by the ordinary migrate run, roll the app forward rather than reverting the
-- migration — the column is empty of meaning by then and nothing can be recovered
-- from putting it back.
--
-- DROP COLUMN is metadata-only on PG11+ (the row data is not rewritten; the column
-- is marked dropped), so it holds ACCESS EXCLUSIVE only for the instant it takes to
-- write the catalogue entry. The unique index built by 0086 — and repaired by
-- 0117/0118 — is dropped with the column it indexes; naming it separately would be
-- a second statement that can only fail.
--
-- IF EXISTS so a re-run after a partial apply is clean, and because the column is
-- absent on any volume created after this file.

ALTER TABLE public.users
    -- squawk-ignore ban-drop-column -- deliberate, and the "existing clients" it warns about are exactly what the apply-after-deploy paragraph above is for: nothing outside this repository ever saw this column, and the one route that read it is deleted in the same change.
    DROP COLUMN IF EXISTS talent_network_public_id;
