-- Dynamically registered OAuth clients (RFC 7591). Public clients only: no secret
-- is ever stored because none is issued — token_endpoint_auth_method is always
-- "none" and PKCE carries the proof instead.
CREATE TABLE oauth_clients (
    client_id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    redirect_uris TEXT[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Single-use authorization codes. Hashed at rest like api_keys.token_hash; the
-- plaintext code is shown to the client exactly once, in the authorize redirect.
CREATE TABLE oauth_authorization_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    redirect_uri TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX oauth_authorization_codes_user_id_idx ON oauth_authorization_codes (user_id);

-- Long-lived grants: one row per approved "connected device". issued_token_version
-- is the user's users.token_version at the moment of consent — AuthenticateOAuthGrant
-- requires it still to match, so LogoutAll and password reset/change (which already
-- bump that counter) revoke every MCP grant with no extra code.
CREATE TABLE oauth_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_id TEXT NOT NULL REFERENCES oauth_clients (client_id) ON DELETE CASCADE,
    access_token_hash TEXT NOT NULL UNIQUE,
    -- squawk-ignore prefer-bigint-over-int -- mirrors users.token_version (int, 0041_account_security.sql), which this column is compared against
    issued_token_version INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ
);

CREATE INDEX oauth_grants_user_id_idx ON oauth_grants (user_id);
