// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adzuna_description.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAdzunaDescriptionBatch = `-- name: ClaimAdzunaDescriptionBatch :many
WITH claimable AS (
    SELECT o.id, o.job_id
    FROM adzuna_description_outbox o
    JOIN jobs j ON j.id = o.job_id
    WHERE o.failed_at IS NULL
      AND (o.claimed_at IS NULL
           OR o.claimed_at < now() - make_interval(secs => $1::int))
    ORDER BY COALESCE(j.posted_at, j.created_at) DESC, j.id DESC
    FOR UPDATE OF o SKIP LOCKED
    LIMIT $2
)
UPDATE adzuna_description_outbox o
SET claimed_at = now()
FROM claimable c
JOIN jobs j ON j.id = c.job_id
WHERE o.id = c.id
RETURNING o.id, o.job_id, j.external_id, j.url, j.description
`

type ClaimAdzunaDescriptionBatchParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimAdzunaDescriptionBatchRow struct {
	ID          int64  `json:"id"`
	JobID       int64  `json:"job_id"`
	ExternalID  string `json:"external_id"`
	URL         string `json:"url"`
	Description string `json:"description"`
}

// Claim a batch of live, unleased captures, freshest posting first, by stamping
// claimed_at. Mirrors ClaimApplyFormBatch: FOR UPDATE OF o locks only outbox rows, SKIP
// LOCKED lets concurrent workers take disjoint rows, and the lease predicate reclaims
// entries whose worker died, so no separate reaper process is needed.
//
// The claim returns the job's external_id and url because the fetcher needs the posting
// id and the exact stored URL to hit the same page the ingest write recorded.
func (q *Queries) ClaimAdzunaDescriptionBatch(ctx context.Context, arg ClaimAdzunaDescriptionBatchParams) ([]ClaimAdzunaDescriptionBatchRow, error) {
	rows, err := q.db.Query(ctx, claimAdzunaDescriptionBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimAdzunaDescriptionBatchRow{}
	for rows.Next() {
		var i ClaimAdzunaDescriptionBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ExternalID,
			&i.URL,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAdzunaDescriptionEntry = `-- name: DeleteAdzunaDescriptionEntry :exec
DELETE FROM adzuna_description_outbox
WHERE id = $1
`

// Retire a capture that succeeded (or that will never succeed, e.g. the posting is gone).
func (q *Queries) DeleteAdzunaDescriptionEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAdzunaDescriptionEntry, id)
	return err
}

const enqueueAdzunaDescriptionCapture = `-- name: EnqueueAdzunaDescriptionCapture :execrows
INSERT INTO adzuna_description_outbox (job_id)
SELECT j.id
FROM jobs j
WHERE j.id = $1::bigint
  AND NOT EXISTS (SELECT 1 FROM adzuna_description_hydrated h WHERE h.job_id = j.id)
ON CONFLICT (job_id) DO NOTHING
`

// Transactional-outbox enqueue for the ingest write path: queue this one job for a full-
// description fetch, gated on it not having been hydrated already.
//
// The gate is a dedicated marker table (adzuna_description_hydrated) rather than a content
// check on jobs.description, because once the queue entry is deleted after a successful
// capture nothing else distinguishes "already hydrated" from "still carrying the API
// snippet" — the row's own content_hash and updated_at move for unrelated reasons too.
//
// Idempotent via the outbox's UNIQUE (job_id). Run in the same transaction as the job's
// UpsertJob so a newly ingested job is queued atomically with its write. The caller is
// responsible for only calling this for a job whose stored URL is Adzuna's own hosted
// details page — the ad-network tracking redirect answers Access Denied and is never
// queued (see adzunadesc.Eligible).
func (q *Queries) EnqueueAdzunaDescriptionCapture(ctx context.Context, jobID int64) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueAdzunaDescriptionCapture, jobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAdzunaDescriptionHydrated = `-- name: MarkAdzunaDescriptionHydrated :exec
INSERT INTO adzuna_description_hydrated (job_id)
VALUES ($1)
ON CONFLICT (job_id) DO UPDATE SET hydrated_at = now()
`

// Record that this job's description is now the full text, closing the enqueue gate for
// good. A re-hydration is a deliberate act (drop the row, which reopens the gate), not
// something a crawl does by accident — mirrors apply_forms' own refresh story.
func (q *Queries) MarkAdzunaDescriptionHydrated(ctx context.Context, jobID int64) error {
	_, err := q.db.Exec(ctx, markAdzunaDescriptionHydrated, jobID)
	return err
}

const recordAdzunaDescriptionFailure = `-- name: RecordAdzunaDescriptionFailure :one
UPDATE adzuna_description_outbox
SET attempts   = attempts + 1,
    last_error = $1,
    failed_at  = CASE
                     WHEN attempts + 1 >= $2::int THEN now()
                     ELSE NULL
                 END
WHERE id = $3
RETURNING attempts, failed_at
`

type RecordAdzunaDescriptionFailureParams struct {
	LastError   string `json:"last_error"`
	MaxAttempts int32  `json:"max_attempts"`
	ID          int64  `json:"id"`
}

type RecordAdzunaDescriptionFailureRow struct {
	Attempts int32              `json:"attempts"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

// Count a failed capture: bump attempts, record the error, and dead-letter (set
// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally left in
// place — its expiry gates the retry to a later run. Mirrors RecordApplyFormFailure.
func (q *Queries) RecordAdzunaDescriptionFailure(ctx context.Context, arg RecordAdzunaDescriptionFailureParams) (RecordAdzunaDescriptionFailureRow, error) {
	row := q.db.QueryRow(ctx, recordAdzunaDescriptionFailure, arg.LastError, arg.MaxAttempts, arg.ID)
	var i RecordAdzunaDescriptionFailureRow
	err := row.Scan(&i.Attempts, &i.FailedAt)
	return i, err
}
