// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAssistantMessage = `-- name: AppendAssistantMessage :one
INSERT INTO assistant_messages (session_id, seq, role, content)
VALUES (
    $1,
    (SELECT coalesce(max(seq), 0) + 1 FROM assistant_messages WHERE session_id = $1),
    $2,
    $3
)
RETURNING session_id, seq, role, content, created_at
`

type AppendAssistantMessageParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Role      string          `json:"role"`
	Content   json.RawMessage `json:"content"`
}

// Append one message to a session's transcript, assigning the next sequence number in the
// same statement so concurrent writers cannot collide on (session_id, seq) — the primary
// key rejects a duplicate rather than silently reordering the conversation.
func (q *Queries) AppendAssistantMessage(ctx context.Context, arg AppendAssistantMessageParams) (AssistantMessage, error) {
	row := q.db.QueryRow(ctx, appendAssistantMessage, arg.SessionID, arg.Role, arg.Content)
	var i AssistantMessage
	err := row.Scan(
		&i.SessionID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createAssistantSession = `-- name: CreateAssistantSession :one
INSERT INTO assistant_sessions (user_id, preset, cv_id, job_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, preset, label, cv_id, job_id, created_at, updated_at
`

type CreateAssistantSessionParams struct {
	UserID int64      `json:"user_id"`
	Preset string     `json:"preset"`
	CvID   *uuid.UUID `json:"cv_id"`
	JobID  *int64     `json:"job_id"`
}

type CreateAssistantSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Start a conversation for a user. preset selects the prompt and tool set ('chat' or
// 'tailor'); cv_id/job_id bind a tailoring session to its CV and vacancy and are NULL
// for a chat. The label is set later, from the first user message.
func (q *Queries) CreateAssistantSession(ctx context.Context, arg CreateAssistantSessionParams) (CreateAssistantSessionRow, error) {
	row := q.db.QueryRow(ctx, createAssistantSession,
		arg.UserID,
		arg.Preset,
		arg.CvID,
		arg.JobID,
	)
	var i CreateAssistantSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preset,
		&i.Label,
		&i.CvID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssistantSession = `-- name: DeleteAssistantSession :execrows
DELETE FROM assistant_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteAssistantSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

// Remove an owned session; its transcript goes with it (ON DELETE CASCADE). Returns 0
// affected rows for a foreign or missing id.
func (q *Queries) DeleteAssistantSession(ctx context.Context, arg DeleteAssistantSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssistantSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssistantSession = `-- name: GetAssistantSession :one
SELECT id, user_id, preset, label, cv_id, job_id, created_at, updated_at
FROM assistant_sessions
WHERE id = $1 AND user_id = $2
`

type GetAssistantSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

type GetAssistantSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One session owned by the caller. Owner-scoped: a foreign or missing id returns no row,
// which the handler maps to 404 — so a probe cannot tell the two apart.
func (q *Queries) GetAssistantSession(ctx context.Context, arg GetAssistantSessionParams) (GetAssistantSessionRow, error) {
	row := q.db.QueryRow(ctx, getAssistantSession, arg.ID, arg.UserID)
	var i GetAssistantSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preset,
		&i.Label,
		&i.CvID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssistantChatSessions = `-- name: ListAssistantChatSessions :many
SELECT id, user_id, preset, label, cv_id, job_id, created_at, updated_at
FROM assistant_sessions
WHERE user_id = $1 AND preset IN ('chat', 'profile', 'browse', 'interview', 'debrief')
ORDER BY updated_at DESC, id DESC
`

type ListAssistantChatSessionsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// The caller's session rail: their unbound conversations, most recently active first.
// Owner-scoped by construction — another user's sessions can never appear.
//
// The rail carries every conversation that can be continued on its own: chat, profile,
// browse, interview and debrief alike. An experience interview is resumable and would
// otherwise be lost the moment its author navigated away; a browsing conversation begun in
// the extension's side panel is one the candidate can pick up at their desk, where it
// simply cannot see a page any more; a rehearsal is opened days before the interview and
// closed again, and a debrief is written in one sitting and reread before the next round.
//
// A rehearsal and a debrief are bound to a vacancy, so the test is not "binds to nothing"
// — it is whether the conversation still works when reopened from here. It does: their
// context tool closes over the vacancy id the session already carries. Tailoring
// conversations are excluded for exactly that reason inverted — they belong to the CV that
// owns them, are reached through the tailoring workspace, and cannot be continued without it.
func (q *Queries) ListAssistantChatSessions(ctx context.Context, userID int64) ([]ListAssistantChatSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAssistantChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantChatSessionsRow{}
	for rows.Next() {
		var i ListAssistantChatSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Preset,
			&i.Label,
			&i.CvID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessages = `-- name: ListAssistantMessages :many
SELECT session_id, seq, role, content, created_at
FROM assistant_messages
WHERE session_id = $1
ORDER BY seq
`

// A session's whole transcript in order, for the client to replay. Tool calls and tool
// results are included. Unbounded by design: the client's own message list must show
// everything, not a trimmed window — see ListRecentAssistantMessages for the bounded
// read the model's own history is rebuilt from.
func (q *Queries) ListAssistantMessages(ctx context.Context, sessionID uuid.UUID) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listAssistantMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAssistantMessages = `-- name: ListRecentAssistantMessages :many
SELECT session_id, seq, role, content, created_at
FROM assistant_messages
WHERE session_id = $1
ORDER BY seq DESC
LIMIT $2
`

type ListRecentAssistantMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

// The session's most recent messages, newest first — the bounded counterpart of
// ListAssistantMessages, for rebuilding the model's own history every turn. Runner.trim()
// only ever keeps the tail (HistoryLimit, default 60) of what ListAssistantMessages
// returns; fetching and JSON-decoding the WHOLE transcript first, only to discard
// everything but the tail, cost time and memory proportional to total session length
// (autopilot runs, long-lived chat/tailoring sessions can accumulate hundreds of rows)
// instead of the fixed window actually used. The caller reverses these rows back to
// ascending seq order before handing them to trim()/Conversation().
func (q *Queries) ListRecentAssistantMessages(ctx context.Context, arg ListRecentAssistantMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listRecentAssistantMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssistantSessionLabel = `-- name: SetAssistantSessionLabel :exec
UPDATE assistant_sessions
SET label = $3
WHERE id = $1 AND user_id = $2 AND label IS NULL
`

type SetAssistantSessionLabelParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID int64       `json:"user_id"`
	Label  pgtype.Text `json:"label"`
}

// Name a session from its first user message. Applied only while the label is still unset,
// so a long conversation keeps the name it was born with. Owner-scoped for the same
// reason TouchAssistantSession is.
func (q *Queries) SetAssistantSessionLabel(ctx context.Context, arg SetAssistantSessionLabelParams) error {
	_, err := q.db.Exec(ctx, setAssistantSessionLabel, arg.ID, arg.UserID, arg.Label)
	return err
}

const touchAssistantSession = `-- name: TouchAssistantSession :exec
UPDATE assistant_sessions
SET updated_at = now()
WHERE id = $1 AND user_id = $2
`

type TouchAssistantSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

// Mark a session as the most recently active, so the rail's order follows real use.
// Owner-scoped like every other write in this file (Get/Delete both require id AND
// user_id): a bare id would let any caller who learns another user's session id touch
// it, and every call site already has the owner's id in hand (the Session it just
// read, created, or otherwise proved ownership of).
func (q *Queries) TouchAssistantSession(ctx context.Context, arg TouchAssistantSessionParams) error {
	_, err := q.db.Exec(ctx, touchAssistantSession, arg.ID, arg.UserID)
	return err
}
