// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAssistantMessage = `-- name: AppendAssistantMessage :one
INSERT INTO assistant_messages (session_id, seq, role, content)
VALUES (
    $1,
    (SELECT coalesce(max(seq), 0) + 1 FROM assistant_messages WHERE session_id = $1),
    $2,
    $3
)
RETURNING session_id, seq, role, content, created_at
`

type AppendAssistantMessageParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Role      string          `json:"role"`
	Content   json.RawMessage `json:"content"`
}

// Append one message to a session's transcript, assigning the next sequence number in the
// same statement so concurrent writers cannot collide on (session_id, seq) — the primary
// key rejects a duplicate rather than silently reordering the conversation.
func (q *Queries) AppendAssistantMessage(ctx context.Context, arg AppendAssistantMessageParams) (AssistantMessage, error) {
	row := q.db.QueryRow(ctx, appendAssistantMessage, arg.SessionID, arg.Role, arg.Content)
	var i AssistantMessage
	err := row.Scan(
		&i.SessionID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createAssistantSession = `-- name: CreateAssistantSession :one
INSERT INTO assistant_sessions (user_id, preset, cv_id, job_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, preset, label, cv_id, job_id, created_at, updated_at
`

type CreateAssistantSessionParams struct {
	UserID int64      `json:"user_id"`
	Preset string     `json:"preset"`
	CvID   *uuid.UUID `json:"cv_id"`
	JobID  *int64     `json:"job_id"`
}

type CreateAssistantSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Start a conversation for a user. preset selects the prompt and tool set ('chat' or
// 'tailor'); cv_id/job_id bind a tailoring session to its CV and vacancy and are NULL
// for a chat. The label is set later, from the first user message.
func (q *Queries) CreateAssistantSession(ctx context.Context, arg CreateAssistantSessionParams) (CreateAssistantSessionRow, error) {
	row := q.db.QueryRow(ctx, createAssistantSession,
		arg.UserID,
		arg.Preset,
		arg.CvID,
		arg.JobID,
	)
	var i CreateAssistantSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preset,
		&i.Label,
		&i.CvID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssistantSession = `-- name: DeleteAssistantSession :execrows
DELETE FROM assistant_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteAssistantSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

// Remove an owned session; its transcript goes with it (ON DELETE CASCADE). Returns 0
// affected rows for a foreign or missing id.
func (q *Queries) DeleteAssistantSession(ctx context.Context, arg DeleteAssistantSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssistantSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssistantSession = `-- name: GetAssistantSession :one
SELECT id, user_id, preset, label, cv_id, job_id, created_at, updated_at
FROM assistant_sessions
WHERE id = $1 AND user_id = $2
`

type GetAssistantSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

type GetAssistantSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One session owned by the caller. Owner-scoped: a foreign or missing id returns no row,
// which the handler maps to 404 — so a probe cannot tell the two apart.
func (q *Queries) GetAssistantSession(ctx context.Context, arg GetAssistantSessionParams) (GetAssistantSessionRow, error) {
	row := q.db.QueryRow(ctx, getAssistantSession, arg.ID, arg.UserID)
	var i GetAssistantSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preset,
		&i.Label,
		&i.CvID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssistantChatSessions = `-- name: ListAssistantChatSessions :many
SELECT id, user_id, preset, label, cv_id, job_id, created_at, updated_at
FROM assistant_sessions
WHERE user_id = $1 AND preset IN ('chat', 'profile', 'browse')
ORDER BY updated_at DESC, id DESC
`

type ListAssistantChatSessionsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    int64              `json:"user_id"`
	Preset    string             `json:"preset"`
	Label     pgtype.Text        `json:"label"`
	CvID      *uuid.UUID         `json:"cv_id"`
	JobID     *int64             `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// The caller's session rail: their unbound conversations, most recently active first.
// Owner-scoped by construction — another user's sessions can never appear.
//
// The rail carries every preset that binds to NOTHING: chat, profile and browse alike. An
// experience interview is resumable and would otherwise be lost the moment its author
// navigated away; a browsing conversation begun in the extension's side panel is one the
// candidate can pick up at their desk, where it simply cannot see a page any more.
// Tailoring conversations are deliberately excluded for the opposite reason — they belong
// to the CV that owns them and are reached through the tailoring workspace, so listing one
// here would put a conversation in the rail that leads nowhere useful and cannot be
// continued without its CV.
func (q *Queries) ListAssistantChatSessions(ctx context.Context, userID int64) ([]ListAssistantChatSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAssistantChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantChatSessionsRow{}
	for rows.Next() {
		var i ListAssistantChatSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Preset,
			&i.Label,
			&i.CvID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessages = `-- name: ListAssistantMessages :many
SELECT session_id, seq, role, content, created_at
FROM assistant_messages
WHERE session_id = $1
ORDER BY seq
`

// A session's whole transcript in order. It is both what the client replays and what the
// model's history is rebuilt from, so tool calls and tool results are included.
func (q *Queries) ListAssistantMessages(ctx context.Context, sessionID uuid.UUID) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listAssistantMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssistantSessionLabel = `-- name: SetAssistantSessionLabel :exec
UPDATE assistant_sessions
SET label = $2
WHERE id = $1 AND label IS NULL
`

type SetAssistantSessionLabelParams struct {
	ID    uuid.UUID   `json:"id"`
	Label pgtype.Text `json:"label"`
}

// Name a session from its first user message. Applied only while the label is still unset,
// so a long conversation keeps the name it was born with.
func (q *Queries) SetAssistantSessionLabel(ctx context.Context, arg SetAssistantSessionLabelParams) error {
	_, err := q.db.Exec(ctx, setAssistantSessionLabel, arg.ID, arg.Label)
	return err
}

const touchAssistantSession = `-- name: TouchAssistantSession :exec
UPDATE assistant_sessions
SET updated_at = now()
WHERE id = $1
`

// Mark a session as the most recently active, so the rail's order follows real use.
func (q *Queries) TouchAssistantSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAssistantSession, id)
	return err
}
