// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const applyDailyView = `-- name: ApplyDailyView :batchexec
WITH ins AS (
    INSERT INTO job_daily_views (day, job_id, uniques)
    VALUES ($3, $2, $1)
    ON CONFLICT (day, job_id)
        DO UPDATE SET uniques = job_daily_views.uniques + EXCLUDED.uniques
)
UPDATE jobs SET view_count = view_count + $1
WHERE id = $2
`

type ApplyDailyViewBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ApplyDailyViewParams struct {
	Delta int32       `json:"delta"`
	JobID int64       `json:"job_id"`
	Day   pgtype.Date `json:"day"`
}

// Apply one (day, job) unique count additively: upsert the daily rollup and add the
// same delta to jobs.view_count, in one statement. The data-modifying CTE runs even
// though the primary query does not read it. Issued as a pgx batch (one call per
// tuple) so a file's rows land in a single round trip; view_count accumulates across
// a job's day-rows, and additivity lets a day spanning two rotated files sum right.
func (q *Queries) ApplyDailyView(ctx context.Context, arg []ApplyDailyViewParams) *ApplyDailyViewBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Delta,
			a.JobID,
			a.Day,
		}
		batch.Queue(applyDailyView, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ApplyDailyViewBatchResults{br, len(arg), false}
}

func (b *ApplyDailyViewBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ApplyDailyViewBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
