// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearProviderCooldowns = `-- name: ClearProviderCooldowns :execrows
UPDATE board_health
SET cooldown_until = NULL, consecutive_failures = 0
WHERE provider = $1 AND cooldown_until IS NOT NULL AND cooldown_until > now()
`

// Clear the active cooldown and failure count for every currently-cooled board of a
// provider — applied once a recovery probe proves the provider reachable again, so the
// run crawls them this cycle instead of each waiting out its own backoff (up to a day)
// after a resolved provider-wide outage. Returns the number of boards cleared.
func (q *Queries) ClearProviderCooldowns(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, clearProviderCooldowns, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoardCooldown = `-- name: GetBoardCooldown :one
SELECT cooldown_until
FROM board_health
WHERE provider = $1 AND board = $2 AND region = $3
`

type GetBoardCooldownParams struct {
	Provider string `json:"provider"`
	Board    string `json:"board"`
	Region   string `json:"region"`
}

// The board's current cooldown_until (NULL = eligible). Absent row → pgx.ErrNoRows,
// which the caller treats as "never seen, eligible". region disambiguates a board id that
// repeats across independent regional slices (e.g. Adzuna's "it-jobs" once per country); every
// other provider passes ” here, matching the column's default.
func (q *Queries) GetBoardCooldown(ctx context.Context, arg GetBoardCooldownParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getBoardCooldown, arg.Provider, arg.Board, arg.Region)
	var cooldown_until pgtype.Timestamptz
	err := row.Scan(&cooldown_until)
	return cooldown_until, err
}

const listCooledBoards = `-- name: ListCooledBoards :many
SELECT board, region
FROM board_health
WHERE provider = $1 AND cooldown_until IS NOT NULL AND cooldown_until > now()
ORDER BY cooldown_until, board, region
LIMIT $2
`

type ListCooledBoardsParams struct {
	Provider string `json:"provider"`
	Limit    int32  `json:"limit"`
}

type ListCooledBoardsRow struct {
	Board  string `json:"board"`
	Region string `json:"region"`
}

// Up to $2 (board, region) pairs currently in an active cooldown for a provider,
// soonest-to-expire first — the recovery probe's candidates. The ordering rotates the sample as
// cooldowns lapse, so a run does not keep probing the same few boards.
func (q *Queries) ListCooledBoards(ctx context.Context, arg ListCooledBoardsParams) ([]ListCooledBoardsRow, error) {
	rows, err := q.db.Query(ctx, listCooledBoards, arg.Provider, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCooledBoardsRow{}
	for rows.Next() {
		var i ListCooledBoardsRow
		if err := rows.Scan(&i.Board, &i.Region); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnhealthyBoards = `-- name: ListUnhealthyBoards :many
SELECT provider, board, region, consecutive_failures, cooldown_until, last_error, last_error_at,
       count(*) OVER () AS total
FROM board_health
WHERE consecutive_failures > 0 OR (cooldown_until IS NOT NULL AND cooldown_until > now())
ORDER BY consecutive_failures DESC, provider, board, region
LIMIT $1
`

type ListUnhealthyBoardsRow struct {
	Provider            string             `json:"provider"`
	Board               string             `json:"board"`
	Region              string             `json:"region"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldown_until"`
	LastError           pgtype.Text        `json:"last_error"`
	LastErrorAt         pgtype.Timestamptz `json:"last_error_at"`
	Total               int64              `json:"total"`
}

// The worst $1 boards currently failing or cooled down, worst first — the source of the
// per-run summary log. Every row also carries the FULL unhealthy count: count(*) OVER () is
// evaluated over the whole filtered set, before the LIMIT, so the caller reports how many
// boards are broken without a second round trip and without naming them all. Ask this table
// directly for the rest.
func (q *Queries) ListUnhealthyBoards(ctx context.Context, maxBoards int32) ([]ListUnhealthyBoardsRow, error) {
	rows, err := q.db.Query(ctx, listUnhealthyBoards, maxBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnhealthyBoardsRow{}
	for rows.Next() {
		var i ListUnhealthyBoardsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Board,
			&i.Region,
			&i.ConsecutiveFailures,
			&i.CooldownUntil,
			&i.LastError,
			&i.LastErrorAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerHealthRollup = `-- name: ProviderHealthRollup :many
SELECT
    provider,
    count(*)                                                         AS total_boards,
    count(*) FILTER (WHERE cooldown_until IS NULL OR cooldown_until <= now()) AS healthy_boards,
    count(*) FILTER (WHERE cooldown_until IS NOT NULL AND cooldown_until > now()) AS cooled_boards,
    max(last_run_at)::timestamptz                                    AS last_run_at,
    max(last_success_at)::timestamptz                                AS last_success_at,
    coalesce(sum(last_ingested_count) FILTER (WHERE consecutive_failures = 0), 0)::bigint AS ingested_total
FROM board_health
GROUP BY provider
ORDER BY provider
`

type ProviderHealthRollupRow struct {
	Provider      string             `json:"provider"`
	TotalBoards   int64              `json:"total_boards"`
	HealthyBoards int64              `json:"healthy_boards"`
	CooledBoards  int64              `json:"cooled_boards"`
	LastRunAt     pgtype.Timestamptz `json:"last_run_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	IngestedTotal int64              `json:"ingested_total"`
}

// Per-provider health rollup that backs the public /status page: one row per
// provider with board counts and freshness. Read-only — it never touches cooldown
// state. healthy_boards counts boards being served (NOT in an active cooldown), so a
// board that merely erred once but is still crawled every cycle counts as healthy and
// only a board the backoff actually sidelined is unhealthy; healthy_boards + cooled_boards
// always equals total_boards. Aggregate-only: it selects no board identifier and no error
// text, so the public endpoint built on it cannot leak internal detail. ingested_total is
// coalesced/cast to bigint so it reads as a plain int64 (an all-failing provider
// yields 0, not NULL).
func (q *Queries) ProviderHealthRollup(ctx context.Context) ([]ProviderHealthRollupRow, error) {
	rows, err := q.db.Query(ctx, providerHealthRollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderHealthRollupRow{}
	for rows.Next() {
		var i ProviderHealthRollupRow
		if err := rows.Scan(
			&i.Provider,
			&i.TotalBoards,
			&i.HealthyBoards,
			&i.CooledBoards,
			&i.LastRunAt,
			&i.LastSuccessAt,
			&i.IngestedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBoardFailure = `-- name: RecordBoardFailure :one
INSERT INTO board_health (provider, board, region, consecutive_failures, last_error, last_error_at, last_run_at)
VALUES ($1, $2, $3, 1, $4, now(), now())
ON CONFLICT (provider, board, region) DO UPDATE SET
    consecutive_failures = board_health.consecutive_failures + 1,
    last_error           = EXCLUDED.last_error,
    last_error_at        = now(),
    last_run_at          = now()
RETURNING consecutive_failures
`

type RecordBoardFailureParams struct {
	Provider  string      `json:"provider"`
	Board     string      `json:"board"`
	Region    string      `json:"region"`
	LastError pgtype.Text `json:"last_error"`
}

// Count a failed crawl: bump consecutive_failures, record the error, stamp the run,
// and RETURN the new failure count so the caller can compute the cooldown (the backoff
// policy lives in Go, not here). The cooldown itself is applied by SetBoardCooldown.
func (q *Queries) RecordBoardFailure(ctx context.Context, arg RecordBoardFailureParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordBoardFailure,
		arg.Provider,
		arg.Board,
		arg.Region,
		arg.LastError,
	)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const recordBoardSuccess = `-- name: RecordBoardSuccess :exec
INSERT INTO board_health (provider, board, region, consecutive_failures, cooldown_until,
                          last_success_at, last_ingested_count, last_run_at)
VALUES ($1, $2, $3, 0, NULL, now(), $4, now())
ON CONFLICT (provider, board, region) DO UPDATE SET
    consecutive_failures = 0,
    cooldown_until       = NULL,
    last_success_at      = now(),
    last_ingested_count  = EXCLUDED.last_ingested_count,
    last_run_at          = now()
`

type RecordBoardSuccessParams struct {
	Provider          string      `json:"provider"`
	Board             string      `json:"board"`
	Region            string      `json:"region"`
	LastIngestedCount pgtype.Int4 `json:"last_ingested_count"`
}

// A successful crawl clears the failure state and stamps freshness. Upsert so a
// first-ever crawl creates the row.
func (q *Queries) RecordBoardSuccess(ctx context.Context, arg RecordBoardSuccessParams) error {
	_, err := q.db.Exec(ctx, recordBoardSuccess,
		arg.Provider,
		arg.Board,
		arg.Region,
		arg.LastIngestedCount,
	)
	return err
}

const setBoardCooldown = `-- name: SetBoardCooldown :exec
UPDATE board_health
SET cooldown_until = $4
WHERE provider = $1 AND board = $2 AND region = $3
`

type SetBoardCooldownParams struct {
	Provider      string             `json:"provider"`
	Board         string             `json:"board"`
	Region        string             `json:"region"`
	CooldownUntil pgtype.Timestamptz `json:"cooldown_until"`
}

// Apply the Go-computed cooldown window to a board (called only when the backoff
// policy says to cool down).
func (q *Queries) SetBoardCooldown(ctx context.Context, arg SetBoardCooldownParams) error {
	_, err := q.db.Exec(ctx, setBoardCooldown,
		arg.Provider,
		arg.Board,
		arg.Region,
		arg.CooldownUntil,
	)
	return err
}
