// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCommunityThread = `-- name: CloseCommunityThread :exec
UPDATE threads SET status = 'closed' WHERE id = $1
`

// Moderator close: the thread leaves the open listing and rejects new replies.
func (q *Queries) CloseCommunityThread(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, closeCommunityThread, id)
	return err
}

const countOpenThreadsBySubject = `-- name: CountOpenThreadsBySubject :one
SELECT count(*) FROM threads
WHERE subject_type = $1 AND subject_ref = $2 AND status = 'open'
`

type CountOpenThreadsBySubjectParams struct {
	SubjectType string `json:"subject_type"`
	SubjectRef  string `json:"subject_ref"`
}

// Open-thread count for one subject — the "Discussion · N" badge on the detail page.
// Served by the partial index threads_subject_open_created_idx; scoped to a single
// subject so it stays cheap (not the cross-subject count the design rules out).
func (q *Queries) CountOpenThreadsBySubject(ctx context.Context, arg CountOpenThreadsBySubjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenThreadsBySubject, arg.SubjectType, arg.SubjectRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRepliesByUser = `-- name: CountRecentRepliesByUser :one
SELECT count(*) FROM thread_replies WHERE author_user_id = $1 AND created_at > $2
`

type CountRecentRepliesByUserParams struct {
	AuthorUserID pgtype.Int8        `json:"author_user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentRepliesByUser(ctx context.Context, arg CountRecentRepliesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRepliesByUser, arg.AuthorUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentThreadsByUser = `-- name: CountRecentThreadsByUser :one
SELECT count(*) FROM threads WHERE author_user_id = $1 AND created_at > $2
`

type CountRecentThreadsByUserParams struct {
	AuthorUserID int64              `json:"author_user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Rate-limit count: threads a user opened since a cutoff. Served by
// threads_author_created_idx.
func (q *Queries) CountRecentThreadsByUser(ctx context.Context, arg CountRecentThreadsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentThreadsByUser, arg.AuthorUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCommunityPersona = `-- name: GetCommunityPersona :one

SELECT user_id, handle, created_at FROM community_personas WHERE user_id = $1
`

// Community discussion threads (see the add-community-threads change). Read paths
// join community_personas so a row carries the author's handle, never their user_id.
// A user's stable pseudonymous handle, or no row when they have never posted.
func (q *Queries) GetCommunityPersona(ctx context.Context, userID int64) (CommunityPersona, error) {
	row := q.db.QueryRow(ctx, getCommunityPersona, userID)
	var i CommunityPersona
	err := row.Scan(&i.UserID, &i.Handle, &i.CreatedAt)
	return i, err
}

const getCommunityThread = `-- name: GetCommunityThread :one
SELECT t.id, t.subject_type, t.subject_ref, t.anchor_path, t.title, t.body, t.author_user_id, t.reply_count, t.status, t.created_at, p.handle AS author_handle
FROM threads t
JOIN community_personas p ON p.user_id = t.author_user_id
WHERE t.id = $1
`

type GetCommunityThreadRow struct {
	ID           int64              `json:"id"`
	SubjectType  string             `json:"subject_type"`
	SubjectRef   string             `json:"subject_ref"`
	AnchorPath   pgtype.Text        `json:"anchor_path"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	AuthorUserID int64              `json:"author_user_id"`
	ReplyCount   int32              `json:"reply_count"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AuthorHandle string             `json:"author_handle"`
}

// A single thread with its author handle.
func (q *Queries) GetCommunityThread(ctx context.Context, id int64) (GetCommunityThreadRow, error) {
	row := q.db.QueryRow(ctx, getCommunityThread, id)
	var i GetCommunityThreadRow
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectRef,
		&i.AnchorPath,
		&i.Title,
		&i.Body,
		&i.AuthorUserID,
		&i.ReplyCount,
		&i.Status,
		&i.CreatedAt,
		&i.AuthorHandle,
	)
	return i, err
}

const incrementThreadReplyCount = `-- name: IncrementThreadReplyCount :exec
UPDATE threads SET reply_count = reply_count + 1 WHERE id = $1
`

func (q *Queries) IncrementThreadReplyCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementThreadReplyCount, id)
	return err
}

const insertCommunityPersona = `-- name: InsertCommunityPersona :one
INSERT INTO community_personas (user_id, handle)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, handle, created_at
`

type InsertCommunityPersonaParams struct {
	UserID int64  `json:"user_id"`
	Handle string `json:"handle"`
}

// Mint a persona. ON CONFLICT (user_id) DO NOTHING makes a concurrent same-user mint
// return no row (the repository re-reads the winner); a handle-unique violation is a
// different collision the repository maps to a retry.
func (q *Queries) InsertCommunityPersona(ctx context.Context, arg InsertCommunityPersonaParams) (CommunityPersona, error) {
	row := q.db.QueryRow(ctx, insertCommunityPersona, arg.UserID, arg.Handle)
	var i CommunityPersona
	err := row.Scan(&i.UserID, &i.Handle, &i.CreatedAt)
	return i, err
}

const insertThread = `-- name: InsertThread :one
INSERT INTO threads (subject_type, subject_ref, title, body, author_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subject_type, subject_ref, anchor_path, title, body, author_user_id, reply_count, status, created_at
`

type InsertThreadParams struct {
	SubjectType  string `json:"subject_type"`
	SubjectRef   string `json:"subject_ref"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	AuthorUserID int64  `json:"author_user_id"`
}

// Open a thread. The author's handle is filled by the service from the minted
// persona, so no join is needed here.
func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, insertThread,
		arg.SubjectType,
		arg.SubjectRef,
		arg.Title,
		arg.Body,
		arg.AuthorUserID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectRef,
		&i.AnchorPath,
		&i.Title,
		&i.Body,
		&i.AuthorUserID,
		&i.ReplyCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertThreadReply = `-- name: InsertThreadReply :one
INSERT INTO thread_replies (thread_id, parent_reply_id, author_user_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, thread_id, parent_reply_id, author_user_id, is_ai, body, created_at
`

type InsertThreadReplyParams struct {
	ThreadID      int64       `json:"thread_id"`
	ParentReplyID pgtype.Int8 `json:"parent_reply_id"`
	AuthorUserID  pgtype.Int8 `json:"author_user_id"`
	Body          string      `json:"body"`
}

// parent_reply_id is NULL for a top-level reply, or another reply's id to nest under it.
func (q *Queries) InsertThreadReply(ctx context.Context, arg InsertThreadReplyParams) (ThreadReply, error) {
	row := q.db.QueryRow(ctx, insertThreadReply,
		arg.ThreadID,
		arg.ParentReplyID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i ThreadReply
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentReplyID,
		&i.AuthorUserID,
		&i.IsAi,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listOpenThreadsAfter = `-- name: ListOpenThreadsAfter :many
SELECT t.id, t.subject_type, t.subject_ref, t.anchor_path, t.title, t.body, t.author_user_id, t.reply_count, t.status, t.created_at, p.handle AS author_handle
FROM threads t
JOIN community_personas p ON p.user_id = t.author_user_id
WHERE t.subject_type = $1 AND t.subject_ref = $2 AND t.status = 'open'
  AND (t.created_at < $3
       OR (t.created_at = $3 AND t.id < $4))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $5
`

type ListOpenThreadsAfterParams struct {
	SubjectType     string             `json:"subject_type"`
	SubjectRef      string             `json:"subject_ref"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListOpenThreadsAfterRow struct {
	ID           int64              `json:"id"`
	SubjectType  string             `json:"subject_type"`
	SubjectRef   string             `json:"subject_ref"`
	AnchorPath   pgtype.Text        `json:"anchor_path"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	AuthorUserID int64              `json:"author_user_id"`
	ReplyCount   int32              `json:"reply_count"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AuthorHandle string             `json:"author_handle"`
}

// Keyset continuation: rows strictly older than the cursor (created_at, id). No
// OFFSET, so deep pages never scan skipped rows.
func (q *Queries) ListOpenThreadsAfter(ctx context.Context, arg ListOpenThreadsAfterParams) ([]ListOpenThreadsAfterRow, error) {
	rows, err := q.db.Query(ctx, listOpenThreadsAfter,
		arg.SubjectType,
		arg.SubjectRef,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenThreadsAfterRow{}
	for rows.Next() {
		var i ListOpenThreadsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectRef,
			&i.AnchorPath,
			&i.Title,
			&i.Body,
			&i.AuthorUserID,
			&i.ReplyCount,
			&i.Status,
			&i.CreatedAt,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenThreadsFirst = `-- name: ListOpenThreadsFirst :many
SELECT t.id, t.subject_type, t.subject_ref, t.anchor_path, t.title, t.body, t.author_user_id, t.reply_count, t.status, t.created_at, p.handle AS author_handle
FROM threads t
JOIN community_personas p ON p.user_id = t.author_user_id
WHERE t.subject_type = $1 AND t.subject_ref = $2 AND t.status = 'open'
ORDER BY t.created_at DESC, t.id DESC
LIMIT $3
`

type ListOpenThreadsFirstParams struct {
	SubjectType string `json:"subject_type"`
	SubjectRef  string `json:"subject_ref"`
	Limit       int32  `json:"limit"`
}

type ListOpenThreadsFirstRow struct {
	ID           int64              `json:"id"`
	SubjectType  string             `json:"subject_type"`
	SubjectRef   string             `json:"subject_ref"`
	AnchorPath   pgtype.Text        `json:"anchor_path"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	AuthorUserID int64              `json:"author_user_id"`
	ReplyCount   int32              `json:"reply_count"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AuthorHandle string             `json:"author_handle"`
}

// First page of a subject's open threads, newest first. Served by the partial index
// threads_subject_open_created_idx.
func (q *Queries) ListOpenThreadsFirst(ctx context.Context, arg ListOpenThreadsFirstParams) ([]ListOpenThreadsFirstRow, error) {
	rows, err := q.db.Query(ctx, listOpenThreadsFirst, arg.SubjectType, arg.SubjectRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenThreadsFirstRow{}
	for rows.Next() {
		var i ListOpenThreadsFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectRef,
			&i.AnchorPath,
			&i.Title,
			&i.Body,
			&i.AuthorUserID,
			&i.ReplyCount,
			&i.Status,
			&i.CreatedAt,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadRepliesAfter = `-- name: ListThreadRepliesAfter :many
SELECT r.id, r.thread_id, r.parent_reply_id, r.author_user_id, r.is_ai, r.body, r.created_at, p.handle AS author_handle
FROM thread_replies r
LEFT JOIN community_personas p ON p.user_id = r.author_user_id
WHERE r.thread_id = $1
  AND (r.created_at > $2
       OR (r.created_at = $2 AND r.id > $3))
ORDER BY r.created_at ASC, r.id ASC
LIMIT $4
`

type ListThreadRepliesAfterParams struct {
	ThreadID        int64              `json:"thread_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListThreadRepliesAfterRow struct {
	ID            int64              `json:"id"`
	ThreadID      int64              `json:"thread_id"`
	ParentReplyID pgtype.Int8        `json:"parent_reply_id"`
	AuthorUserID  pgtype.Int8        `json:"author_user_id"`
	IsAi          bool               `json:"is_ai"`
	Body          string             `json:"body"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AuthorHandle  pgtype.Text        `json:"author_handle"`
}

func (q *Queries) ListThreadRepliesAfter(ctx context.Context, arg ListThreadRepliesAfterParams) ([]ListThreadRepliesAfterRow, error) {
	rows, err := q.db.Query(ctx, listThreadRepliesAfter,
		arg.ThreadID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadRepliesAfterRow{}
	for rows.Next() {
		var i ListThreadRepliesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ParentReplyID,
			&i.AuthorUserID,
			&i.IsAi,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadRepliesFirst = `-- name: ListThreadRepliesFirst :many
SELECT r.id, r.thread_id, r.parent_reply_id, r.author_user_id, r.is_ai, r.body, r.created_at, p.handle AS author_handle
FROM thread_replies r
LEFT JOIN community_personas p ON p.user_id = r.author_user_id
WHERE r.thread_id = $1
ORDER BY r.created_at ASC, r.id ASC
LIMIT $2
`

type ListThreadRepliesFirstParams struct {
	ThreadID int64 `json:"thread_id"`
	Limit    int32 `json:"limit"`
}

type ListThreadRepliesFirstRow struct {
	ID            int64              `json:"id"`
	ThreadID      int64              `json:"thread_id"`
	ParentReplyID pgtype.Int8        `json:"parent_reply_id"`
	AuthorUserID  pgtype.Int8        `json:"author_user_id"`
	IsAi          bool               `json:"is_ai"`
	Body          string             `json:"body"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AuthorHandle  pgtype.Text        `json:"author_handle"`
}

// First page of a thread's replies, oldest first. LEFT JOIN so a future AI reply
// (null author) still returns, with a null handle the API renders as the AI persona.
func (q *Queries) ListThreadRepliesFirst(ctx context.Context, arg ListThreadRepliesFirstParams) ([]ListThreadRepliesFirstRow, error) {
	rows, err := q.db.Query(ctx, listThreadRepliesFirst, arg.ThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadRepliesFirstRow{}
	for rows.Next() {
		var i ListThreadRepliesFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ParentReplyID,
			&i.AuthorUserID,
			&i.IsAi,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
