// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*)
FROM companies
WHERE $1::text = '' OR name ILIKE '%' || $1 || '%'
`

// Total companies matching the same optional name filter as ListCompanies, so
// search pagination reports the filtered total.
func (q *Queries) CountCompanies(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOrphanCompanies = `-- name: DeleteOrphanCompanies :execrows
DELETE FROM companies c
WHERE NOT EXISTS (SELECT 1 FROM jobs j WHERE j.company_slug = c.slug)
`

// Drop companies no longer referenced by any job — the stale rows left behind
// when a slug-builder change re-keys jobs onto new slugs.
func (q *Queries) DeleteOrphanCompanies(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanCompanies)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT slug, name, created_at, updated_at, collections
FROM companies
WHERE slug = $1
`

// SELECT * (not an explicit column list) so the generated row stays db.Company as
// the table grows columns (e.g. collections); an explicit subset makes sqlc emit a
// distinct row type and breaks the company-detail handler on every new column.
func (q *Queries) GetCompany(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, slug)
	var i Company
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Collections,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT c.slug, c.name, count(j.company_slug) AS job_count
FROM companies c
LEFT JOIN jobs j ON j.company_slug = c.slug AND j.closed_at IS NULL
WHERE $1::text = '' OR c.name ILIKE '%' || $1 || '%'
GROUP BY c.slug, c.name
ORDER BY c.name
LIMIT $3 OFFSET $2
`

type ListCompaniesParams struct {
	Search string `json:"search"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

type ListCompaniesRow struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	JobCount int64  `json:"job_count"`
}

// Catalog page: companies with their job counts. The job count is computed on
// the fly (no denormalized counter yet). This is the one acknowledged place a
// join to jobs is acceptable; LEFT JOIN keeps companies with zero jobs visible.
// An empty `search` short-circuits the ILIKE, so the same prepared statement
// serves both the full list and a name search (`search` is a case-insensitive
// substring of the name).
func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyCollections = `-- name: ListCompanyCollections :many
SELECT slug, collections
FROM companies
ORDER BY slug
`

type ListCompanyCollectionsRow struct {
	Slug        string   `json:"slug"`
	Collections []string `json:"collections"`
}

// All companies with their current collection membership. cmd/import-collections
// reads this to know the existing company slugs (the match target) and each
// company's current tags (so it can reconcile only the tags it manages, leaving any
// others untouched).
func (q *Queries) ListCompanyCollections(ctx context.Context) ([]ListCompanyCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCompanyCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyCollectionsRow{}
	for rows.Next() {
		var i ListCompanyCollectionsRow
		if err := rows.Scan(&i.Slug, &i.Collections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompanyCollections = `-- name: SetCompanyCollections :exec
UPDATE companies
SET collections = $2,
    updated_at  = now()
WHERE slug = $1
`

type SetCompanyCollectionsParams struct {
	Slug        string   `json:"slug"`
	Collections []string `json:"collections"`
}

// Replace a company's collection set. The import worker computes the full set in Go
// (preserving unmanaged tags) and writes it here; updated_at is bumped for parity
// with the other write paths.
func (q *Queries) SetCompanyCollections(ctx context.Context, arg SetCompanyCollectionsParams) error {
	_, err := q.db.Exec(ctx, setCompanyCollections, arg.Slug, arg.Collections)
	return err
}

const syncCompaniesFromJobs = `-- name: SyncCompaniesFromJobs :exec
INSERT INTO companies (slug, name)
SELECT DISTINCT ON (company_slug) company_slug, company
FROM jobs
WHERE company_slug <> ''
ORDER BY company_slug
ON CONFLICT (slug) DO UPDATE SET
    name       = EXCLUDED.name,
    updated_at = now()
`

// Rebuild the companies catalogue from jobs. The companies table is derivable
// from jobs (slug = company_slug, name = company), so after a slug-builder change
// re-keys jobs, this re-keys companies to match. DISTINCT ON collapses a slug's
// name variants; ON CONFLICT folds collisions and refreshes existing rows.
func (q *Queries) SyncCompaniesFromJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, syncCompaniesFromJobs)
	return err
}
