// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credits.sql

package db

import (
	"context"
)

const debitExists = `-- name: DebitExists :one
SELECT EXISTS (
    SELECT 1 FROM credit_ledger
    WHERE user_id = $1
      AND kind = 'debit'
      AND feature = $2::text
      AND ref = $3::text
)
`

type DebitExistsParams struct {
	UserID  int64  `json:"user_id"`
	Feature string `json:"feature"`
	Ref     string `json:"ref"`
}

// Whether the caller already spent points on this (feature, ref). True means the action
// is a recompute/resume and must not be charged again (idempotency by ref).
func (q *Queries) DebitExists(ctx context.Context, arg DebitExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, debitExists, arg.UserID, arg.Feature, arg.Ref)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ensureBalance = `-- name: EnsureBalance :exec
INSERT INTO credit_balances (user_id, period, remaining)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type EnsureBalanceParams struct {
	UserID    int64  `json:"user_id"`
	Period    string `json:"period"`
	Remaining int32  `json:"remaining"`
}

// Seed a balance row for a brand-new user so the subsequent SELECT ... FOR UPDATE
// always has a row to lock (this is what serializes concurrent first-ever debits).
// For an existing user the row is left untouched; a stale period is reset later
// under the lock. remaining is seeded with the monthly grant for a fresh row.
func (q *Queries) EnsureBalance(ctx context.Context, arg EnsureBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureBalance, arg.UserID, arg.Period, arg.Remaining)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT period, remaining
FROM credit_balances
WHERE user_id = $1
`

type GetBalanceRow struct {
	Period    string `json:"period"`
	Remaining int32  `json:"remaining"`
}

// Read-only balance for display (no lock, no LLM). Returns no rows for a user who has never
// had credit activity; the caller treats that as a full monthly grant remaining.
func (q *Queries) GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i GetBalanceRow
	err := row.Scan(&i.Period, &i.Remaining)
	return i, err
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT period, remaining
FROM credit_balances
WHERE user_id = $1
FOR UPDATE
`

type GetBalanceForUpdateRow struct {
	Period    string `json:"period"`
	Remaining int32  `json:"remaining"`
}

// Lock the caller's balance row for the debit transaction. EnsureBalance guarantees
// the row exists, so this never returns no-rows on the debit path; the lock serializes
// concurrent debits for the same user so the balance can never be oversold.
func (q *Queries) GetBalanceForUpdate(ctx context.Context, userID int64) (GetBalanceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, userID)
	var i GetBalanceForUpdateRow
	err := row.Scan(&i.Period, &i.Remaining)
	return i, err
}

const insertDebit = `-- name: InsertDebit :exec
INSERT INTO credit_ledger (user_id, period, kind, feature, delta, ref)
VALUES ($1, $2, 'debit', $3::text, $4, $5::text)
`

type InsertDebitParams struct {
	UserID  int64  `json:"user_id"`
	Period  string `json:"period"`
	Feature string `json:"feature"`
	Delta   int32  `json:"delta"`
	Ref     string `json:"ref"`
}

// Append the debit for a metered action. delta is negative (the action cost). The partial
// unique index on (user_id, feature, ref) WHERE kind='debit' guards against a double charge
// for the same ref even under a race.
func (q *Queries) InsertDebit(ctx context.Context, arg InsertDebitParams) error {
	_, err := q.db.Exec(ctx, insertDebit,
		arg.UserID,
		arg.Period,
		arg.Feature,
		arg.Delta,
		arg.Ref,
	)
	return err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO credit_ledger (user_id, period, kind, feature, delta)
VALUES ($1, $2, 'grant', NULL, $3)
ON CONFLICT (user_id, period) WHERE kind = 'grant' DO NOTHING
`

type InsertGrantParams struct {
	UserID int64  `json:"user_id"`
	Period string `json:"period"`
	Delta  int32  `json:"delta"`
}

// Record the monthly grant for (user, period), idempotent via the partial unique index
// on (user_id, period) WHERE kind = 'grant'. Safe to call on every debit: it inserts
// once per period and does nothing thereafter. Purchase grants (kind='purchase') are
// exempt from this index and can be added later without contention.
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant, arg.UserID, arg.Period, arg.Delta)
	return err
}

const insertReward = `-- name: InsertReward :exec
INSERT INTO credit_ledger (user_id, period, kind, feature, delta, ref)
VALUES ($1, $2, 'reward', NULL, $3, $4::text)
`

type InsertRewardParams struct {
	UserID int64  `json:"user_id"`
	Period string `json:"period"`
	Delta  int32  `json:"delta"`
	Ref    string `json:"ref"`
}

// Append a reward: points earned (e.g. for an accepted board contribution), delta positive,
// feature NULL. Rewards bank above the monthly grant and survive the period reset.
func (q *Queries) InsertReward(ctx context.Context, arg InsertRewardParams) error {
	_, err := q.db.Exec(ctx, insertReward,
		arg.UserID,
		arg.Period,
		arg.Delta,
		arg.Ref,
	)
	return err
}

const rewardExists = `-- name: RewardExists :one
SELECT EXISTS (
    SELECT 1 FROM credit_ledger
    WHERE user_id = $1
      AND kind = 'reward'
      AND ref = $2::text
)
`

type RewardExistsParams struct {
	UserID int64  `json:"user_id"`
	Ref    string `json:"ref"`
}

// Whether the caller already received a reward for this ref (e.g. an accepted contribution).
// True means the reward was already granted and must not be granted again (idempotency).
func (q *Queries) RewardExists(ctx context.Context, arg RewardExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, rewardExists, arg.UserID, arg.Ref)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE credit_balances
SET period = $1, remaining = $2, updated_at = now()
WHERE user_id = $3
`

type UpdateBalanceParams struct {
	Period    string `json:"period"`
	Remaining int32  `json:"remaining"`
	UserID    int64  `json:"user_id"`
}

// Persist the post-transaction balance: the current period and remaining points. Called at
// the end of the debit transaction to write back any lazy reset and/or decrement. The row is
// guaranteed to exist (EnsureBalance ran first).
func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.Period, arg.Remaining, arg.UserID)
	return err
}
