// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCV = `-- name: CreateCV :one
INSERT INTO cvs (user_id, title, template_id, data)
VALUES ($1, $2, $3, $4)
RETURNING id, title, template_id, created_at, updated_at
`

type CreateCVParams struct {
	UserID     int64  `json:"user_id"`
	Title      string `json:"title"`
	TemplateID string `json:"template_id"`
	Data       []byte `json:"data"`
}

type CreateCVRow struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Insert a new CV for a user. data is the sanitized structured document (JSON). job_id
// defaults NULL (the tailoring seam is unused in phase 1). Returns the metadata the list
// and detail responses need.
func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (CreateCVRow, error) {
	row := q.db.QueryRow(ctx, createCV,
		arg.UserID,
		arg.Title,
		arg.TemplateID,
		arg.Data,
	)
	var i CreateCVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCV = `-- name: DeleteCV :execrows
DELETE FROM cvs
WHERE id = $1 AND user_id = $2
`

type DeleteCVParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Delete a CV owned by the user. Returns the affected-row count so the handler can 404
// when nothing was deleted (foreign or missing id).
func (q *Queries) DeleteCV(ctx context.Context, arg DeleteCVParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCV, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCVByID = `-- name: GetCVByID :one
SELECT id, title, template_id, data, created_at, updated_at
FROM cvs
WHERE id = $1 AND user_id = $2
`

type GetCVByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetCVByIDRow struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// One CV owned by the user, including the full data blob. Owner-scoped: a foreign or
// missing id returns no row (the handler maps it to 404).
func (q *Queries) GetCVByID(ctx context.Context, arg GetCVByIDParams) (GetCVByIDRow, error) {
	row := q.db.QueryRow(ctx, getCVByID, arg.ID, arg.UserID)
	var i GetCVByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCVsByUser = `-- name: ListCVsByUser :many
SELECT id, title, template_id, created_at, updated_at
FROM cvs
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListCVsByUserRow struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// A user's CVs as metadata (no data blob), newest edit first.
func (q *Queries) ListCVsByUser(ctx context.Context, userID int64) ([]ListCVsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCVsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVsByUserRow{}
	for rows.Next() {
		var i ListCVsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCV = `-- name: UpdateCV :one
UPDATE cvs
SET title = $3, template_id = $4, data = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, title, template_id, created_at, updated_at
`

type UpdateCVParams struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	Title      string `json:"title"`
	TemplateID string `json:"template_id"`
	Data       []byte `json:"data"`
}

type UpdateCVRow struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Replace a CV's editable fields, stamping updated_at. Owner-scoped: no row is updated
// for a foreign or missing id (the handler maps the resulting no-row error to 404).
func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) (UpdateCVRow, error) {
	row := q.db.QueryRow(ctx, updateCV,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.TemplateID,
		arg.Data,
	)
	var i UpdateCVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
