// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCV = `-- name: CreateCV :one
INSERT INTO cvs (user_id, title, template_id, data, is_tailored)
VALUES ($1, $2, $3, $4, false)
RETURNING id, title, template_id, created_at, updated_at
`

type CreateCVParams struct {
	UserID     int64  `json:"user_id"`
	Title      string `json:"title"`
	TemplateID string `json:"template_id"`
	Data       []byte `json:"data"`
}

type CreateCVRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Insert a new CV for a user. data is the sanitized structured document (JSON). This is the
// user's own CV, not a copy made for a vacancy, so is_tailored is stated false rather than left to
// be inferred from a NULL job_id — an absence cmd/prune also produces. Users may own several of
// these. Returns the metadata the list and detail responses need.
func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (CreateCVRow, error) {
	row := q.db.QueryRow(ctx, createCV,
		arg.UserID,
		arg.Title,
		arg.TemplateID,
		arg.Data,
	)
	var i CreateCVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTailoredCV = `-- name: CreateTailoredCV :one
INSERT INTO cvs (user_id, title, template_id, data, job_id, is_tailored)
VALUES ($1, $2, $3, $4, $5, true)
RETURNING id, title, template_id, created_at, updated_at
`

type CreateTailoredCVParams struct {
	UserID     int64       `json:"user_id"`
	Title      string      `json:"title"`
	TemplateID string      `json:"template_id"`
	Data       []byte      `json:"data"`
	JobID      pgtype.Int8 `json:"job_id"`
}

type CreateTailoredCVRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Insert a CV bound to a vacancy (job_id set) — the per-vacancy tailored copy. data is the
// sanitized document copied from the base CV. is_tailored is stated, not inferred: if this vacancy
// is ever pruned the row loses its job_id, and the flag is what keeps it a tailored copy instead of
// joining the pool the base is chosen from. Returns the metadata the detail response needs.
func (q *Queries) CreateTailoredCV(ctx context.Context, arg CreateTailoredCVParams) (CreateTailoredCVRow, error) {
	row := q.db.QueryRow(ctx, createTailoredCV,
		arg.UserID,
		arg.Title,
		arg.TemplateID,
		arg.Data,
		arg.JobID,
	)
	var i CreateTailoredCVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCV = `-- name: DeleteCV :execrows
DELETE FROM cvs
WHERE id = $1 AND user_id = $2
`

type DeleteCVParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

// Delete a CV owned by the user. Returns the affected-row count so the handler can 404
// when nothing was deleted (foreign or missing id).
func (q *Queries) DeleteCV(ctx context.Context, arg DeleteCVParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCV, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBaseCVByUser = `-- name: GetBaseCVByUser :one
SELECT id, title, template_id, data, created_at, updated_at
FROM cvs
WHERE user_id = $1 AND NOT is_tailored
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetBaseCVByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// The user's base CV — their non-tailored résumé. Used as the seed source when tailoring;
// returns no row when the user has only tailored CVs or none at all (the caller then seeds a base
// from the extracted résumé), INCLUDING when their only vacancy-less CV is a tailored copy whose
// vacancy was pruned. Excluding on is_tailored rather than requiring `job_id IS NULL` is the whole
// point: the absence of a vacancy link is something cmd/prune creates, so it cannot mean "not
// tailored".
//
// "The base" stays a derived notion — the most recently edited non-tailored CV. Users may own
// several (cv-builder), so there is no uniqueness constraint and the ORDER BY does the choosing.
func (q *Queries) GetBaseCVByUser(ctx context.Context, userID int64) (GetBaseCVByUserRow, error) {
	row := q.db.QueryRow(ctx, getBaseCVByUser, userID)
	var i GetBaseCVByUserRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVByID = `-- name: GetCVByID :one
SELECT c.id, c.title, c.template_id, c.data, c.job_id, c.is_tailored, c.agent_session_id,
       c.autopilot_report, c.tracer_links_enabled,
       -- The company this copy was tailored for, which is what a tracer token is prefixed with:
       -- the recruiter reads it on hover, and their own company's name alarms less than an
       -- opaque string. Empty for a base CV, and for a tailored copy whose vacancy was pruned.
       coalesce(j.company_slug, '') AS company_slug,
       c.created_at, c.updated_at
FROM cvs c
LEFT JOIN jobs j ON j.id = c.job_id
WHERE c.id = $1 AND c.user_id = $2
`

type GetCVByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

type GetCVByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Title              string             `json:"title"`
	TemplateID         string             `json:"template_id"`
	Data               []byte             `json:"data"`
	JobID              pgtype.Int8        `json:"job_id"`
	IsTailored         bool               `json:"is_tailored"`
	AgentSessionID     pgtype.Text        `json:"agent_session_id"`
	AutopilotReport    []byte             `json:"autopilot_report"`
	TracerLinksEnabled bool               `json:"tracer_links_enabled"`
	CompanySlug        string             `json:"company_slug"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// One CV owned by the user, including the full data blob. Owner-scoped: a foreign or
// missing id returns no row (the handler maps it to 404). job_id is NULL for a base CV and
// the vacancy id for a tailored copy; agent_session_id is the bound roy session (or NULL).
// The autopilot columns are reported as the report itself plus a boolean: the pre-run snapshot
// is a whole second document, and no caller needs its bytes — only whether one exists.
func (q *Queries) GetCVByID(ctx context.Context, arg GetCVByIDParams) (GetCVByIDRow, error) {
	row := q.db.QueryRow(ctx, getCVByID, arg.ID, arg.UserID)
	var i GetCVByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.Data,
		&i.JobID,
		&i.IsTailored,
		&i.AgentSessionID,
		&i.AutopilotReport,
		&i.TracerLinksEnabled,
		&i.CompanySlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTailoredCVForJob = `-- name: GetTailoredCVForJob :one
SELECT id, title, template_id, data, agent_session_id, created_at, updated_at
FROM cvs
WHERE user_id = $1 AND job_id = $2
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetTailoredCVForJobParams struct {
	UserID int64       `json:"user_id"`
	JobID  pgtype.Int8 `json:"job_id"`
}

type GetTailoredCVForJobRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	TemplateID     string             `json:"template_id"`
	Data           []byte             `json:"data"`
	AgentSessionID pgtype.Text        `json:"agent_session_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// The user's existing tailored copy for one vacancy, newest first. The tailoring bootstrap is
// reached by an address (/tailor/<slug>) that carries no CV reference, so a reload runs the
// same request again: without this read every refresh minted another copy and stranded the
// conversation bound to the previous one.
func (q *Queries) GetTailoredCVForJob(ctx context.Context, arg GetTailoredCVForJobParams) (GetTailoredCVForJobRow, error) {
	row := q.db.QueryRow(ctx, getTailoredCVForJob, arg.UserID, arg.JobID)
	var i GetTailoredCVForJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.Data,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCVsByUser = `-- name: ListCVsByUser :many
SELECT id, title, template_id, created_at, updated_at
FROM cvs
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListCVsByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// A user's CVs as metadata (no data blob), newest edit first.
func (q *Queries) ListCVsByUser(ctx context.Context, userID int64) ([]ListCVsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCVsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVsByUserRow{}
	for rows.Next() {
		var i ListCVsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTailoredCVsByUser = `-- name: ListTailoredCVsByUser :many
SELECT c.id, c.title, c.template_id, c.agent_session_id, j.public_slug AS job_slug,
       j.title AS job_title, j.company AS job_company, c.created_at, c.updated_at
FROM cvs c
JOIN jobs j ON j.id = c.job_id
WHERE c.user_id = $1 AND c.job_id IS NOT NULL
ORDER BY c.updated_at DESC
`

type ListTailoredCVsByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	TemplateID     string             `json:"template_id"`
	AgentSessionID pgtype.Text        `json:"agent_session_id"`
	JobSlug        string             `json:"job_slug"`
	JobTitle       string             `json:"job_title"`
	JobCompany     string             `json:"job_company"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// A user's TAILORED CVs (bound to a vacancy), newest edit first — the re-open list. Carries the
// vacancy's public slug and the bound agent session so each row links back to its workspace.
// Base CVs (job_id NULL) are excluded; the JOIN also drops tailored CVs whose job was deleted.
func (q *Queries) ListTailoredCVsByUser(ctx context.Context, userID int64) ([]ListTailoredCVsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTailoredCVsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTailoredCVsByUserRow{}
	for rows.Next() {
		var i ListTailoredCVsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TemplateID,
			&i.AgentSessionID,
			&i.JobSlug,
			&i.JobTitle,
			&i.JobCompany,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeCVAutopilotEntry = `-- name: MergeCVAutopilotEntry :execrows
UPDATE cvs
SET autopilot_report = CASE
    WHEN EXISTS (
      SELECT 1 FROM jsonb_array_elements(COALESCE(autopilot_report, '[]'::jsonb)) elem
      WHERE lower(trim(elem ->> 'requirement')) = lower(trim($3::jsonb ->> 'requirement'))
    )
    THEN (
      SELECT jsonb_agg(
        CASE WHEN lower(trim(elem ->> 'requirement')) = lower(trim($3::jsonb ->> 'requirement'))
             THEN $3::jsonb ELSE elem END
      )
      FROM jsonb_array_elements(COALESCE(autopilot_report, '[]'::jsonb)) elem
    )
    ELSE COALESCE(autopilot_report, '[]'::jsonb) || jsonb_build_array($3::jsonb)
  END
WHERE id = $1 AND user_id = $2
`

type MergeCVAutopilotEntryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
	Entry  []byte    `json:"entry"`
}

// Fold ONE requirement's outcome into the run report: replace the entry whose requirement
// matches case- and whitespace-insensitively, or append when none does. Done as one UPDATE
// expression rather than a read-modify-write from Go, because a read-modify-write has no lock
// between its two calls — two concurrent merges (a duplicate tool call, two requests racing
// during a run) can both read the same starting report and each overwrite the other's entry.
// The CASE here evaluates against one row snapshot under Postgres's own row-level lock for the
// UPDATE, so nothing else can observe or write the row mid-merge. Owner-scoped: 0 rows for a
// foreign id.
func (q *Queries) MergeCVAutopilotEntry(ctx context.Context, arg MergeCVAutopilotEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCVAutopilotEntry, arg.ID, arg.UserID, arg.Entry)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCVAutopilotReport = `-- name: SetCVAutopilotReport :execrows
UPDATE cvs
SET autopilot_report = $3
WHERE id = $1 AND user_id = $2
`

type SetCVAutopilotReportParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          int64     `json:"user_id"`
	AutopilotReport []byte    `json:"autopilot_report"`
}

// Replace the run report on an owned CV. The agent writes the WHOLE report on every call —
// there is no partial update, so a requirement closed later from the candidate's own words
// arrives as the same list with one entry changed. Owner-scoped: 0 rows for a foreign id.
func (q *Queries) SetCVAutopilotReport(ctx context.Context, arg SetCVAutopilotReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCVAutopilotReport, arg.ID, arg.UserID, arg.AutopilotReport)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCVSession = `-- name: SetCVSession :execrows
UPDATE cvs
SET agent_session_id = $3
WHERE id = $1 AND user_id = $2
`

type SetCVSessionParams struct {
	ID             uuid.UUID   `json:"id"`
	UserID         int64       `json:"user_id"`
	AgentSessionID pgtype.Text `json:"agent_session_id"`
}

// Bind (or rebind) the agent session to an owned CV. Owner-scoped: returns 0 affected rows for
// a foreign or missing id (the handler maps that to 404).
func (q *Queries) SetCVSession(ctx context.Context, arg SetCVSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCVSession, arg.ID, arg.UserID, arg.AgentSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCV = `-- name: UpdateCV :one
UPDATE cvs
SET title = $3, template_id = $4, data = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, title, template_id, created_at, updated_at
`

type UpdateCVParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     int64     `json:"user_id"`
	Title      string    `json:"title"`
	TemplateID string    `json:"template_id"`
	Data       []byte    `json:"data"`
}

type UpdateCVRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	TemplateID string             `json:"template_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Replace a CV's editable fields, stamping updated_at. Owner-scoped: no row is updated
// for a foreign or missing id (the handler maps the resulting no-row error to 404).
func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) (UpdateCVRow, error) {
	row := q.db.QueryRow(ctx, updateCV,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.TemplateID,
		arg.Data,
	)
	var i UpdateCVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
