// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpEmailCodeAttempts = `-- name: BumpEmailCodeAttempts :one
UPDATE user_email_codes
SET attempts = attempts + 1
WHERE user_id = $1 AND purpose = $2
RETURNING attempts
`

type BumpEmailCodeAttemptsParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

// Count one failed confirmation and return the new total, so the caller can burn the code
// once it reaches the ceiling. Atomic, so concurrent guesses cannot share an attempt.
func (q *Queries) BumpEmailCodeAttempts(ctx context.Context, arg BumpEmailCodeAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpEmailCodeAttempts, arg.UserID, arg.Purpose)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const deleteEmailCode = `-- name: DeleteEmailCode :exec
DELETE FROM user_email_codes
WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailCodeParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

// Consume the code (on success) or burn it (on too many attempts). Idempotent: deleting
// an absent code is a no-op, so a double submit cannot fail the request.
func (q *Queries) DeleteEmailCode(ctx context.Context, arg DeleteEmailCodeParams) error {
	_, err := q.db.Exec(ctx, deleteEmailCode, arg.UserID, arg.Purpose)
	return err
}

const getEmailCode = `-- name: GetEmailCode :one
SELECT code_hash, expires_at, attempts, created_at
FROM user_email_codes
WHERE user_id = $1 AND purpose = $2
`

type GetEmailCodeParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

type GetEmailCodeRow struct {
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The outstanding code for a purpose. No row means nothing was issued or it was consumed;
// the caller treats pgx.ErrNoRows as "request a new code". Expiry and the attempt ceiling
// are enforced by the caller, which must fail identically for expired and wrong codes.
func (q *Queries) GetEmailCode(ctx context.Context, arg GetEmailCodeParams) (GetEmailCodeRow, error) {
	row := q.db.QueryRow(ctx, getEmailCode, arg.UserID, arg.Purpose)
	var i GetEmailCodeRow
	err := row.Scan(
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailCodeForUpdate = `-- name: GetEmailCodeForUpdate :one
SELECT code_hash, expires_at, attempts, created_at
FROM user_email_codes
WHERE user_id = $1 AND purpose = $2
FOR UPDATE
`

type GetEmailCodeForUpdateParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

type GetEmailCodeForUpdateRow struct {
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// The outstanding code for a purpose locked for update inside a transaction.
func (q *Queries) GetEmailCodeForUpdate(ctx context.Context, arg GetEmailCodeForUpdateParams) (GetEmailCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEmailCodeForUpdate, arg.UserID, arg.Purpose)
	var i GetEmailCodeForUpdateRow
	err := row.Scan(
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmailCode = `-- name: UpsertEmailCode :exec
INSERT INTO user_email_codes (user_id, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, purpose) DO UPDATE
SET code_hash  = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempts   = 0,
    created_at = now()
`

type UpsertEmailCodeParams struct {
	UserID    int64              `json:"user_id"`
	Purpose   string             `json:"purpose"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Issue (or replace) the outstanding code for one purpose. The composite primary key
// makes this the whole "at most one live code per (user, purpose)" rule: a resend
// overwrites the hash and expiry and resets attempts, so a burnt code never lingers
// beside a fresh one. created_at is re-stamped, which is what the resend cooldown reads.
func (q *Queries) UpsertEmailCode(ctx context.Context, arg UpsertEmailCodeParams) error {
	_, err := q.db.Exec(ctx, upsertEmailCode,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}
