// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facet_stats.sql

package db

import (
	"context"
)

const deleteAllFacetStats = `-- name: DeleteAllFacetStats :exec

DELETE FROM insights_facet_stats
`

// Facet-distribution snapshot (insights_facet_stats), recomputed by
// cmd/rollup-facets as an atomic delete-and-reinsert, and the read query the public
// /api/v1/stats/facets endpoint serves from it. The source is Meilisearch's facet
// count (not `jobs`), so the worker inserts rows it already holds in memory rather
// than a set-based INSERT ... SELECT.
// First half of the atomic rebuild: clear the snapshot. Run in the same transaction
// as the InsertFacetStat loop so a reader never sees an empty or partial table.
func (q *Queries) DeleteAllFacetStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllFacetStats)
	return err
}

const insertFacetStat = `-- name: InsertFacetStat :exec
INSERT INTO insights_facet_stats (facet, value, count)
VALUES ($1, $2, $3)
`

type InsertFacetStatParams struct {
	Facet string `json:"facet"`
	Value string `json:"value"`
	Count int64  `json:"count"`
}

// Second half of the atomic rebuild: one row per (facet, value). Called once per
// value the worker computed, inside the same transaction as DeleteAllFacetStats.
func (q *Queries) InsertFacetStat(ctx context.Context, arg InsertFacetStatParams) error {
	_, err := q.db.Exec(ctx, insertFacetStat, arg.Facet, arg.Value, arg.Count)
	return err
}

const listFacetStats = `-- name: ListFacetStats :many
SELECT facet, value, count
FROM insights_facet_stats
ORDER BY facet, count DESC
`

// The whole snapshot, ordered by facet then count DESC so the reader can take the
// top-N per facet without re-sorting. Aggregate only — per-value counts, no
// record-level data.
func (q *Queries) ListFacetStats(ctx context.Context) ([]InsightsFacetStat, error) {
	rows, err := q.db.Query(ctx, listFacetStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsFacetStat{}
	for rows.Next() {
		var i InsightsFacetStat
		if err := rows.Scan(&i.Facet, &i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
