// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ghost_crosscheck.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearJobATSAbsent = `-- name: ClearJobATSAbsent :exec
UPDATE jobs SET ats_absent_at = NULL
WHERE id = ANY($1::bigint[]) AND ats_absent_at IS NOT NULL
`

// Withdraw the absence stamp: the role turned up on the company's board after all.
// Scoped to rows that carry a stamp so a run over a healthy company writes nothing.
func (q *Queries) ClearJobATSAbsent(ctx context.Context, jobIds []int64) error {
	_, err := q.db.Exec(ctx, clearJobATSAbsent, jobIds)
	return err
}

const listAggregatorJobsForCrosscheck = `-- name: ListAggregatorJobsForCrosscheck :many
SELECT j.id, j.company_slug, j.title, j.ats_absent_at
FROM jobs j
WHERE j.closed_at IS NULL
  AND j.source = ANY($1::text[])
  AND j.id > $2
ORDER BY j.id
LIMIT $3
`

type ListAggregatorJobsForCrosscheckParams struct {
	AggregatorSources []string `json:"aggregator_sources"`
	AfterID           int64    `json:"after_id"`
	PageSize          int32    `json:"page_size"`
}

type ListAggregatorJobsForCrosscheckRow struct {
	ID          int64              `json:"id"`
	CompanySlug string             `json:"company_slug"`
	Title       string             `json:"title"`
	AtsAbsentAt pgtype.Timestamptz `json:"ats_absent_at"`
}

// Keyset page of open aggregator postings to cross-check, ordered by id so the scan
// resumes exactly where it stopped. The worker buffers a page and groups it by company
// itself, so a company's board is read once rather than once per posting; ordering by
// company instead would make the keyset cursor non-unique and risk skipping rows.
//
// The caller passes the aggregator provider names (sources.AggregatorProviders): the
// provider taxonomy lives in Go adapter markers, not in the database, and copying it
// into SQL would leave two lists to keep in step.
func (q *Queries) ListAggregatorJobsForCrosscheck(ctx context.Context, arg ListAggregatorJobsForCrosscheckParams) ([]ListAggregatorJobsForCrosscheckRow, error) {
	rows, err := q.db.Query(ctx, listAggregatorJobsForCrosscheck, arg.AggregatorSources, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAggregatorJobsForCrosscheckRow{}
	for rows.Next() {
		var i ListAggregatorJobsForCrosscheckRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanySlug,
			&i.Title,
			&i.AtsAbsentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyBoardTitles = `-- name: ListCompanyBoardTitles :many
SELECT j.title
FROM jobs j
WHERE j.closed_at IS NULL
  AND j.company_slug = $1
  AND j.source = ANY($2::text[])
`

type ListCompanyBoardTitlesParams struct {
	CompanySlug  string   `json:"company_slug"`
	BoardSources []string `json:"board_sources"`
}

// The open titles a company carries on its OWN board — a source of kind `ats` or
// `company`, never an aggregator. The worker turns these into role keys and asks
// whether an aggregator posting's key is among them.
//
// This is the COVERAGE GATE's data as well as its answer. An empty result means we do
// not crawl this company's board at all, and the worker must then stamp nothing:
// absence is evidence only where we looked, and without the gate the signal would
// report our own blind spots as the employer's fault.
func (q *Queries) ListCompanyBoardTitles(ctx context.Context, arg ListCompanyBoardTitlesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listCompanyBoardTitles, arg.CompanySlug, arg.BoardSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobGhostStamps = `-- name: ListJobGhostStamps :many
SELECT id, ats_absent_at FROM jobs WHERE id = ANY($1::bigint[])
`

type ListJobGhostStampsRow struct {
	ID          int64              `json:"id"`
	AtsAbsentAt pgtype.Timestamptz `json:"ats_absent_at"`
}

// The absence stamps of a page of jobs, for the read paths that do not already hold
// the rows — search results come back from Meilisearch, which does not carry this
// column (and cannot: reindex is content_hash-incremental, so a column no adapter
// writes would never reach the index on its own).
func (q *Queries) ListJobGhostStamps(ctx context.Context, jobIds []int64) ([]ListJobGhostStampsRow, error) {
	rows, err := q.db.Query(ctx, listJobGhostStamps, jobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobGhostStampsRow{}
	for rows.Next() {
		var i ListJobGhostStampsRow
		if err := rows.Scan(&i.ID, &i.AtsAbsentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampJobATSAbsent = `-- name: StampJobATSAbsent :exec
UPDATE jobs SET ats_absent_at = now() WHERE id = ANY($1::bigint[])
`

// Record that this posting's role was not found on its company's own board, as of now.
// Re-stamped on every run, so the reader can ignore a stamp that has aged out and a
// worker that has stopped falls silent instead of accusing from a frozen snapshot.
func (q *Queries) StampJobATSAbsent(ctx context.Context, jobIds []int64) error {
	_, err := q.db.Exec(ctx, stampJobATSAbsent, jobIds)
	return err
}
