// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ghost_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGhostReportsSince = `-- name: CountGhostReportsSince :one
SELECT count(*) FROM ghost_reports
WHERE user_id = $1::bigint
  AND created_at >= $2::timestamptz
`

type CountGhostReportsSinceParams struct {
	UserID int64              `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

// How many claims this account has filed since a cutoff, for the daily cap. Counts
// retracted rows too: filing and withdrawing in a loop is exactly the pattern the cap
// exists to bound, so forgiving it would leave the cap trivially bypassable.
func (q *Queries) CountGhostReportsSince(ctx context.Context, arg CountGhostReportsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGhostReportsSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGhostReport = `-- name: CreateGhostReport :one
INSERT INTO ghost_reports (user_id, job_id, applied_on)
SELECT u.id, j.id, $1::date
FROM users u, jobs j
WHERE u.id = $2::bigint
  AND u.email_verified
  AND j.id = $3::bigint
  AND j.closed_at IS NULL
ON CONFLICT (user_id, job_id) DO UPDATE
  SET retracted_at = NULL,
      applied_on   = EXCLUDED.applied_on,
      created_at   = now()
  WHERE ghost_reports.retracted_at IS NOT NULL
RETURNING id, user_id, job_id, applied_on, created_at, retracted_at
`

type CreateGhostReportParams struct {
	AppliedOn pgtype.Date `json:"applied_on"`
	UserID    int64       `json:"user_id"`
	JobID     int64       `json:"job_id"`
}

// File one person's claim that they applied to a posting and were never answered.
//
// Two of the three refusals are STRUCTURAL rather than checks the service performs:
// the INSERT selects from users and jobs, so an unproven address or a posting already
// taken down inserts no row at all. That is the same shape CreateAPIKey uses for the
// verified-address gate — a guarantee nothing downstream can forget to apply.
//
// A conflicting row that has been RETRACTED is revived rather than refused: retracting
// by mistake must not lock somebody out of their own claim forever, and reviving cannot
// inflate anything, since the row (and so the person) is still counted once. A
// conflicting row that is still live updates nothing (the DO UPDATE's WHERE), returning
// no row, which the repository reports as a duplicate.
//
// Because all four outcomes are "no row", the repository asks GhostReportRefusalReason
// which one it was. That costs an extra query only on the failure path.
func (q *Queries) CreateGhostReport(ctx context.Context, arg CreateGhostReportParams) (GhostReport, error) {
	row := q.db.QueryRow(ctx, createGhostReport, arg.AppliedOn, arg.UserID, arg.JobID)
	var i GhostReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.AppliedOn,
		&i.CreatedAt,
		&i.RetractedAt,
	)
	return i, err
}

const ghostReportRefusalReason = `-- name: GhostReportRefusalReason :one
SELECT
  coalesce((SELECT u.email_verified FROM users u
             WHERE u.id = $1::bigint), false)::boolean AS email_verified,
  coalesce((SELECT j.closed_at IS NULL FROM jobs j
             WHERE j.id = $2::bigint), false)::boolean AS job_open,
  (EXISTS (SELECT 1 FROM ghost_reports r
            WHERE r.user_id = $1::bigint
              AND r.job_id = $2::bigint
              AND r.retracted_at IS NULL))::boolean AS already_reported
`

type GhostReportRefusalReasonParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

type GhostReportRefusalReasonRow struct {
	EmailVerified   bool `json:"email_verified"`
	JobOpen         bool `json:"job_open"`
	AlreadyReported bool `json:"already_reported"`
}

// Why CreateGhostReport returned no row. Read only on the failure path, so the happy
// path stays one statement. Each column answers one gate, and the repository maps the
// first failing one — unverified before closed before duplicate — because an
// unverified account should be told to confirm its address rather than that somebody
// already reported the job.
func (q *Queries) GhostReportRefusalReason(ctx context.Context, arg GhostReportRefusalReasonParams) (GhostReportRefusalReasonRow, error) {
	row := q.db.QueryRow(ctx, ghostReportRefusalReason, arg.UserID, arg.JobID)
	var i GhostReportRefusalReasonRow
	err := row.Scan(&i.EmailVerified, &i.JobOpen, &i.AlreadyReported)
	return i, err
}

const retractGhostReport = `-- name: RetractGhostReport :one
UPDATE ghost_reports
SET retracted_at = now()
WHERE user_id = $1::bigint
  AND job_id = $2::bigint
  AND retracted_at IS NULL
RETURNING id, user_id, job_id, applied_on, created_at, retracted_at
`

type RetractGhostReportParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

// Withdraw a live claim. Scoped to a non-retracted row so a second retraction affects
// nothing and surfaces as not-found, rather than silently re-stamping the date.
func (q *Queries) RetractGhostReport(ctx context.Context, arg RetractGhostReportParams) (GhostReport, error) {
	row := q.db.QueryRow(ctx, retractGhostReport, arg.UserID, arg.JobID)
	var i GhostReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.AppliedOn,
		&i.CreatedAt,
		&i.RetractedAt,
	)
	return i, err
}
