// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllInsightsCompanyGrowth = `-- name: DeleteAllInsightsCompanyGrowth :exec

DELETE FROM insights_company_growth
`

// ---------------------------------------------------------------------------
// Per-company open/growth scalar (backs the /insights/companies leaderboard)
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsCompanyGrowth(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsCompanyGrowth)
	return err
}

const deleteAllInsightsCompanyResponse = `-- name: DeleteAllInsightsCompanyResponse :exec
DELETE FROM insights_company_response
`

func (q *Queries) DeleteAllInsightsCompanyResponse(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsCompanyResponse)
	return err
}

const deleteAllInsightsCompanyStats = `-- name: DeleteAllInsightsCompanyStats :exec

DELETE FROM insights_company_stats
`

// ---------------------------------------------------------------------------
// Per-company hiring signal
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsCompanyStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsCompanyStats)
	return err
}

const deleteAllInsightsRoleStats = `-- name: DeleteAllInsightsRoleStats :exec


DELETE FROM insights_role_stats
`

// Trends & Insights rollups (insights_*), recomputed by cmd/rollup-stats as an
// atomic delete-and-reinsert, and the read queries the public /api/v1/insights/*
// endpoints serve from them. All rollups are a pure function of current `jobs`
// state; @prev_ts (the growth-window start) and @min_sample are supplied by the
// worker so the window and sample floor stay out of the SQL and are test-injectable.
// ---------------------------------------------------------------------------
// Role demand
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsRoleStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsRoleStats)
	return err
}

const deleteAllInsightsSalaryStats = `-- name: DeleteAllInsightsSalaryStats :exec

DELETE FROM insights_salary_stats
`

// ---------------------------------------------------------------------------
// Salary bands
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsSalaryStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsSalaryStats)
	return err
}

const deleteAllInsightsSkillStats = `-- name: DeleteAllInsightsSkillStats :exec

DELETE FROM insights_skill_stats
`

// ---------------------------------------------------------------------------
// Skill demand
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsSkillStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsSkillStats)
	return err
}

const deleteAllInsightsVelocityDaily = `-- name: DeleteAllInsightsVelocityDaily :exec

DELETE FROM insights_velocity_daily
`

// ---------------------------------------------------------------------------
// Hiring velocity (faceted)
// ---------------------------------------------------------------------------
func (q *Queries) DeleteAllInsightsVelocityDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllInsightsVelocityDaily)
	return err
}

const getCompanyResponse = `-- name: GetCompanyResponse :one
SELECT applications, answered, median_reply_days FROM insights_company_response WHERE company_slug = $1
`

type GetCompanyResponseRow struct {
	Applications    int32         `json:"applications"`
	Answered        int32         `json:"answered"`
	MedianReplyDays pgtype.Float4 `json:"median_reply_days"`
}

// The observable application counts for one company. A company with no row has no
// observable applications at all, which the caller must treat as "not enough data"
// rather than as a zero response rate.
func (q *Queries) GetCompanyResponse(ctx context.Context, companySlug string) (GetCompanyResponseRow, error) {
	row := q.db.QueryRow(ctx, getCompanyResponse, companySlug)
	var i GetCompanyResponseRow
	err := row.Scan(&i.Applications, &i.Answered, &i.MedianReplyDays)
	return i, err
}

const listInsightsCompanies = `-- name: ListInsightsCompanies :many
SELECT
    g.company_slug,
    coalesce(c.name, g.company_slug) AS company_name,
    g.open_count,
    g.open_count_prev,
    (g.open_count - g.open_count_prev)::int AS growth
FROM insights_company_growth g
LEFT JOIN companies c ON c.slug = g.company_slug
WHERE g.open_count >= $1::int
ORDER BY
    (CASE
        WHEN $2::text = 'open'     THEN g.open_count
        WHEN $2::text = '-growth'  THEN -(g.open_count - g.open_count_prev)
        ELSE (g.open_count - g.open_count_prev)
    END) DESC,
    g.open_count DESC
LIMIT $3::int
`

type ListInsightsCompaniesParams struct {
	MinOpen int32  `json:"min_open"`
	Sort    string `json:"sort"`
	Lim     int32  `json:"lim"`
}

type ListInsightsCompaniesRow struct {
	CompanySlug   string `json:"company_slug"`
	CompanyName   string `json:"company_name"`
	OpenCount     int32  `json:"open_count"`
	OpenCountPrev int32  `json:"open_count_prev"`
	Growth        int32  `json:"growth"`
}

// The leaderboard read: companies ranked by growth (open_count - open_count_prev),
// '-growth' (freezing) reverses it, 'open' ranks by raw size; open_count is the
// tiebreak. @min_open floors the current open-count (blunts ingest-artifact spikes).
// company_name falls back to the slug when no companies row exists.
func (q *Queries) ListInsightsCompanies(ctx context.Context, arg ListInsightsCompaniesParams) ([]ListInsightsCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listInsightsCompanies, arg.MinOpen, arg.Sort, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsCompaniesRow{}
	for rows.Next() {
		var i ListInsightsCompaniesRow
		if err := rows.Scan(
			&i.CompanySlug,
			&i.CompanyName,
			&i.OpenCount,
			&i.OpenCountPrev,
			&i.Growth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsRoles = `-- name: ListInsightsRoles :many
SELECT category, seniority, open_count, (open_count - open_count_prev)::int AS growth
FROM insights_role_stats
WHERE country = $1
  AND ($2::text = '' OR category = $2)
ORDER BY
    (CASE WHEN $3::text = 'growth' THEN (open_count - open_count_prev) ELSE open_count END) DESC,
    open_count DESC
LIMIT $4::int
`

type ListInsightsRolesParams struct {
	Country  string `json:"country"`
	Category string `json:"category"`
	Sort     string `json:"sort"`
	Lim      int32  `json:"lim"`
}

type ListInsightsRolesRow struct {
	Category  string `json:"category"`
	Seniority string `json:"seniority"`
	OpenCount int32  `json:"open_count"`
	Growth    int32  `json:"growth"`
}

// Ranked roles within one country slice (” = all countries), ordered by raw
// demand or by growth (open_count - open_count_prev), demand as the tiebreak.
// An empty @category means all categories (the original behavior); a non-empty
// @category restricts the ranking to that category's seniorities.
func (q *Queries) ListInsightsRoles(ctx context.Context, arg ListInsightsRolesParams) ([]ListInsightsRolesRow, error) {
	rows, err := q.db.Query(ctx, listInsightsRoles,
		arg.Country,
		arg.Category,
		arg.Sort,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsRolesRow{}
	for rows.Next() {
		var i ListInsightsRolesRow
		if err := rows.Scan(
			&i.Category,
			&i.Seniority,
			&i.OpenCount,
			&i.Growth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsSalary = `-- name: ListInsightsSalary :many
SELECT currency, period, sample_size, p25, p50, p75
FROM insights_salary_stats
WHERE category = $1
  AND seniority = $2
  AND country = $3
ORDER BY sample_size DESC
`

type ListInsightsSalaryParams struct {
	Category  string `json:"category"`
	Seniority string `json:"seniority"`
	Country   string `json:"country"`
}

type ListInsightsSalaryRow struct {
	Currency   string `json:"currency"`
	Period     string `json:"period"`
	SampleSize int32  `json:"sample_size"`
	P25        int32  `json:"p25"`
	P50        int32  `json:"p50"`
	P75        int32  `json:"p75"`
}

// Salary bands for one role × country scope, one row per (currency, period),
// richest samples first. Currencies are never combined.
func (q *Queries) ListInsightsSalary(ctx context.Context, arg ListInsightsSalaryParams) ([]ListInsightsSalaryRow, error) {
	rows, err := q.db.Query(ctx, listInsightsSalary, arg.Category, arg.Seniority, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsSalaryRow{}
	for rows.Next() {
		var i ListInsightsSalaryRow
		if err := rows.Scan(
			&i.Currency,
			&i.Period,
			&i.SampleSize,
			&i.P25,
			&i.P50,
			&i.P75,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsSalaryByCategory = `-- name: ListInsightsSalaryByCategory :many
SELECT seniority, currency, period, sample_size, p25, p50, p75
FROM insights_salary_stats
WHERE category = $1
  AND country = ''
ORDER BY seniority, sample_size DESC
`

type ListInsightsSalaryByCategoryRow struct {
	Seniority  string `json:"seniority"`
	Currency   string `json:"currency"`
	Period     string `json:"period"`
	SampleSize int32  `json:"sample_size"`
	P25        int32  `json:"p25"`
	P50        int32  `json:"p50"`
	P75        int32  `json:"p75"`
}

// All-seniority salary bands for one category (country-agnostic ” bucket), so a
// per-category salary page is one call: one row per (seniority, currency, period),
// richest samples first. seniority ” is the category-wide band; the named
// seniorities are the per-grade bands. Bands below the sample floor are already
// absent from the rollup.
func (q *Queries) ListInsightsSalaryByCategory(ctx context.Context, category string) ([]ListInsightsSalaryByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listInsightsSalaryByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsSalaryByCategoryRow{}
	for rows.Next() {
		var i ListInsightsSalaryByCategoryRow
		if err := rows.Scan(
			&i.Seniority,
			&i.Currency,
			&i.Period,
			&i.SampleSize,
			&i.P25,
			&i.P50,
			&i.P75,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsSkillHistory = `-- name: ListInsightsSkillHistory :many
SELECT skill, week_start, open_count
FROM insights_skill_history
WHERE skill = ANY($1::text[])
ORDER BY skill, week_start DESC
`

// All retained weekly snapshots for a set of skills (a caller's own profile
// skills), newest first per skill.
func (q *Queries) ListInsightsSkillHistory(ctx context.Context, skills []string) ([]InsightsSkillHistory, error) {
	rows, err := q.db.Query(ctx, listInsightsSkillHistory, skills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsSkillHistory{}
	for rows.Next() {
		var i InsightsSkillHistory
		if err := rows.Scan(&i.Skill, &i.WeekStart, &i.OpenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsSkills = `-- name: ListInsightsSkills :many
SELECT skill, open_count, (open_count - open_count_prev)::int AS growth
FROM insights_skill_stats
WHERE category = $1 AND country = $2
ORDER BY
    (CASE WHEN $3::text = 'growth' THEN (open_count - open_count_prev) ELSE open_count END) DESC,
    open_count DESC
LIMIT $4::int
`

type ListInsightsSkillsParams struct {
	Category string `json:"category"`
	Country  string `json:"country"`
	Sort     string `json:"sort"`
	Lim      int32  `json:"lim"`
}

type ListInsightsSkillsRow struct {
	Skill     string `json:"skill"`
	OpenCount int32  `json:"open_count"`
	Growth    int32  `json:"growth"`
}

// Ranked skills within one (category, country) scope; scoping is one-dimensional
// (either category or country carries a value, the other is ”), matching what the
// rollup materializes.
func (q *Queries) ListInsightsSkills(ctx context.Context, arg ListInsightsSkillsParams) ([]ListInsightsSkillsRow, error) {
	rows, err := q.db.Query(ctx, listInsightsSkills,
		arg.Category,
		arg.Country,
		arg.Sort,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsSkillsRow{}
	for rows.Next() {
		var i ListInsightsSkillsRow
		if err := rows.Scan(&i.Skill, &i.OpenCount, &i.Growth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightsVelocity = `-- name: ListInsightsVelocity :many
SELECT
    date_trunc($1::text, d)::date AS period,
    coalesce(sum(v.added), 0)::int   AS added,
    coalesce(sum(v.removed), 0)::int AS removed
FROM generate_series($2::timestamp, $3::timestamp, interval '1 day') AS d
LEFT JOIN insights_velocity_daily v
    ON v.day = d::date
   AND v.facet_kind = $4
   AND v.facet_value = $5
GROUP BY date_trunc($1::text, d)
ORDER BY date_trunc($1::text, d)
`

type ListInsightsVelocityParams struct {
	Unit       string           `json:"unit"`
	FromTs     pgtype.Timestamp `json:"from_ts"`
	ToTs       pgtype.Timestamp `json:"to_ts"`
	FacetKind  string           `json:"facet_kind"`
	FacetValue string           `json:"facet_value"`
}

type ListInsightsVelocityRow struct {
	Period  pgtype.Date `json:"period"`
	Added   int32       `json:"added"`
	Removed int32       `json:"removed"`
}

// Dense, gap-free added/removed series over [from_ts, to_ts] at @unit granularity
// for one facet slice. A daily generate_series fills missing days with zeros; @unit
// is a caller-validated date_trunc field (day/week/month).
func (q *Queries) ListInsightsVelocity(ctx context.Context, arg ListInsightsVelocityParams) ([]ListInsightsVelocityRow, error) {
	rows, err := q.db.Query(ctx, listInsightsVelocity,
		arg.Unit,
		arg.FromTs,
		arg.ToTs,
		arg.FacetKind,
		arg.FacetValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInsightsVelocityRow{}
	for rows.Next() {
		var i ListInsightsVelocityRow
		if err := rows.Scan(&i.Period, &i.Added, &i.Removed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneInsightsSkillHistory = `-- name: PruneInsightsSkillHistory :execrows
DELETE FROM insights_skill_history
WHERE week_start < $1::date
`

// Drops snapshot rows older than the retention window (~26 weeks), keeping
// the table bounded.
func (q *Queries) PruneInsightsSkillHistory(ctx context.Context, cutoff pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, pruneInsightsSkillHistory, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsCompanyGrowth = `-- name: RebuildInsightsCompanyGrowth :execrows
INSERT INTO insights_company_growth (company_slug, open_count, open_count_prev)
SELECT
    company_slug,
    count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
    count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
FROM jobs
WHERE company_slug <> '' AND duplicate_of IS NULL
GROUP BY company_slug
HAVING count(*) FILTER (WHERE closed_at IS NULL) > 0
    OR count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1)) > 0
`

// One row per company with its current open-count and the open-count as of @prev_ts,
// from a single scan of jobs over canonical rows only (same count(*) FILTER idiom as
// insights_role_stats). open_count uses closed_at IS NULL (open now); open_count_prev
// uses open-as-of @prev_ts. Companies open at neither point are dropped (HAVING) to
// keep the table lean.
func (q *Queries) RebuildInsightsCompanyGrowth(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsCompanyGrowth, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsCompanyResponse = `-- name: RebuildInsightsCompanyResponse :execrows
WITH observable AS (
    SELECT ae.application_id, ae.company_slug, ae.occurred_at AS applied_at
      FROM application_events ae
     WHERE ae.kind = 'applied'
       AND ae.retracted_at IS NULL
       AND ae.company_slug <> ''
       AND ae.application_id IS NOT NULL
       -- Observable means "we would have seen a reply": the candidate has somewhere we
       -- read mail. A Google grant with no mailbox address is a calendar-only consent —
       -- it can never produce an employer_reply, so counting it would put applications in
       -- the denominator that are structurally barred from the numerator and make named
       -- employers read as more silent than they are. That is the exact distortion this
       -- rollup exists to remove.
       AND (EXISTS (SELECT 1 FROM gmail_connections gc
                     WHERE gc.user_id = ae.user_id AND gc.status = 'connected' AND gc.email <> '')
         OR EXISTS (SELECT 1 FROM mailboxes mb WHERE mb.user_id = ae.user_id))
), answered AS (
    SELECT o.company_slug, o.applied_at,
           (SELECT min(r.occurred_at)
              FROM application_events r
             WHERE r.application_id = o.application_id
               AND r.kind          = 'employer_reply'
               AND r.retracted_at IS NULL) AS replied_at
      FROM observable o
)
INSERT INTO insights_company_response (company_slug, applications, answered, median_reply_days)
SELECT company_slug,
       count(*)::int,
       count(*) FILTER (WHERE replied_at IS NOT NULL)::int,
       percentile_cont(0.5) WITHIN GROUP (
           ORDER BY EXTRACT(EPOCH FROM (replied_at - applied_at)) / 86400.0
       ) FILTER (WHERE replied_at IS NOT NULL AND replied_at >= applied_at)::real
  FROM answered
 GROUP BY company_slug
`

// One row per company with an OBSERVABLE application: the applicant has a connected
// mailbox, so a reply would have been seen. Applications from people we cannot observe
// are excluded from BOTH sides of the ratio — counting them in the denominator would
// report our own blind spot as the employer's silence, which is the same mistake the
// job-level signal's mailbox gate exists to prevent.
//
// Both sides come from application_events, not from live mail. Reading the emails table
// made the served rate a function of the candidate's inbox hygiene: it counted messages
// WHERE deleted_at IS NULL, so someone clearing old mail made an employer that had
// answered them look silent, on a public page, about a named company. The ledger records
// that the reply arrived; what later became of the message is not the employer's doing.
//
// "Answered" is any live employer_reply event. Not a stage advance: a stage is what the
// candidate recorded, and a company that replied to somebody who never updated their
// board still replied. A retracted event does not count — it belongs to another employer.
//
// The reply is paired to its application through application_id, never through job_id.
// job_id is ON DELETE SET NULL, so after cmd/prune both sides read NULL, the pair reduces
// to NULL = NULL — never true — and an employer that answered is served as silent: the
// distortion this rollup was moved onto the ledger to remove, arriving by a different
// route. Pairing on (user_id, company_slug) instead would survive the deletion by
// crediting one reply to every application that user made to that employer, which is
// worse than losing it.
//
// An event with no application_id is left out of BOTH sides rather than counted and never
// answerable. Only rows written before the carry-over can be in that state, and
// cmd/backfill-applications is what empties it.
//
// The median covers answered applications only and is therefore right-censored; the
// serving layer reports the unanswered count beside it so the number is never read as
// "employers reply in six days" when most of the sample was never replied to. Replies
// dated before their application (an application reconstructed from a later message, or
// clock skew) still count as answered but are kept out of the median, where they would
// contribute a negative duration.
func (q *Queries) RebuildInsightsCompanyResponse(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsCompanyResponse)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsCompanyStats = `-- name: RebuildInsightsCompanyStats :execrows
INSERT INTO insights_company_stats (company_slug, day, added, removed, open)
SELECT
    company_slug,
    day,
    added,
    removed,
    sum(added - removed) OVER (PARTITION BY company_slug ORDER BY day)::int AS open
FROM (
    SELECT j.company_slug, day, sum(added)::int AS added, sum(removed)::int AS removed
    FROM jobs j
    CROSS JOIN LATERAL (
        -- Added event on the created_at day; removed event on the closed_at day.
        SELECT (j.created_at AT TIME ZONE 'UTC')::date AS day, 1 AS added, 0 AS removed
        UNION ALL
        SELECT (j.closed_at AT TIME ZONE 'UTC')::date, 0, 1
        WHERE j.closed_at IS NOT NULL
    ) e
    WHERE j.company_slug <> '' AND j.duplicate_of IS NULL
    GROUP BY j.company_slug, day
) daily
`

// Per-(company, day) hiring velocity with a running open count, from the retained
// jobs lifecycle. Each canonical, attributable job (company_slug <> ” AND
// duplicate_of IS NULL) emits an added event on its created_at (UTC) day and, if
// closed, a removed event on its closed_at (UTC) day; the inner aggregate collapses
// those to one row per (company_slug, day), and the window SUM over (added - removed)
// ordered by day yields open = cumulative(added) - cumulative(removed) as of that day
// (a job is created no later than it closes, so this equals the point-in-time open
// count). Only a company's activity days get a row.
func (q *Queries) RebuildInsightsCompanyStats(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsCompanyStats)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsRoleStatsByCountry = `-- name: RebuildInsightsRoleStatsByCountry :execrows
INSERT INTO insights_role_stats (category, seniority, country, open_count, open_count_prev)
SELECT category, seniority, country, open_count, open_count_prev
FROM (
    SELECT
        category,
        seniority,
        country,
        count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
        count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
    FROM jobs, unnest(countries) AS country
    WHERE category <> '' AND seniority <> ''
    GROUP BY category, seniority, country
) t
WHERE open_count > 0 OR open_count_prev > 0
`

// Per-country role demand: a job contributes once to each of its countries.
func (q *Queries) RebuildInsightsRoleStatsByCountry(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsRoleStatsByCountry, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsRoleStatsGlobal = `-- name: RebuildInsightsRoleStatsGlobal :execrows
INSERT INTO insights_role_stats (category, seniority, country, open_count, open_count_prev)
SELECT category, seniority, '', open_count, open_count_prev
FROM (
    SELECT
        category,
        seniority,
        count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
        count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
    FROM jobs
    WHERE category <> '' AND seniority <> ''
    GROUP BY category, seniority
) t
WHERE open_count > 0 OR open_count_prev > 0
`

// Country-agnostic (” bucket) role demand. open_count = jobs open now
// (closed_at IS NULL); open_count_prev = jobs open as of @prev_ts. The inner
// aggregate is wrapped so the "non-zero in either window" filter names the counts
// once instead of repeating the FILTER expressions in a HAVING.
func (q *Queries) RebuildInsightsRoleStatsGlobal(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsRoleStatsGlobal, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsSalaryStatsByCountry = `-- name: RebuildInsightsSalaryStatsByCountry :execrows
INSERT INTO insights_salary_stats (category, seniority, country, currency, period, sample_size, p25, p50, p75)
SELECT
    coalesce(category, ''),
    coalesce(seniority, ''),
    country,
    currency,
    period,
    count(*)::int,
    percentile_cont(0.25) WITHIN GROUP (ORDER BY sal)::int,
    percentile_cont(0.50) WITHIN GROUP (ORDER BY sal)::int,
    percentile_cont(0.75) WITHIN GROUP (ORDER BY sal)::int
FROM (
    SELECT
        category,
        seniority,
        country,
        upper(enrichment->>'salary_currency') AS currency,
        enrichment->>'salary_period'   AS period,
        coalesce(
            (nullif(enrichment->>'salary_min', '')::numeric + nullif(enrichment->>'salary_max', '')::numeric) / 2,
            nullif(enrichment->>'salary_min', '')::numeric,
            nullif(enrichment->>'salary_max', '')::numeric
        ) AS sal
    FROM jobs, unnest(countries) AS country
    WHERE closed_at IS NULL
      AND category <> '' AND seniority <> ''
      AND coalesce(enrichment->>'salary_currency', '') <> ''
      AND coalesce(enrichment->>'salary_period', '') <> ''
) s
WHERE sal IS NOT NULL
GROUP BY country, currency, period, CUBE(category, seniority)
HAVING count(*) >= $1::int
`

// Per-country salary bands (same CUBE of role scope, country from unnest).
func (q *Queries) RebuildInsightsSalaryStatsByCountry(ctx context.Context, minSample int32) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsSalaryStatsByCountry, minSample)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsSalaryStatsGlobal = `-- name: RebuildInsightsSalaryStatsGlobal :execrows
INSERT INTO insights_salary_stats (category, seniority, country, currency, period, sample_size, p25, p50, p75)
SELECT
    coalesce(category, ''),
    coalesce(seniority, ''),
    '',
    currency,
    period,
    count(*)::int,
    percentile_cont(0.25) WITHIN GROUP (ORDER BY sal)::int,
    percentile_cont(0.50) WITHIN GROUP (ORDER BY sal)::int,
    percentile_cont(0.75) WITHIN GROUP (ORDER BY sal)::int
FROM (
    SELECT
        category,
        seniority,
        upper(enrichment->>'salary_currency') AS currency,
        enrichment->>'salary_period'   AS period,
        coalesce(
            (nullif(enrichment->>'salary_min', '')::numeric + nullif(enrichment->>'salary_max', '')::numeric) / 2,
            nullif(enrichment->>'salary_min', '')::numeric,
            nullif(enrichment->>'salary_max', '')::numeric
        ) AS sal
    FROM jobs
    WHERE closed_at IS NULL
      AND category <> '' AND seniority <> ''
      AND coalesce(enrichment->>'salary_currency', '') <> ''
      AND coalesce(enrichment->>'salary_period', '') <> ''
) s
WHERE sal IS NOT NULL
GROUP BY currency, period, CUBE(category, seniority)
HAVING count(*) >= $1::int
`

// Country-agnostic salary bands. CUBE(category, seniority) emits every scope the
// endpoint can ask for — the exact (category, seniority) band, the category-only
// band (seniority ”), the seniority-only band (category ”), and the overall band
// (both ”) — all per (currency, period), which is never aggregated across. The
// representative figure per job is the min/max midpoint (or whichever bound is
// present). Only bands at/above @min_sample are stored.
func (q *Queries) RebuildInsightsSalaryStatsGlobal(ctx context.Context, minSample int32) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsSalaryStatsGlobal, minSample)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsSkillStatsByCategory = `-- name: RebuildInsightsSkillStatsByCategory :execrows
INSERT INTO insights_skill_stats (skill, category, country, open_count, open_count_prev)
SELECT skill, category, '', open_count, open_count_prev
FROM (
    SELECT
        skill,
        category,
        count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
        count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
    FROM jobs, unnest(skills) AS skill
    WHERE category <> ''
    GROUP BY skill, category
) t
WHERE open_count > 0 OR open_count_prev > 0
`

// Per-category skill demand (country ” bucket).
func (q *Queries) RebuildInsightsSkillStatsByCategory(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsSkillStatsByCategory, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsSkillStatsByCountry = `-- name: RebuildInsightsSkillStatsByCountry :execrows
INSERT INTO insights_skill_stats (skill, category, country, open_count, open_count_prev)
SELECT skill, '', country, open_count, open_count_prev
FROM (
    SELECT
        skill,
        country,
        count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
        count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
    FROM jobs, unnest(skills) AS skill, unnest(countries) AS country
    GROUP BY skill, country
) t
WHERE open_count > 0 OR open_count_prev > 0
`

// Per-country skill demand (category ” bucket).
func (q *Queries) RebuildInsightsSkillStatsByCountry(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsSkillStatsByCountry, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsSkillStatsGlobal = `-- name: RebuildInsightsSkillStatsGlobal :execrows
INSERT INTO insights_skill_stats (skill, category, country, open_count, open_count_prev)
SELECT skill, '', '', open_count, open_count_prev
FROM (
    SELECT
        skill,
        count(*) FILTER (WHERE closed_at IS NULL)::int AS open_count,
        count(*) FILTER (WHERE created_at <= $1 AND (closed_at IS NULL OR closed_at > $1))::int AS open_count_prev
    FROM jobs, unnest(skills) AS skill
    GROUP BY skill
) t
WHERE open_count > 0 OR open_count_prev > 0
`

// Country- and category-agnostic skill demand (both ” buckets).
func (q *Queries) RebuildInsightsSkillStatsGlobal(ctx context.Context, prevTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsSkillStatsGlobal, prevTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildInsightsVelocityDaily = `-- name: RebuildInsightsVelocityDaily :execrows
INSERT INTO insights_velocity_daily (day, facet_kind, facet_value, added, removed)
SELECT day, facet_kind, facet_value, sum(added)::int, sum(removed)::int
FROM jobs j
CROSS JOIN LATERAL (
    -- Added events (created_at day), scalar facet axes.
    SELECT (j.created_at AT TIME ZONE 'UTC')::date AS day, f.fk AS facet_kind, f.fv AS facet_value, 1 AS added, 0 AS removed
    FROM (VALUES ('all', ''), ('category', j.category), ('seniority', j.seniority)) AS f(fk, fv)
    WHERE f.fk = 'all' OR f.fv <> ''
    UNION ALL
    -- Added events, per country.
    SELECT (j.created_at AT TIME ZONE 'UTC')::date, 'country', c, 1, 0
    FROM unnest(j.countries) AS c
    UNION ALL
    -- Removed events (closed_at day), scalar facet axes — only for closed jobs.
    SELECT (j.closed_at AT TIME ZONE 'UTC')::date, f.fk, f.fv, 0, 1
    FROM (VALUES ('all', ''), ('category', j.category), ('seniority', j.seniority)) AS f(fk, fv)
    WHERE j.closed_at IS NOT NULL AND (f.fk = 'all' OR f.fv <> '')
    UNION ALL
    -- Removed events, per country.
    SELECT (j.closed_at AT TIME ZONE 'UTC')::date, 'country', c, 0, 1
    FROM unnest(j.countries) AS c
    WHERE j.closed_at IS NOT NULL
) e
GROUP BY day, facet_kind, facet_value
`

// Faceted added/removed-per-day rollup from a SINGLE scan of jobs: a CROSS JOIN
// LATERAL expands each job into its events instead of the previous 8 separate
// full-table scans (one per facet axis × added/removed), which at catalogue scale
// dominated the recompute. Per job the lateral emits: added events on the
// created_at day and (if closed) removed events on the closed_at day, across the
// 'all', category, seniority, and country (unnest) axes. Days are UTC calendar
// dates; the outer GROUP BY aggregates per (day, facet_kind, facet_value).
func (q *Queries) RebuildInsightsVelocityDaily(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildInsightsVelocityDaily)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotInsightsSkillHistory = `-- name: SnapshotInsightsSkillHistory :execrows

INSERT INTO insights_skill_history (skill, week_start, open_count)
SELECT skill, $1::date, open_count
FROM insights_skill_stats
WHERE category = '' AND country = ''
ON CONFLICT (skill, week_start) DO NOTHING
`

// ---------------------------------------------------------------------------
// Skill demand history (the personal GET /me/market-pulse read)
// ---------------------------------------------------------------------------
// Appends this ISO week's global (category=”, country=”) skill open-counts
// to the history table, reading the rollup this same transaction just
// rebuilt rather than re-aggregating jobs. ON CONFLICT DO NOTHING is what
// makes this safe to call on every intra-day rollup-stats run: only the
// first run of a given week actually inserts, every later run this week is
// a no-op.
func (q *Queries) SnapshotInsightsSkillHistory(ctx context.Context, weekStart pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, snapshotInsightsSkillHistory, weekStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
