// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeJobByID = `-- name: CloseJobByID :execrows
UPDATE jobs
SET closed_at  = now(),
    updated_at = now()
WHERE id = $1 AND closed_at IS NULL
`

// Soft-close one job now (see job-lifecycle): a moderator resolving a report with
// close_job=true. The third writer of closed_at, alongside the ingest sweep and the
// liveness probe. WHERE closed_at IS NULL keeps it idempotent — a second close on an
// already-closed job is a no-op, never an error, so it never fights the report's own
// status guard. A later ingest upsert may legitimately reopen a board job (reopen-on-
// reappear); that is the lifecycle's existing behavior, not a conflict.
func (q *Queries) CloseJobByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, closeJobByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeJobBySourceExternalID = `-- name: CloseJobBySourceExternalID :execrows
UPDATE jobs
SET closed_at  = now(),
    updated_at = now()
WHERE closed_at IS NULL
  AND source = $1
  AND external_id = $2
`

type CloseJobBySourceExternalIDParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

// Stream-driven close (see job-lifecycle): a self-closing feed source (e.g. jobtech)
// learns of a removed posting from its incremental stream and closes it by identity,
// rather than relying on the post-run unseen sweep (which it opts out of, since an
// incremental stream re-reports only changed ads and so never refreshes last_seen_at
// for the still-open ones). WHERE closed_at IS NULL keeps it idempotent; a later
// upsert of the same (source, external_id) reopens it if the posting reappears.
func (q *Queries) CloseJobBySourceExternalID(ctx context.Context, arg CloseJobBySourceExternalIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeJobBySourceExternalID, arg.Source, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeUnseenJobs = `-- name: CloseUnseenJobs :execrows
UPDATE jobs
SET closed_at  = now(),
    updated_at = now()
WHERE closed_at IS NULL
  AND source = $1
  AND last_seen_at < $2
`

type CloseUnseenJobsParams struct {
	Source string             `json:"source"`
	Cutoff pgtype.Timestamptz `json:"cutoff"`
}

// Post-ingest sweep (see job-lifecycle spec): close every open job of ONE source not
// seen since the cutoff. Scoped by source because ingest runs per provider — a
// greenhouse run must not close jobs another provider owns and didn't crawl. The
// caller owns the grace window (cutoff = now() - window) and the "run ingested
// something" guard, so a failed crawl never mass-closes that source's catalogue.
func (q *Queries) CloseUnseenJobs(ctx context.Context, arg CloseUnseenJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeUnseenJobs, arg.Source, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM jobs
WHERE closed_at IS NULL
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJobEnrichment = `-- name: EnqueueJobEnrichment :execrows
INSERT INTO enrichment_outbox (job_id, target_version)
SELECT id, $1::int
FROM jobs
WHERE id = $2::bigint
  AND (enriched_at IS NULL OR enrichment_version < $1::int)
ON CONFLICT (job_id, target_version) DO NOTHING
`

type EnqueueJobEnrichmentParams struct {
	TargetVersion int32 `json:"target_version"`
	JobID         int64 `json:"job_id"`
}

// Transactional-outbox enqueue for the ingest write path: queue this one job for
// enrichment, gated on the same condition the backfill uses (unenriched or below the
// target schema version), so an already-enriched job is not re-queued. Idempotent via
// the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
// job's UpsertJob so a newly ingested job is queued atomically with its write.
func (q *Queries) EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJobEnrichment, arg.TargetVersion, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.Countries,
		&i.Regions,
		&i.WorkMode,
		&i.LivenessStrikes,
		&i.Skills,
		&i.Seniority,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.PostingLanguage,
		&i.EmploymentType,
		&i.EducationLevel,
		&i.ExperienceYearsMin,
		&i.Collections,
		&i.ContentHash,
		&i.RemoteUnspecified,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE public_slug = $1
`

func (q *Queries) GetJobBySlug(ctx context.Context, publicSlug string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobBySlug, publicSlug)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.Countries,
		&i.Regions,
		&i.WorkMode,
		&i.LivenessStrikes,
		&i.Skills,
		&i.Seniority,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.PostingLanguage,
		&i.EmploymentType,
		&i.EducationLevel,
		&i.ExperienceYearsMin,
		&i.Collections,
		&i.ContentHash,
		&i.RemoteUnspecified,
	)
	return i, err
}

const getJobIDBySlug = `-- name: GetJobIDBySlug :one
SELECT id
FROM jobs
WHERE public_slug = $1
`

// Slim slug->id lookup for the view/apply interaction path, which needs only the
// internal id (the user_jobs FK) and must not drag the wide description/enrichment
// columns over the wire on every silent view. GetJobBySlug (SELECT *) stays for the
// public detail handler that renders the whole row.
func (q *Queries) GetJobIDBySlug(ctx context.Context, publicSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, getJobIDBySlug, publicSlug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const jobSitemapBoundaries = `-- name: JobSitemapBoundaries :many
SELECT id FROM (
  SELECT id,
         row_number() OVER (ORDER BY id) AS rn,
         count(*) OVER () AS total
  FROM jobs
  WHERE closed_at IS NULL
) t
WHERE rn % $1::bigint = 0 AND rn < total
ORDER BY id
`

// The id ending every full chunk of `chunk_size` open jobs (ordered by id),
// excluding the final row, so the sitemap index can list each sub-sitemap's keyset
// cursor without the client walking the whole catalogue.
func (q *Queries) JobSitemapBoundaries(ctx context.Context, chunkSize int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, jobSitemapBoundaries, chunkSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobSitemap = `-- name: ListJobSitemap :many
SELECT id, public_slug, updated_at
FROM jobs
WHERE closed_at IS NULL AND id > $1
ORDER BY id
LIMIT $2
`

type ListJobSitemapParams struct {
	AfterID   int64 `json:"after_id"`
	BatchSize int32 `json:"batch_size"`
}

type ListJobSitemapRow struct {
	ID         int64              `json:"id"`
	PublicSlug string             `json:"public_slug"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Slim keyset page for the sitemap: only the fields a sitemap URL needs, open jobs
// only, cursored by the immutable primary key so a chunk is a bounded index scan
// (never a deep OFFSET over millions of rows).
func (q *Queries) ListJobSitemap(ctx context.Context, arg ListJobSitemapParams) ([]ListJobSitemapRow, error) {
	rows, err := q.db.Query(ctx, listJobSitemap, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobSitemapRow{}
	for rows.Next() {
		var i ListJobSitemapRow
		if err := rows.Scan(&i.ID, &i.PublicSlug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE closed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Newest-added first: created_at is when the job entered the catalogue (stable
// across re-ingests), so fresh ingests surface on top regardless of how old the
// platform's posted_at is. id breaks ties within one ingest batch.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Countries,
			&i.Regions,
			&i.WorkMode,
			&i.LivenessStrikes,
			&i.Skills,
			&i.Seniority,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.PostingLanguage,
			&i.EmploymentType,
			&i.EducationLevel,
			&i.ExperienceYearsMin,
			&i.Collections,
			&i.ContentHash,
			&i.RemoteUnspecified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCompany = `-- name: ListJobsByCompany :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE company_slug = $1 AND closed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListJobsByCompanyParams struct {
	CompanySlug string `json:"company_slug"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCompany, arg.CompanySlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Countries,
			&i.Regions,
			&i.WorkMode,
			&i.LivenessStrikes,
			&i.Skills,
			&i.Seniority,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.PostingLanguage,
			&i.EmploymentType,
			&i.EducationLevel,
			&i.ExperienceYearsMin,
			&i.Collections,
			&i.ContentHash,
			&i.RemoteUnspecified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByIDAfter = `-- name: ListJobsByIDAfter :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListJobsByIDAfterParams struct {
	AfterID   int64 `json:"after_id"`
	BatchSize int32 `json:"batch_size"`
}

// Keyset scan for the reindex command: pages by the immutable primary key, so
// concurrent inserts/updates (which shift posted_at ordering) cannot make the
// scan skip or repeat rows the way OFFSET pagination would.
func (q *Queries) ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByIDAfter, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Countries,
			&i.Regions,
			&i.WorkMode,
			&i.LivenessStrikes,
			&i.Skills,
			&i.Seniority,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.PostingLanguage,
			&i.EmploymentType,
			&i.EducationLevel,
			&i.ExperienceYearsMin,
			&i.Collections,
			&i.ContentHash,
			&i.RemoteUnspecified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsUpdatedAfter = `-- name: ListJobsUpdatedAfter :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
FROM jobs
WHERE id > $1 AND updated_at >= $2
ORDER BY id
LIMIT $3
`

type ListJobsUpdatedAfterParams struct {
	AfterID   int64              `json:"after_id"`
	Since     pgtype.Timestamptz `json:"since"`
	BatchSize int32              `json:"batch_size"`
}

// Incremental keyset scan for `reindex --since`: like ListJobsByIDAfter but only
// rows changed at or after the cutoff. Every write path (UpsertJob, the close
// sweeps, SetJobEnrichment, UpdateJobFacets) stamps updated_at = now(), so this
// captures new, re-crawled, closed, and re-enriched jobs — enough to bring an
// index current without re-pushing the whole table. Returns closed rows too, so
// the caller deletes a freshly-closed job from the index.
func (q *Queries) ListJobsUpdatedAfter(ctx context.Context, arg ListJobsUpdatedAfterParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsUpdatedAfter, arg.AfterID, arg.Since, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Countries,
			&i.Regions,
			&i.WorkMode,
			&i.LivenessStrikes,
			&i.Skills,
			&i.Seniority,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.PostingLanguage,
			&i.EmploymentType,
			&i.EducationLevel,
			&i.ExperienceYearsMin,
			&i.Collections,
			&i.ContentHash,
			&i.RemoteUnspecified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLivenessExpired = `-- name: MarkLivenessExpired :one
UPDATE jobs
SET liveness_strikes = liveness_strikes + 1,
    closed_at = CASE
        WHEN liveness_strikes + 1 >= $1 THEN now()
        ELSE closed_at
    END,
    updated_at = now()
WHERE id = $2
RETURNING id, liveness_strikes, closed_at
`

type MarkLivenessExpiredParams struct {
	Threshold int32 `json:"threshold"`
	ID        int64 `json:"id"`
}

type MarkLivenessExpiredRow struct {
	ID              int64              `json:"id"`
	LivenessStrikes int32              `json:"liveness_strikes"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
}

// Record one expired probe: increment the strike counter and, in the same write,
// close the job (closed_at) once it reaches the threshold the caller owns — the
// two-strike grace that absorbs a transient death signal. Returns the new strike
// count and closed_at so the worker can log the outcome.
func (q *Queries) MarkLivenessExpired(ctx context.Context, arg MarkLivenessExpiredParams) (MarkLivenessExpiredRow, error) {
	row := q.db.QueryRow(ctx, markLivenessExpired, arg.Threshold, arg.ID)
	var i MarkLivenessExpiredRow
	err := row.Scan(&i.ID, &i.LivenessStrikes, &i.ClosedAt)
	return i, err
}

const propagateCollectionsToJobs = `-- name: PropagateCollectionsToJobs :execrows
UPDATE jobs
SET collections = c.collections,
    updated_at  = now()
FROM companies c
WHERE jobs.company_slug = c.slug
  AND jobs.collections IS DISTINCT FROM c.collections
`

// Denormalize each company's curated-collection set onto its jobs, so the search
// facet (jobs.collections) reflects current membership. Run by cmd/import-collections
// after it writes companies.collections. updated_at is bumped so `reindex --since`
// picks the changed rows up; the IS DISTINCT FROM guard skips unchanged rows, making
// re-runs idempotent and cheap.
func (q *Queries) PropagateCollectionsToJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, propagateCollectionsToJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetLivenessStrikes = `-- name: ResetLivenessStrikes :exec
UPDATE jobs
SET liveness_strikes = 0
WHERE id = $1 AND liveness_strikes <> 0
`

// A healthy (not-expired) probe clears any accumulated strikes, so only CONSECUTIVE
// expired probes can close a job. Guarded to the non-zero case so probing an
// already-clean job does not churn the row.
func (q *Queries) ResetLivenessStrikes(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetLivenessStrikes, id)
	return err
}

const selectOrphanLivenessCandidates = `-- name: SelectOrphanLivenessCandidates :many
SELECT id, source, url, public_slug, liveness_strikes
FROM jobs
WHERE closed_at IS NULL
  AND source <> ALL($1::text[])
`

type SelectOrphanLivenessCandidatesRow struct {
	ID              int64  `json:"id"`
	Source          string `json:"source"`
	URL             string `json:"url"`
	PublicSlug      string `json:"public_slug"`
	LivenessStrikes int32  `json:"liveness_strikes"`
}

// Orphan-job liveness (probe-orphan-job-liveness): open jobs whose source is NOT a
// registered ATS board provider — the sources no ingest run re-crawls and the sweep
// therefore never closes (telegram, habr_career, geekjob, …). The caller passes the
// ATS provider set from the sources registry; <> ALL excludes them, so a new adapter
// never silently becomes a probe target. Closed jobs are skipped (already not open).
func (q *Queries) SelectOrphanLivenessCandidates(ctx context.Context, atsProviders []string) ([]SelectOrphanLivenessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, selectOrphanLivenessCandidates, atsProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectOrphanLivenessCandidatesRow{}
	for rows.Next() {
		var i SelectOrphanLivenessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.URL,
			&i.PublicSlug,
			&i.LivenessStrikes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobEnrichment = `-- name: SetJobEnrichment :exec
UPDATE jobs
SET enrichment         = $1,
    enriched_at        = $2,
    enrichment_version = $3,
    updated_at         = now()
WHERE id = $4
`

type SetJobEnrichmentParams struct {
	Enrichment        json.RawMessage    `json:"enrichment"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion int32              `json:"enrichment_version"`
	ID                int64              `json:"id"`
}

// Targeted enrichment write used by the enrichment command: set only the payload
// and the provenance stamp, touching no raw source field. Kept separate from
// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
func (q *Queries) SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error {
	_, err := q.db.Exec(ctx, setJobEnrichment,
		arg.Enrichment,
		arg.EnrichedAt,
		arg.EnrichmentVersion,
		arg.ID,
	)
	return err
}

const updateJobFacets = `-- name: UpdateJobFacets :exec
UPDATE jobs
SET countries = COALESCE($1::text[], '{}'),
    regions   = COALESCE($2::text[], '{}'),
    work_mode = $3,
    skills    = COALESCE($4::text[], '{}'),
    seniority = $5,
    category  = $6,
    posting_language     = $7,
    employment_type      = $8,
    education_level      = $9,
    experience_years_min = $10,
    remote_unspecified   = $11
WHERE id = $12
`

type UpdateJobFacetsParams struct {
	Countries          []string    `json:"countries"`
	Regions            []string    `json:"regions"`
	WorkMode           string      `json:"work_mode"`
	Skills             []string    `json:"skills"`
	Seniority          string      `json:"seniority"`
	Category           string      `json:"category"`
	PostingLanguage    string      `json:"posting_language"`
	EmploymentType     string      `json:"employment_type"`
	EducationLevel     string      `json:"education_level"`
	ExperienceYearsMin pgtype.Int4 `json:"experience_years_min"`
	RemoteUnspecified  bool        `json:"remote_unspecified"`
	ID                 int64       `json:"id"`
}

// One-off backfill (cmd/backfill-derive): rewrite every deterministic dictionary
// facet column — countries, regions, work_mode, skills, seniority, category, plus the
// synthetic enrichment facets posting_language, employment_type, education_level,
// experience_years_min, and remote_unspecified — from the row's raw content
// (title/location/description) in one
// pass, replacing the
// three separate per-facet backfill writes. The facets are a pure function of the
// raw fields, so this is idempotent. updated_at is deliberately left untouched
// (like UpdateJobSlugs) so a backfill does not churn every row's timestamp. COALESCE
// maps a nil array arg to '{}' for the NOT NULL array columns. work_mode is written
// as given by the caller, which preserves an already-set (possibly
// adapter-structured) value.
func (q *Queries) UpdateJobFacets(ctx context.Context, arg UpdateJobFacetsParams) error {
	_, err := q.db.Exec(ctx, updateJobFacets,
		arg.Countries,
		arg.Regions,
		arg.WorkMode,
		arg.Skills,
		arg.Seniority,
		arg.Category,
		arg.PostingLanguage,
		arg.EmploymentType,
		arg.EducationLevel,
		arg.ExperienceYearsMin,
		arg.RemoteUnspecified,
		arg.ID,
	)
	return err
}

const updateJobSlugs = `-- name: UpdateJobSlugs :exec
UPDATE jobs
SET public_slug  = $1,
    company_slug = $2
WHERE id = $3
`

type UpdateJobSlugsParams struct {
	PublicSlug  string `json:"public_slug"`
	CompanySlug string `json:"company_slug"`
	ID          int64  `json:"id"`
}

// One-off backfill for a deliberate slug-builder change (see the UpsertJob note on
// why slugs are otherwise immutable). public_slug/company_slug are deterministic
// from the row's immutable fields, so recomputing and rewriting them is idempotent.
func (q *Queries) UpdateJobSlugs(ctx context.Context, arg UpdateJobSlugsParams) error {
	_, err := q.db.Exec(ctx, updateJobSlugs, arg.PublicSlug, arg.CompanySlug, arg.ID)
	return err
}

const updateManualJob = `-- name: UpdateManualJob :one
WITH company_upsert AS (
    INSERT INTO companies (slug, name)
    SELECT $3, $2
    WHERE $3 <> ''
    ON CONFLICT (slug) DO UPDATE SET
        name       = EXCLUDED.name,
        updated_at = now()
)
UPDATE jobs
SET title        = $1,
    company      = $2,
    company_slug = $3,
    location     = $4,
    remote       = $5,
    description  = $6,
    posted_at    = $7,
    countries    = COALESCE($8::text[], '{}'),
    regions      = COALESCE($9::text[], '{}'),
    work_mode    = $10,
    skills       = COALESCE($11::text[], '{}'),
    seniority    = $12,
    category     = $13,
    posting_language     = $14,
    employment_type      = $15,
    education_level      = $16,
    experience_years_min = $17,
    remote_unspecified   = $18,
    updated_by   = $19::bigint,
    updated_at   = now()
WHERE public_slug = $20 AND created_by IS NOT NULL
RETURNING id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
`

type UpdateManualJobParams struct {
	Title              string             `json:"title"`
	Company            string             `json:"company"`
	CompanySlug        string             `json:"company_slug"`
	Location           string             `json:"location"`
	Remote             bool               `json:"remote"`
	Description        string             `json:"description"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	Countries          []string           `json:"countries"`
	Regions            []string           `json:"regions"`
	WorkMode           string             `json:"work_mode"`
	Skills             []string           `json:"skills"`
	Seniority          string             `json:"seniority"`
	Category           string             `json:"category"`
	PostingLanguage    string             `json:"posting_language"`
	EmploymentType     string             `json:"employment_type"`
	EducationLevel     string             `json:"education_level"`
	ExperienceYearsMin pgtype.Int4        `json:"experience_years_min"`
	RemoteUnspecified  bool               `json:"remote_unspecified"`
	UpdatedBy          int64              `json:"updated_by"`
	PublicSlug         string             `json:"public_slug"`
}

// Moderator edit of a hand-curated job, addressed by public_slug and scoped to
// created_by IS NOT NULL so this path can only rewrite a moderator-authored posting,
// never an automated-source (ingest/telegram) one — regardless of the declared source.
// The partial merge (nil = unchanged) and facet re-derivation happen in the service; this
// query writes the resulting full field set, so geography/skills/company_slug stay
// consistent with the edited content. The source identity (url/external_id/public_slug)
// is deliberately NOT updatable here. The company row is upserted when a slug is present,
// so "a company's jobs" stays resolvable. updated_by records the acting moderator. Returns
// no row when the slug is missing or not a manual job (the caller maps that to 404).
// closed_at is deliberately NOT touched: an edit is a content fix, not a lifecycle change.
// Reopening a closed posting is the re-create (same-URL UpsertManualJob) path's job, so a
// content edit never resurrects a job the sweep/liveness worker closed.
func (q *Queries) UpdateManualJob(ctx context.Context, arg UpdateManualJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateManualJob,
		arg.Title,
		arg.Company,
		arg.CompanySlug,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.Countries,
		arg.Regions,
		arg.WorkMode,
		arg.Skills,
		arg.Seniority,
		arg.Category,
		arg.PostingLanguage,
		arg.EmploymentType,
		arg.EducationLevel,
		arg.ExperienceYearsMin,
		arg.RemoteUnspecified,
		arg.UpdatedBy,
		arg.PublicSlug,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.Countries,
		&i.Regions,
		&i.WorkMode,
		&i.LivenessStrikes,
		&i.Skills,
		&i.Seniority,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.PostingLanguage,
		&i.EmploymentType,
		&i.EducationLevel,
		&i.ExperienceYearsMin,
		&i.Collections,
		&i.ContentHash,
		&i.RemoteUnspecified,
	)
	return i, err
}

const upsertJob = `-- name: UpsertJob :one
WITH existing AS (
    SELECT content_hash AS old_hash, true AS existed FROM jobs
    WHERE source = $1 AND external_id = $2
),
company_upsert AS (
    INSERT INTO companies (slug, name)
    SELECT $6, $5
    WHERE $6 <> ''
    ON CONFLICT (slug) DO UPDATE SET
        name       = EXCLUDED.name,
        updated_at = now()
)
INSERT INTO jobs (
    source, external_id, url, title, company, company_slug, location, remote, description, posted_at,
    public_slug, countries, regions, work_mode, skills, seniority, category,
    posting_language, employment_type, education_level, experience_years_min,
    remote_unspecified, content_hash
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11,
    COALESCE($12::text[], '{}'), COALESCE($13::text[], '{}'),
    $14, COALESCE($15::text[], '{}'), $16, $17,
    $18, $19, $20, $21,
    $22, $23
)
ON CONFLICT (source, external_id) DO UPDATE SET
    url          = EXCLUDED.url,
    title        = EXCLUDED.title,
    company      = EXCLUDED.company,
    company_slug = EXCLUDED.company_slug,
    location     = EXCLUDED.location,
    remote       = EXCLUDED.remote,
    description  = EXCLUDED.description,
    posted_at    = EXCLUDED.posted_at,
    countries    = EXCLUDED.countries,
    regions      = EXCLUDED.regions,
    work_mode    = EXCLUDED.work_mode,
    skills       = EXCLUDED.skills,
    seniority    = EXCLUDED.seniority,
    category     = EXCLUDED.category,
    posting_language     = EXCLUDED.posting_language,
    employment_type      = EXCLUDED.employment_type,
    education_level      = EXCLUDED.education_level,
    experience_years_min = EXCLUDED.experience_years_min,
    remote_unspecified   = EXCLUDED.remote_unspecified,
    content_hash = EXCLUDED.content_hash,
    -- The crawl saw the posting: refresh liveness and reopen if it was closed.
    last_seen_at = now(),
    closed_at    = NULL,
    updated_at   = now()
RETURNING jobs.id, jobs.source, jobs.external_id, jobs.url, jobs.title, jobs.company, jobs.location, jobs.remote, jobs.description, jobs.posted_at, jobs.created_at, jobs.updated_at, jobs.company_slug, jobs.enrichment, jobs.enriched_at, jobs.enrichment_version, jobs.public_slug, jobs.last_seen_at, jobs.closed_at, jobs.countries, jobs.regions, jobs.work_mode, jobs.liveness_strikes, jobs.skills, jobs.seniority, jobs.category, jobs.created_by, jobs.updated_by, jobs.posting_language, jobs.employment_type, jobs.education_level, jobs.experience_years_min, jobs.collections, jobs.content_hash, jobs.remote_unspecified,
    NOT COALESCE((SELECT existed FROM existing), false) AS inserted,
    ((SELECT old_hash FROM existing) IS DISTINCT FROM $23) AS changed
`

type UpsertJobParams struct {
	Source             string             `json:"source"`
	ExternalID         string             `json:"external_id"`
	URL                string             `json:"url"`
	Title              string             `json:"title"`
	Company            string             `json:"company"`
	CompanySlug        string             `json:"company_slug"`
	Location           string             `json:"location"`
	Remote             bool               `json:"remote"`
	Description        string             `json:"description"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	PublicSlug         string             `json:"public_slug"`
	Countries          []string           `json:"countries"`
	Regions            []string           `json:"regions"`
	WorkMode           string             `json:"work_mode"`
	Skills             []string           `json:"skills"`
	Seniority          string             `json:"seniority"`
	Category           string             `json:"category"`
	PostingLanguage    string             `json:"posting_language"`
	EmploymentType     string             `json:"employment_type"`
	EducationLevel     string             `json:"education_level"`
	ExperienceYearsMin pgtype.Int4        `json:"experience_years_min"`
	RemoteUnspecified  bool               `json:"remote_unspecified"`
	ContentHash        pgtype.Text        `json:"content_hash"`
}

type UpsertJobRow struct {
	Job      Job         `json:"job"`
	Inserted pgtype.Bool `json:"inserted"`
	Changed  bool        `json:"changed"`
}

// Single atomic write: upsert the company (only when the slug is non-empty,
// via the WHERE on the SELECT) and the job together, keeping the "one write =
// one job" property of the pipeline's write path.
// The enrichment columns are deliberately NOT written here: ingest carries no
// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
// enrichment worker) is the sole writer of those columns.
// countries/regions ARE written here: they are source facts parsed from the
// location, not enrichment. COALESCE maps a nil arg to '{}', so a location that
// yields no geography stores empty arrays (the columns are NOT NULL).
// content_hash is the incremental-index change signal (internal/jobhash): the
// `existing` CTE captures the row's pre-update hash (snapshot from before this
// statement), so RETURNING can report whether the write inserted a new row
// (`inserted`) or changed its searchable content (`changed`, true on insert and
// for a legacy NULL hash). A re-ingest that only bumps last_seen_at reports both
// false and needs no re-push to the search index.
// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
// at insert and is the row's stable public identity. Re-ingest of the same
// (source, external_id) must not rewrite it, so external links stay valid even
// if the slug builder changes later (that would be a deliberate migration).
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (UpsertJobRow, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Source,
		arg.ExternalID,
		arg.URL,
		arg.Title,
		arg.Company,
		arg.CompanySlug,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.PublicSlug,
		arg.Countries,
		arg.Regions,
		arg.WorkMode,
		arg.Skills,
		arg.Seniority,
		arg.Category,
		arg.PostingLanguage,
		arg.EmploymentType,
		arg.EducationLevel,
		arg.ExperienceYearsMin,
		arg.RemoteUnspecified,
		arg.ContentHash,
	)
	var i UpsertJobRow
	err := row.Scan(
		&i.Job.ID,
		&i.Job.Source,
		&i.Job.ExternalID,
		&i.Job.URL,
		&i.Job.Title,
		&i.Job.Company,
		&i.Job.Location,
		&i.Job.Remote,
		&i.Job.Description,
		&i.Job.PostedAt,
		&i.Job.CreatedAt,
		&i.Job.UpdatedAt,
		&i.Job.CompanySlug,
		&i.Job.Enrichment,
		&i.Job.EnrichedAt,
		&i.Job.EnrichmentVersion,
		&i.Job.PublicSlug,
		&i.Job.LastSeenAt,
		&i.Job.ClosedAt,
		&i.Job.Countries,
		&i.Job.Regions,
		&i.Job.WorkMode,
		&i.Job.LivenessStrikes,
		&i.Job.Skills,
		&i.Job.Seniority,
		&i.Job.Category,
		&i.Job.CreatedBy,
		&i.Job.UpdatedBy,
		&i.Job.PostingLanguage,
		&i.Job.EmploymentType,
		&i.Job.EducationLevel,
		&i.Job.ExperienceYearsMin,
		&i.Job.Collections,
		&i.Job.ContentHash,
		&i.Job.RemoteUnspecified,
		&i.Inserted,
		&i.Changed,
	)
	return i, err
}

const upsertManualJob = `-- name: UpsertManualJob :one
WITH company_upsert AS (
    INSERT INTO companies (slug, name)
    SELECT $6, $5
    WHERE $6 <> ''
    ON CONFLICT (slug) DO UPDATE SET
        name       = EXCLUDED.name,
        updated_at = now()
)
INSERT INTO jobs (
    source, external_id, url, title, company, company_slug, location, remote, description, posted_at,
    public_slug, countries, regions, work_mode, skills, seniority, category,
    posting_language, employment_type, education_level, experience_years_min,
    remote_unspecified, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11,
    COALESCE($12::text[], '{}'), COALESCE($13::text[], '{}'),
    $14, COALESCE($15::text[], '{}'),
    $16, $17,
    $18, $19, $20, $21,
    $22, $23::bigint
)
ON CONFLICT (source, external_id) DO UPDATE SET
    url          = EXCLUDED.url,
    title        = EXCLUDED.title,
    company      = EXCLUDED.company,
    company_slug = EXCLUDED.company_slug,
    location     = EXCLUDED.location,
    remote       = EXCLUDED.remote,
    description  = EXCLUDED.description,
    posted_at    = EXCLUDED.posted_at,
    countries    = EXCLUDED.countries,
    regions      = EXCLUDED.regions,
    work_mode    = EXCLUDED.work_mode,
    skills       = EXCLUDED.skills,
    seniority    = EXCLUDED.seniority,
    category     = EXCLUDED.category,
    posting_language     = EXCLUDED.posting_language,
    employment_type      = EXCLUDED.employment_type,
    education_level      = EXCLUDED.education_level,
    experience_years_min = EXCLUDED.experience_years_min,
    remote_unspecified   = EXCLUDED.remote_unspecified,
    updated_by   = $24::bigint,
    closed_at    = NULL,
    updated_at   = now()
RETURNING id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, remote_unspecified
`

type UpsertManualJobParams struct {
	Source             string             `json:"source"`
	ExternalID         string             `json:"external_id"`
	URL                string             `json:"url"`
	Title              string             `json:"title"`
	Company            string             `json:"company"`
	CompanySlug        string             `json:"company_slug"`
	Location           string             `json:"location"`
	Remote             bool               `json:"remote"`
	Description        string             `json:"description"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	PublicSlug         string             `json:"public_slug"`
	Countries          []string           `json:"countries"`
	Regions            []string           `json:"regions"`
	WorkMode           string             `json:"work_mode"`
	Skills             []string           `json:"skills"`
	Seniority          string             `json:"seniority"`
	Category           string             `json:"category"`
	PostingLanguage    string             `json:"posting_language"`
	EmploymentType     string             `json:"employment_type"`
	EducationLevel     string             `json:"education_level"`
	ExperienceYearsMin pgtype.Int4        `json:"experience_years_min"`
	RemoteUnspecified  bool               `json:"remote_unspecified"`
	CreatedBy          int64              `json:"created_by"`
	UpdatedBy          int64              `json:"updated_by"`
}

// Moderator-authored write: the hand-curated analogue of UpsertJob. source is the
// posting's real origin (e.g. 'workatastartup'), supplied by the moderator and
// defaulting to 'manual'; the dedup key is (source, external_id = url), so re-POSTing
// the same URL updates the row idempotently instead of duplicating it. The manual
// provenance is recorded by created_by (set here, NULL for every automated source) —
// not by the source value. created_by is stamped once at insert; updated_by is
// (re)written on the conflict update. Like UpsertJob, public_slug is minted once and
// never rewritten, and the enrichment columns are left to SetJobEnrichment. The conflict
// reopens a previously closed posting (closed_at = NULL) since the moderator is
// re-asserting it.
func (q *Queries) UpsertManualJob(ctx context.Context, arg UpsertManualJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertManualJob,
		arg.Source,
		arg.ExternalID,
		arg.URL,
		arg.Title,
		arg.Company,
		arg.CompanySlug,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.PublicSlug,
		arg.Countries,
		arg.Regions,
		arg.WorkMode,
		arg.Skills,
		arg.Seniority,
		arg.Category,
		arg.PostingLanguage,
		arg.EmploymentType,
		arg.EducationLevel,
		arg.ExperienceYearsMin,
		arg.RemoteUnspecified,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.Countries,
		&i.Regions,
		&i.WorkMode,
		&i.LivenessStrikes,
		&i.Skills,
		&i.Seniority,
		&i.Category,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.PostingLanguage,
		&i.EmploymentType,
		&i.EducationLevel,
		&i.ExperienceYearsMin,
		&i.Collections,
		&i.ContentHash,
		&i.RemoteUnspecified,
	)
	return i, err
}
