// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_contributions.sql

package db

import (
	"context"
)

const companyForBoard = `-- name: CompanyForBoard :one
SELECT company, company_slug FROM jobs
WHERE source = $1 AND external_id LIKE $2 AND company_slug <> ''
LIMIT 1
`

type CompanyForBoardParams struct {
	Source       string `json:"source"`
	BoardPattern string `json:"board_pattern"`
}

type CompanyForBoardRow struct {
	Company     string `json:"company"`
	CompanySlug string `json:"company_slug"`
}

// The tracked company on a board — for the "already tracked" reply: a job's company name and
// slug so the bot/UI can link to /companies/<slug>. board_pattern is "<escaped board>:%" (same
// index-backed LIKE as JobsExistForBoard). Only rows with a resolved company_slug qualify.
func (q *Queries) CompanyForBoard(ctx context.Context, arg CompanyForBoardParams) (CompanyForBoardRow, error) {
	row := q.db.QueryRow(ctx, companyForBoard, arg.Source, arg.BoardPattern)
	var i CompanyForBoardRow
	err := row.Scan(&i.Company, &i.CompanySlug)
	return i, err
}

const createContribution = `-- name: CreateContribution :one
INSERT INTO link_contributions (submitted_by, url, source, board)
VALUES ($1::bigint, $2, $3, $4)
RETURNING id, submitted_by, url, source, board, status, created_at
`

type CreateContributionParams struct {
	SubmittedBy int64  `json:"submitted_by"`
	URL         string `json:"url"`
	Source      string `json:"source"`
	Board       string `json:"board"`
}

// Record a contribution of a novel company board. The UNIQUE (source, board) constraint
// rejects a second contribution of the same board (another vacancy or the listing); the
// repository maps that unique violation to ErrBoardAlreadyContributed. Runs in the same
// transaction as IncrementUserPoints.
func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (LinkContribution, error) {
	row := q.db.QueryRow(ctx, createContribution,
		arg.SubmittedBy,
		arg.URL,
		arg.Source,
		arg.Board,
	)
	var i LinkContribution
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Board,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const incrementUserPoints = `-- name: IncrementUserPoints :exec
UPDATE users SET points = points + 1 WHERE id = $1
`

// Award one point to the contributor. Runs in the same transaction as CreateContribution,
// so a rolled-back insert (e.g. a duplicate-board race) never credits a point.
func (q *Queries) IncrementUserPoints(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserPoints, id)
	return err
}

const jobsExistForBoard = `-- name: JobsExistForBoard :one
SELECT EXISTS (
    SELECT 1 FROM jobs WHERE source = $1 AND external_id LIKE $2
) AS exists
`

type JobsExistForBoardParams struct {
	Source       string `json:"source"`
	BoardPattern string `json:"board_pattern"`
}

// Whether the catalogue already crawls this board — any job whose external_id is "<board>:…".
// Matched with a LIKE-prefix so the (source, external_id text_pattern_ops) index serves it as
// a range scan; starts_with()/a default-collation LIKE would seq-scan the whole source (37s
// over greenhouse's ~300k rows). board_pattern is "<escaped board>:%", built by the repository.
func (q *Queries) JobsExistForBoard(ctx context.Context, arg JobsExistForBoardParams) (bool, error) {
	row := q.db.QueryRow(ctx, jobsExistForBoard, arg.Source, arg.BoardPattern)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listContributionsByUser = `-- name: ListContributionsByUser :many
SELECT id, submitted_by, url, source, board, status, created_at FROM link_contributions
WHERE submitted_by = $1
ORDER BY created_at DESC
`

// The "my contributions" list: one user's contributions, newest first.
func (q *Queries) ListContributionsByUser(ctx context.Context, submittedBy int64) ([]LinkContribution, error) {
	rows, err := q.db.Query(ctx, listContributionsByUser, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkContribution{}
	for rows.Next() {
		var i LinkContribution
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.URL,
			&i.Source,
			&i.Board,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
