// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUserLLMKey = `-- name: ClaimUserLLMKey :one
UPDATE users
SET llm_key = $1
WHERE id = $2 AND llm_key IS NULL
RETURNING coalesce(llm_key, '')::text AS llm_key
`

type ClaimUserLLMKeyParams struct {
	LlmKey pgtype.Text `json:"llm_key"`
	ID     int64       `json:"id"`
}

// Store a freshly minted credential, but only if this account still has none, and report
// what is now stored. NO ROWS means somebody else claimed first — the caller re-reads the
// winner's credential and deletes the one it minted, which would otherwise sit at the
// gateway forever spending nothing and appearing in every listing.
//
// The `IS NULL` guard is the whole race resolution: two concurrent first calls both mint,
// the row lock serializes them, and the loser's UPDATE re-evaluates the guard against the
// committed row and matches nothing.
func (q *Queries) ClaimUserLLMKey(ctx context.Context, arg ClaimUserLLMKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimUserLLMKey, arg.LlmKey, arg.ID)
	var llm_key string
	err := row.Scan(&llm_key)
	return llm_key, err
}

const clearUserLLMKey = `-- name: ClearUserLLMKey :exec
UPDATE users
SET llm_key = NULL
WHERE id = $1 AND llm_key = $2
`

type ClearUserLLMKeyParams struct {
	ID     int64       `json:"id"`
	LlmKey pgtype.Text `json:"llm_key"`
}

// Forget a credential the gateway no longer recognises, so the next call mints a
// replacement. Conditional on the value we believe is stored: a concurrent call may have
// already re-minted, and clearing unconditionally would throw away that good credential
// and leave it orphaned at the gateway.
func (q *Queries) ClearUserLLMKey(ctx context.Context, arg ClearUserLLMKeyParams) error {
	_, err := q.db.Exec(ctx, clearUserLLMKey, arg.ID, arg.LlmKey)
	return err
}

const getUserLLMKey = `-- name: GetUserLLMKey :one
SELECT coalesce(llm_key, '')::text AS llm_key
FROM users
WHERE id = $1
`

// The gateway credential this account is known by, or "" when none has been minted.
// coalesce keeps the empty string as the single "not minted" signal, so callers test a
// string rather than unwrapping a nullable through pgtype on every model call.
func (q *Queries) GetUserLLMKey(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserLLMKey, id)
	var llm_key string
	err := row.Scan(&llm_key)
	return llm_key, err
}
