// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_linking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmEmailLink = `-- name: ConfirmEmailLink :execrows
UPDATE emails
SET job_id           = suggested_job_id,
    link_source      = 'manual',
    suggested_job_id = NULL
WHERE id = $1 AND user_id = $2 AND suggested_job_id IS NOT NULL
`

type ConfirmEmailLinkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Promote a suggested link to a confirmed one: the suggestion becomes job_id with
// link_source 'manual'. No-op (0 rows) when there is no pending suggestion.
func (q *Queries) ConfirmEmailLink(ctx context.Context, arg ConfirmEmailLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmEmailLink, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserApplication = `-- name: GetUserApplication :one
SELECT viewed_at, saved_at, applied_at, stage, notes
FROM user_jobs
WHERE user_id = $1 AND job_id = $2
`

type GetUserApplicationParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

type GetUserApplicationRow struct {
	ViewedAt  pgtype.Timestamptz `json:"viewed_at"`
	SavedAt   pgtype.Timestamptz `json:"saved_at"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
	Stage     pgtype.Text        `json:"stage"`
	Notes     pgtype.Text        `json:"notes"`
}

// The caller's interaction row for one job (the application-detail header).
func (q *Queries) GetUserApplication(ctx context.Context, arg GetUserApplicationParams) (GetUserApplicationRow, error) {
	row := q.db.QueryRow(ctx, getUserApplication, arg.UserID, arg.JobID)
	var i GetUserApplicationRow
	err := row.Scan(
		&i.ViewedAt,
		&i.SavedAt,
		&i.AppliedAt,
		&i.Stage,
		&i.Notes,
	)
	return i, err
}

const linkEmailToJob = `-- name: LinkEmailToJob :execrows
UPDATE emails
SET job_id           = $3,
    link_source      = 'manual',
    suggested_job_id = NULL
WHERE id = $1 AND user_id = $2
`

type LinkEmailToJobParams struct {
	ID     int64       `json:"id"`
	UserID int64       `json:"user_id"`
	JobID  pgtype.Int8 `json:"job_id"`
}

// Manually link (or relink) an email to a chosen application, overriding any
// auto-link or suggestion.
func (q *Queries) LinkEmailToJob(ctx context.Context, arg LinkEmailToJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkEmailToJob, arg.ID, arg.UserID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJobEmails = `-- name: ListJobEmails :many
SELECT id, source, from_addr, from_name, subject, status_signal, link_source,
    received_at, (read_at IS NOT NULL)::boolean AS read
FROM emails
WHERE user_id = $1 AND job_id = $2
ORDER BY received_at DESC, id DESC
`

type ListJobEmailsParams struct {
	UserID int64       `json:"user_id"`
	JobID  pgtype.Int8 `json:"job_id"`
}

type ListJobEmailsRow struct {
	ID           int64              `json:"id"`
	Source       string             `json:"source"`
	FromAddr     string             `json:"from_addr"`
	FromName     string             `json:"from_name"`
	Subject      string             `json:"subject"`
	StatusSignal pgtype.Text        `json:"status_signal"`
	LinkSource   pgtype.Text        `json:"link_source"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	Read         bool               `json:"read"`
}

// The emails linked to one of the caller's applications, newest first, for the
// application detail page.
func (q *Queries) ListJobEmails(ctx context.Context, arg ListJobEmailsParams) ([]ListJobEmailsRow, error) {
	rows, err := q.db.Query(ctx, listJobEmails, arg.UserID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobEmailsRow{}
	for rows.Next() {
		var i ListJobEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.FromAddr,
			&i.FromName,
			&i.Subject,
			&i.StatusSignal,
			&i.LinkSource,
			&i.ReceivedAt,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectEmailLink = `-- name: RejectEmailLink :execrows
UPDATE emails
SET suggested_job_id = NULL
WHERE id = $1 AND user_id = $2 AND suggested_job_id IS NOT NULL
`

type RejectEmailLinkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Dismiss a suggestion without linking.
func (q *Queries) RejectEmailLink(ctx context.Context, arg RejectEmailLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectEmailLink, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkEmail = `-- name: UnlinkEmail :execrows
UPDATE emails
SET job_id      = NULL,
    link_source = NULL
WHERE id = $1 AND user_id = $2
`

type UnlinkEmailParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Clear an email's application link (leaves the classified status intact).
func (q *Queries) UnlinkEmail(ctx context.Context, arg UnlinkEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkEmail, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
