// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Company struct {
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Collections      []string           `json:"collections"`
	JobCount         int32              `json:"job_count"`
	Regions          []string           `json:"regions"`
	Countries        []string           `json:"countries"`
	Domains          []string           `json:"domains"`
	CompanyTypes     []string           `json:"company_types"`
	CompanySizes     []string           `json:"company_sizes"`
	Industries       []string           `json:"industries"`
	YearFounded      pgtype.Int4        `json:"year_founded"`
	EmployeeCount    pgtype.Int4        `json:"employee_count"`
	HqCountry        pgtype.Text        `json:"hq_country"`
	OrganizationType pgtype.Text        `json:"organization_type"`
	Tagline          pgtype.Text        `json:"tagline"`
	CompanyInfo      json.RawMessage    `json:"company_info"`
	IsReference      bool               `json:"is_reference"`
	CompanyInfoAt    pgtype.Timestamptz `json:"company_info_at"`
}

type EnrichmentOutbox struct {
	ID            int64              `json:"id"`
	JobID         int64              `json:"job_id"`
	TargetVersion int32              `json:"target_version"`
	Attempts      int32              `json:"attempts"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                 int64              `json:"id"`
	Source             string             `json:"source"`
	ExternalID         string             `json:"external_id"`
	URL                string             `json:"url"`
	Title              string             `json:"title"`
	Company            string             `json:"company"`
	Location           string             `json:"location"`
	Remote             bool               `json:"remote"`
	Description        string             `json:"description"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompanySlug        string             `json:"company_slug"`
	Enrichment         json.RawMessage    `json:"enrichment"`
	EnrichedAt         pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion  int32              `json:"enrichment_version"`
	PublicSlug         string             `json:"public_slug"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	Countries          []string           `json:"countries"`
	Regions            []string           `json:"regions"`
	WorkMode           string             `json:"work_mode"`
	LivenessStrikes    int32              `json:"liveness_strikes"`
	Skills             []string           `json:"skills"`
	Seniority          string             `json:"seniority"`
	Category           string             `json:"category"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	UpdatedBy          pgtype.Int8        `json:"updated_by"`
	PostingLanguage    string             `json:"posting_language"`
	EmploymentType     string             `json:"employment_type"`
	EducationLevel     string             `json:"education_level"`
	ExperienceYearsMin pgtype.Int4        `json:"experience_years_min"`
	Collections        []string           `json:"collections"`
	ContentHash        pgtype.Text        `json:"content_hash"`
	EnglishLevel       string             `json:"english_level"`
	Cities             []string           `json:"cities"`
	ViewCount          int32              `json:"view_count"`
	AppliedCount       int32              `json:"applied_count"`
}

type JobReport struct {
	ID              int64              `json:"id"`
	ReportedBy      int64              `json:"reported_by"`
	JobID           int64              `json:"job_id"`
	Reason          string             `json:"reason"`
	Details         string             `json:"details"`
	ContactTelegram string             `json:"contact_telegram"`
	Status          string             `json:"status"`
	ReviewReason    string             `json:"review_reason"`
	ReviewedBy      pgtype.Int8        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type JobSubmission struct {
	ID           int64              `json:"id"`
	SubmittedBy  int64              `json:"submitted_by"`
	URL          string             `json:"url"`
	Source       string             `json:"source"`
	Title        string             `json:"title"`
	Company      string             `json:"company"`
	Location     string             `json:"location"`
	Remote       bool               `json:"remote"`
	Description  string             `json:"description"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	Status       string             `json:"status"`
	ReviewReason string             `json:"review_reason"`
	ReviewedBy   pgtype.Int8        `json:"reviewed_by"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	JobID        pgtype.Int8        `json:"job_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SavedSearch struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Query       string             `json:"query"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PublicSlug  pgtype.Text        `json:"public_slug"`
	AuthorLabel pgtype.Text        `json:"author_label"`
}

type Subscription struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	SavedSearchID int64              `json:"saved_search_id"`
	Channel       string             `json:"channel"`
	Destination   pgtype.Text        `json:"destination"`
	Active        bool               `json:"active"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionMatch struct {
	SubscriptionID int64              `json:"subscription_id"`
	JobID          int64              `json:"job_id"`
	MatchedAt      pgtype.Timestamptz `json:"matched_at"`
	NotifiedAt     pgtype.Timestamptz `json:"notified_at"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	Attempts       int32              `json:"attempts"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	LastError      string             `json:"last_error"`
}

type TelegramLink struct {
	UserID   int64              `json:"user_id"`
	ChatID   int64              `json:"chat_id"`
	LinkedAt pgtype.Timestamptz `json:"linked_at"`
}

type TelegramPost struct {
	Channel     string             `json:"channel"`
	MsgID       int64              `json:"msg_id"`
	Text        string             `json:"text"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
	Attempts    int32              `json:"attempts"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
	LastError   string             `json:"last_error"`
	ExtractedAt pgtype.Timestamptz `json:"extracted_at"`
	Links       []byte             `json:"links"`
}

type User struct {
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Role                 string             `json:"role"`
	ResumeObjectKey      pgtype.Text        `json:"resume_object_key"`
	ResumeUploadedAt     pgtype.Timestamptz `json:"resume_uploaded_at"`
	ResumeAtsAnalysis    []byte             `json:"resume_ats_analysis"`
	ResumeEmbedding      []float64          `json:"resume_embedding"`
	ResumeEmbeddingModel pgtype.Text        `json:"resume_embedding_model"`
}

type UserIdentity struct {
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	UserID         int64              `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserJob struct {
	UserID      int64              `json:"user_id"`
	JobID       int64              `json:"job_id"`
	ViewedAt    pgtype.Timestamptz `json:"viewed_at"`
	AppliedAt   pgtype.Timestamptz `json:"applied_at"`
	SavedAt     pgtype.Timestamptz `json:"saved_at"`
	Stage       pgtype.Text        `json:"stage"`
	Notes       pgtype.Text        `json:"notes"`
	DismissedAt pgtype.Timestamptz `json:"dismissed_at"`
}

type UserProfile struct {
	UserID          int64              `json:"user_id"`
	Skills          []string           `json:"skills"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Specializations []string           `json:"specializations"`
}
