// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Resolve a presented token (by its SHA-256 hash) to the owning user id, enforcing
	// expiry and touching last_used_at in one atomic statement. No row means the key is
	// unknown, revoked, or expired; the caller treats pgx.ErrNoRows as 401.
	AuthenticateAPIKey(ctx context.Context, tokenHash string) (int64, error)
	// Claim a batch of live, unleased entries for OPEN jobs, freshest job first, by
	// stamping claimed_at. The jobs join lets the claim order by posting freshness and
	// skip closed jobs, so LLM budget goes to live postings users will actually see.
	// Freshness is COALESCE(posted_at, created_at): jobs without a source post date
	// (telegram/linksource and some ATS) fall back to ingest time, so they rank by
	// recency instead of starving behind every dated job under NULLS LAST. FOR UPDATE OF o
	// locks only outbox rows (a bare FOR UPDATE would also lock jobs, making concurrent
	// claim waves contend); SKIP LOCKED lets concurrent workers take disjoint rows; the
	// lease predicate reclaims entries whose worker died (stale claimed_at), so no
	// separate reaper process is needed.
	ClaimEnrichmentBatch(ctx context.Context, arg ClaimEnrichmentBatchParams) ([]ClaimEnrichmentBatchRow, error)
	// Claim a batch of live, unleased entries, freshest job first, by stamping claimed_at.
	// Unlike ClaimEnrichmentBatch this does NOT filter unindexable jobs out: a closed OR
	// non-canonical (duplicate_of) entry is the removal signal, so the worker must receive
	// it and branch on `closed` (true = remove the document). The jobs join supplies both
	// the freshness order and that flag. Freshness is
	// COALESCE(posted_at, created_at): jobs without a source post date fall back to ingest
	// time so they rank by recency instead of starving under NULLS LAST. FOR UPDATE OF o
	// locks only outbox rows (a bare FOR UPDATE would also lock jobs, making concurrent
	// claim waves contend); SKIP LOCKED lets concurrent workers take disjoint rows; the
	// lease predicate reclaims entries whose worker died (stale claimed_at), so no separate
	// reaper process is needed.
	// Join jobs off the claimable CTE (not the UPDATE target o, which Postgres forbids in
	// FROM) so the removal branch gets the job's closed flag without a second query.
	ClaimSemanticBatch(ctx context.Context, arg ClaimSemanticBatchParams) ([]ClaimSemanticBatchRow, error)
	// Lease a batch of pending, live matches for active subscriptions by stamping
	// claimed_at, oldest-claimable first, ordered by subscription so the worker can
	// group a subscription's matches into one digest. FOR UPDATE OF m locks only match
	// rows; SKIP LOCKED lets overlapping passes take disjoint rows so a digest is sent
	// at most once; the lease predicate reclaims rows whose sender died (stale
	// claimed_at), so no separate reaper is needed. The digest is sent OUTSIDE this
	// claim's transaction, so no network call is held inside a row lock.
	ClaimSubscriptionMatches(ctx context.Context, arg ClaimSubscriptionMatchesParams) ([]ClaimSubscriptionMatchesRow, error)
	// Claim a batch of pending posts by stamping claimed_at. SKIP LOCKED lets
	// concurrent workers take disjoint rows; the lease predicate reclaims posts whose
	// worker died (stale claimed_at), so no separate reaper process is needed.
	// Oldest post first so a backlog drains in posting order.
	ClaimTelegramPosts(ctx context.Context, arg ClaimTelegramPostsParams) ([]ClaimTelegramPostsRow, error)
	// Reset a tracked job to the wishlist: drop stage and applied state, keep saved/viewed/notes.
	ClearJobProgress(ctx context.Context, arg ClearJobProgressParams) (UserJob, error)
	// Unpublish a board: clear the slug and author label, owner-scoped. Returns the
	// affected row count: 1 for an owned row (whether or not it was shared — unshare is an
	// idempotent no-op when already private), 0 when missing or not the caller's (→ 404).
	ClearSavedSearchPublicSlug(ctx context.Context, arg ClearSavedSearchPublicSlugParams) (int64, error)
	// Clear a batch of jobs' embed provenance after their documents are removed from
	// jobs_semantic (closed-job path). Run in the same transaction as DeleteSemanticEntriesBatch.
	ClearSemanticEmbeddedBatch(ctx context.Context, ids []int64) error
	// Clear the user's résumé pointer (after deleting the object from storage), any
	// cached ATS review, the derived CV embedding (no CV → no recommendations), and the
	// derived structured résumé (the structure must not outlive the CV it describes).
	ClearUserResume(ctx context.Context, id int64) error
	// Soft-close one job now (see job-lifecycle): a moderator resolving a report with
	// close_job=true. The third writer of closed_at, alongside the ingest sweep and the
	// liveness probe. WHERE closed_at IS NULL keeps it idempotent — a second close on an
	// already-closed job is a no-op, never an error, so it never fights the report's own
	// status guard. A later ingest upsert may legitimately reopen a board job (reopen-on-
	// reappear); that is the lifecycle's existing behavior, not a conflict.
	CloseJobByID(ctx context.Context, id int64) (int64, error)
	// Stream-driven close (see job-lifecycle): a self-closing feed source (e.g. jobtech)
	// learns of a removed posting from its incremental stream and closes it by identity,
	// rather than relying on the post-run unseen sweep (which it opts out of, since an
	// incremental stream re-reports only changed ads and so never refreshes last_seen_at
	// for the still-open ones). WHERE closed_at IS NULL keeps it idempotent; a later
	// upsert of the same (source, external_id) reopens it if the posting reappears.
	CloseJobBySourceExternalID(ctx context.Context, arg CloseJobBySourceExternalIDParams) (int64, error)
	// Post-ingest sweep (see job-lifecycle spec): close every open job of ONE source not
	// seen since the cutoff, scoped to the company slugs the run actually crawled. Scoped
	// by source because ingest runs per provider (a greenhouse run must not close jobs
	// another provider owns), and by company_slug because a run may crawl only a SUBSET of
	// a provider's boards — a partial or targeted run (or a full crawl of a huge provider
	// that times out and only completes some boards) must not close the companies it never
	// touched. The caller passes the crawled slugs and owns the grace window (cutoff =
	// now() - window), so neither a failed nor a partial crawl mass-closes a catalogue.
	CloseUnseenJobs(ctx context.Context, arg CloseUnseenJobsParams) (int64, error)
	// Company slugs with at least one OPEN aggregator posting — the drive list for the
	// cross-source aggregator suppression pass. An open aggregator row is a candidate whether
	// it still needs suppressing OR needs releasing (its ATS twin closed), so one predicate
	// covers both. Processed one company at a time (SuppressAggregatorDuplicatesForCompany),
	// mirroring the role-duplicate recompute's lock discipline.
	CompaniesWithAggregatorPostings(ctx context.Context, aggregators []string) ([]string, error)
	// Company slugs whose role-duplicate markers may need recomputing: a company with an
	// open role cluster (>1 posting sharing a fingerprint) to collapse, OR one still
	// carrying an open marker that may need clearing (its cluster shrank). The recompute
	// processes these ONE COMPANY AT A TIME (RecomputeRoleDuplicatesForCompany) in short
	// transactions, so it never holds a table-wide lock that would stall concurrent ingest
	// crawls (a whole-table UPDATE did: it locked ~1.4M rows for minutes).
	CompaniesWithRoleClusters(ctx context.Context) ([]string, error)
	// Whether a company row already exists for the slug. The backfill checks this
	// before upserting to log matched-existing vs inserted-reference counts — the
	// upsert itself is blind to which path (insert or update) it took.
	CompanyExists(ctx context.Context, slug string) (bool, error)
	// The denormalized open-job count for a slug (pgx.ErrNoRows if the company is
	// absent). cmd/import-yc uses it to guard against homonym collisions: it skips
	// enriching an existing company whose job_count dwarfs a matched YC entry's team.
	CompanyJobCountBySlug(ctx context.Context, slug string) (int32, error)
	// The slug ending every full chunk of `chunk_size` companies (ordered by slug),
	// excluding the final row, so the sitemap index can list each company sub-sitemap's
	// keyset cursor.
	CompanySitemapBoundaries(ctx context.Context, chunkSize int64) ([]string, error)
	// Total companies matching the same optional name + facet filters as ListCompanies,
	// so search/filter pagination reports the filtered total. Keep this WHERE identical
	// to ListCompanies.
	CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error)
	// Total distinct subject groups for the caller (with the same optional search),
	// so the inbox knows whether more pages remain.
	CountInboxGroups(ctx context.Context, arg CountInboxGroupsParams) (int64, error)
	// Per-stage application counts for the Pipeline snapshot. An application is any
	// row the user applied to or staged (saved-only rows are excluded); a row with
	// applied_at set but no stage groups under a NULL stage. The Go layer folds these
	// rows into the pipeline buckets.
	CountMyJobsByStage(ctx context.Context, userID int64) ([]CountMyJobsByStageRow, error)
	// How many distinct jobs the caller first analyzed within the window (created_at is the
	// first-analysis time — see UpsertUserJobAnalysis). This is the fit-analysis quota
	// meter: the PK guarantees one row per (user, job), so the row count is the distinct-job
	// count. A recompute does not add a row, so it never consumes quota.
	CountRecentUserJobAnalyses(ctx context.Context, arg CountRecentUserJobAnalysesParams) (int64, error)
	// How many saved searches a user has — the per-user cap is enforced against this in
	// the service before a create.
	CountSavedSearches(ctx context.Context, userID int64) (int64, error)
	// Per-filter row counts for the my-jobs tabs, in one aggregate pass. "all" is
	// every interaction row; "viewed" is the view-only subset (neither saved nor
	// applied), matching the ListUserJobs filter. "board" counts jobs on the Kanban
	// board (saved, applied, or stage set), matching the ListUserJobs board filter.
	CountUserJobs(ctx context.Context, userID int64) (CountUserJobsRow, error)
	// Create an API key for a user. The caller passes the SHA-256 token_hash and the
	// display token_prefix; the plaintext token is shown once and never stored.
	// expires_at NULL means the key never expires. Returns display fields only, never
	// the hash.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	// File a user complaint about a job into the moderation queue as 'pending'. The partial
	// unique index on (reported_by, job_id) WHERE status='pending' rejects a second open report
	// of the same job by the same user (the repository maps that unique violation to a 409).
	CreateReport(ctx context.Context, arg CreateReportParams) (JobReport, error)
	// Create a saved search for a user. The UNIQUE (user_id, name) constraint rejects a
	// duplicate name (surfaced by the repository as a duplicate-name error). Returns the row.
	CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error)
	// Insert a user-contributed vacancy into the moderation queue as 'pending'. The partial
	// unique index on lower(url) WHERE status='pending' rejects a second pending submission of
	// the same URL (the repository maps that unique violation to a 409).
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (JobSubmission, error)
	// Subscribe one of the caller's saved searches to a delivery channel. The SELECT
	// from saved_searches enforces ownership in the same statement: a saved_search_id
	// the caller does not own yields no row (sqlc :one returns ErrNoRows, mapped to
	// 404). A second subscription for the same (saved_search, channel) violates the
	// UNIQUE constraint (surfaced as a 409). Returns the created row.
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// Register a new account. email is stored as given (the handler lowercases it);
	// the unique index on lower(email) rejects duplicates regardless of case. role is
	// returned so the new account's wire shape carries it (always 'user' at creation).
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Link a provider identity to an account (first OAuth sign-in). The composite
	// primary key rejects a duplicate identity.
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error
	// Revoke (delete) a key, scoped to its owner so a user can only delete their own.
	// Returns the affected row count: 0 means the key does not exist or is not the
	// caller's (the handler maps that to 404).
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
	// First half of the atomic rebuild: clear the rollup. Run in the same transaction
	// as RebuildJobDailyStats so readers never see an empty table and reopen-orphaned
	// days (a day that had only closures, now reopened) are dropped rather than left
	// stale.
	DeleteAllJobDailyStats(ctx context.Context) error
	DeleteEnrichmentEntry(ctx context.Context, id int64) error
	DeleteGmailConnection(ctx context.Context, userID int64) error
	// Drop companies no longer referenced by any job — the stale rows left behind
	// when a slug-builder change re-keys jobs onto new slugs. Reference rows imported
	// by the company-info backfill are preserved: they intentionally have no job, so
	// the NOT is_reference guard keeps the backfill directory from being swept away.
	DeleteOrphanCompanies(ctx context.Context) (int64, error)
	// Delete a saved search, scoped to its owner so a user can only delete their own.
	// Returns the affected row count: 0 means it does not exist or is not the caller's
	// (the handler maps that to 404).
	DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error)
	DeleteSemanticEntriesBatch(ctx context.Context, ids []int64) error
	// Unsubscribe, scoped to its owner. Returns the affected row count: 0 means it
	// does not exist or is not the caller's (the handler maps that to 404). The match
	// ledger cascades away with the subscription.
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error)
	// Unlink Telegram. Returns the affected row count: 0 means there was no link.
	DeleteTelegramLink(ctx context.Context, userID int64) (int64, error)
	DeleteUserEmails(ctx context.Context, userID int64) error
	// Remove the caller's profile. Returns the affected row count (0 when none existed); the
	// handler treats delete as idempotent (204 either way).
	DeleteUserProfile(ctx context.Context, userID int64) (int64, error)
	// Dismiss (swipe away) a job for a user in the swipe deck. Idempotent and
	// independent of a prior view: it inserts the row (viewed_at defaults) or
	// refreshes dismissed_at in place.
	DismissJob(ctx context.Context, arg DismissJobParams) (UserJob, error)
	// Transactional-outbox enqueue for the ingest write path: queue this one job for
	// enrichment, gated on the same conditions the backfill uses (unenriched or below the
	// target schema version, and a non-blacklisted category), so an already-enriched job
	// is not re-queued and a confidently non-technical role (exclude_categories =
	// enrich.NonTechCategories) never consumes LLM budget. category is NOT NULL DEFAULT '',
	// so an empty/unrecognized category still enqueues (empty string <> ALL). Idempotent
	// via the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
	// job's UpsertJob so a newly ingested job is queued atomically with its write.
	EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error)
	// Idempotent backfill: enqueue every OPEN job that is unenriched or below the target
	// schema version. Closed jobs (closed_at IS NOT NULL) are skipped — a dead posting no
	// user will see should not consume LLM budget. Jobs whose derived category is in
	// exclude_categories (enrich.NonTechCategories) are skipped too, so LLM budget stays
	// on technical roles; category is NOT NULL DEFAULT '', so an empty/unrecognized
	// category is never excluded (empty string <> ALL keeps the row). ON CONFLICT keeps
	// exactly one entry per (job_id, target_version), so running this every command
	// invocation never duplicates work.
	EnqueuePendingJobs(ctx context.Context, arg EnqueuePendingJobsParams) (int64, error)
	// Idempotent backfill for the incremental semantic-embedding queue. Enqueues two
	// kinds of outstanding work at the target embedder model:
	//   1. OPEN jobs whose stored vector is missing, content-stale, or model-stale —
	//      i.e. semantic_embedded_model differs from the target OR semantic_embedded_hash
	//      differs from the job's current content_hash. Jobs whose derived category is in
	//      exclude_categories (enrich.NonTechCategories) are skipped so embed budget stays
	//      on technical roles; category is NOT NULL DEFAULT '', so an empty/unrecognized
	//      category is never excluded (empty string <> ALL keeps the row).
	//   2. UNINDEXABLE jobs that still carry an embed stamp (were embedded while open and
	//      canonical) — a job now closed OR a non-canonical repost (duplicate_of set) — so
	//      the worker removes their document from jobs_semantic and clears the stamp. This
	//      mirrors the facet index: the full reindex --semantic also drops reposts (shared
	//      splitJobs), so the incremental path must not re-add them.
	// ON CONFLICT keeps exactly one entry per (job_id, target_model), so running this every
	// command invocation never duplicates work.
	EnqueuePendingSemanticJobs(ctx context.Context, arg EnqueuePendingSemanticJobsParams) (int64, error)
	// Fast approximate open-job total for the DB-backed /jobs list's meta.total. An
	// exact count(*) over ~millions of open rows was a per-request full scan; the
	// planner's estimate (see estimate_open_jobs(), migration 0033) is O(1) and
	// tracks the closed_at IS NULL filter. The total is approximate by design.
	EstimateOpenJobs(ctx context.Context) (int64, error)
	// Job ids the user has already interacted with (viewed, saved, applied, or
	// dismissed) — the swipe deck's exclusion set, so a card is shown at most once
	// across sessions. viewed_at is set on every interaction row, so any row for the
	// user counts (the deck records a view the moment a card is shown). Ordered
	// most-recently-touched first and capped ($2) so the deck's `id NOT IN (...)`
	// search filter stays bounded; the overflow risk is only an occasional re-shown
	// long-ago-seen job, never a correctness problem.
	ExcludedJobIDs(ctx context.Context, arg ExcludedJobIDsParams) ([]int64, error)
	// Seen-set for a hydrating source (see source-ingest): all external_ids stored for one
	// provider, so an adapter with expensive per-posting detail (justjoin, ~20k live offers)
	// fetches detail only for postings the catalogue does not already have. Closed rows are
	// included — a closed posting is still "seen" (no need to re-fetch its detail; a reappearance
	// reopens it via the upsert regardless). Keyed by source alone; the caller namespaces the
	// adapter's raw posting id to match the stored external_id.
	ExistingExternalIDs(ctx context.Context, source string) ([]string, error)
	// The board's current cooldown_until (NULL = eligible). Absent row → pgx.ErrNoRows,
	// which the caller treats as "never seen, eligible".
	GetBoardCooldown(ctx context.Context, arg GetBoardCooldownParams) (pgtype.Timestamptz, error)
	// SELECT * (not an explicit column list) so the generated row stays db.Company as
	// the table grows columns (e.g. collections); an explicit subset makes sqlc emit a
	// distinct row type and breaks the company-detail handler on every new column.
	GetCompany(ctx context.Context, slug string) (Company, error)
	GetEmail(ctx context.Context, arg GetEmailParams) (GetEmailRow, error)
	GetGmailConnection(ctx context.Context, userID int64) (GetGmailConnectionRow, error)
	GetGmailRefreshToken(ctx context.Context, userID int64) (GetGmailRefreshTokenRow, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetJobBySlug(ctx context.Context, publicSlug string) (Job, error)
	// Load a job by its dedup identity (source, external_id) — the key the Job
	// aggregate's repository loads by, mirroring the CloseJobBySourceExternalID key.
	GetJobBySourceExternalID(ctx context.Context, arg GetJobBySourceExternalIDParams) (Job, error)
	// Slim slug->id lookup for the view/apply interaction path, which needs only the
	// internal id (the user_jobs FK) and must not drag the wide description/enrichment
	// columns over the wire on every silent view. GetJobBySlug (SELECT *) stays for the
	// public detail handler that renders the whole row.
	GetJobIDBySlug(ctx context.Context, publicSlug string) (int64, error)
	// Batch-load the persisted rows the embed worker builds documents from. A corrupted
	// row (SQLSTATE XX001) aborts the whole scan; the worker then retries the batch one id
	// at a time to isolate and dead-letter the bad row.
	GetJobsByIDs(ctx context.Context, ids []int64) ([]Job, error)
	// The display fields for the jobs in a digest, freshest first. Salary fields are
	// projected out of the enrichment JSONB (absent keys → NULL) so a card can render
	// a compensation line only when one is known.
	GetJobsForDigest(ctx context.Context, jobIds []int64) ([]GetJobsForDigestRow, error)
	// Public read of a shared board by its slug — no auth, no owner-scoping. Exposes only
	// the board's display fields; owner columns (user_id) are never selected. A NULL slug
	// never equals the param, so private sets are unreachable. No row → 404.
	GetPublicBoardBySlug(ctx context.Context, publicSlug pgtype.Text) (GetPublicBoardBySlugRow, error)
	// Load a single report by id for the review path. The resolve/dismiss flow guards the
	// status in the service; the Mark* queries are additionally scoped to status='pending' as
	// defense-in-depth against a concurrent second decision.
	GetReport(ctx context.Context, id int64) (JobReport, error)
	// Fetch one of a user's saved searches, owner-scoped. Used by the share use case to
	// read the current name/public_slug before deciding whether to keep an existing slug
	// or mint a new one. No matching row (wrong id or another user's) returns no row (the
	// service maps that to ErrNotFound).
	GetSavedSearch(ctx context.Context, arg GetSavedSearchParams) (SavedSearch, error)
	// Load a single submission by id for the review path. The approve/reject flow guards the
	// status in the service; the Mark* queries are additionally scoped to status='pending' as
	// defense-in-depth against a concurrent second decision.
	GetSubmission(ctx context.Context, id int64) (JobSubmission, error)
	// The delivery context for one subscription: channel + destination, the saved
	// search name (for the digest heading), the user's account email (the email
	// channel's live recipient), and the user's linked Telegram chat (NULL when
	// unlinked → the worker soft-skips telegram delivery rather than failing it).
	GetSubscriptionForDelivery(ctx context.Context, id int64) (GetSubscriptionForDeliveryRow, error)
	// The caller's linked Telegram chat (link-status endpoint + delivery resolution).
	GetTelegramLink(ctx context.Context, userID int64) (TelegramLink, error)
	// The user's cached CV ATS qualitative review (content-quality + findings), or NULL
	// when none has been computed. Derived only — never the raw CV text.
	GetUserATSAnalysis(ctx context.Context, id int64) ([]byte, error)
	// Login lookup. Case-insensitive on email; returns password_hash so the handler
	// can verify the password (and reject accounts that have none). role feeds the
	// post-login wire shape.
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	// Profile lookup for the authenticated user. Never selects password_hash. role is
	// included so /auth/me can tell a client whether to surface moderator-only UI.
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// OAuth sign-in fast path: resolve a provider identity straight to its user.
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (GetUserByIdentityRow, error)
	// The caller's cached fit analysis for one job, with the staleness stamps it was
	// computed against. No row means the pair was never analyzed (the handler serves a
	// null analysis, no LLM call). The handler compares cv_uploaded_at / job_content_hash
	// to the live CV upload time and job content_hash to decide the stale flag.
	GetUserJobAnalysis(ctx context.Context, arg GetUserJobAnalysisParams) (GetUserJobAnalysisRow, error)
	// The caller's single profile, keyed by user_id. No matching row means the user has not
	// saved a profile yet (the handler maps that to a null payload / 404 on sub-resources).
	GetUserProfile(ctx context.Context, userID int64) (UserProfile, error)
	// The authenticated user's résumé pointer (object key + upload time), or NULLs when
	// no résumé is stored. The blob lives in S3 under the key; this is just the pointer.
	GetUserResume(ctx context.Context, id int64) (GetUserResumeRow, error)
	// The user's persisted CV embedding and the embedder identity that produced it, or
	// NULLs when none is stored. The caller ignores a vector whose model no longer matches
	// the current embedder (stale) — see the cv-recommendations change.
	GetUserResumeEmbedding(ctx context.Context, id int64) (GetUserResumeEmbeddingRow, error)
	// The user's derived structured résumé plus its provenance stamps (the LLM model and
	// the résumé upload time it was derived from), alongside the current résumé upload time
	// so the caller can tell whether the structure still describes the stored CV (served
	// only when resume_structured_uploaded_at equals resume_uploaded_at). NULLs when none.
	GetUserResumeStructured(ctx context.Context, id int64) (GetUserResumeStructuredRow, error)
	// Slim role lookup for the RequireRole authorization middleware: it runs on every
	// request to a role-gated endpoint and needs only the role, so it does not drag the
	// full user row (the GetJobIDBySlug precedent for a hot-path read).
	GetUserRole(ctx context.Context, id int64) (string, error)
	// Crawl write path: store a fetched post once. ON CONFLICT DO NOTHING makes
	// re-crawling idempotent — a stored post (pending, done, or dead-lettered) is
	// never reset. extracted_at is non-NULL when the ingest prefilter already
	// decided the post holds no vacancy, so it is recorded but never queued.
	InsertTelegramPost(ctx context.Context, arg InsertTelegramPostParams) (int64, error)
	// A user's API keys, newest first. Metadata only — never the token_hash.
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error)
	// Every active subscription with the data the matching worker needs: the saved
	// search query to translate into a filter, plus identity/channel for fan-out. The
	// worker groups these by canonical(query) so each distinct filter hits the search
	// index once regardless of how many subscriptions share it.
	ListActiveSubscriptions(ctx context.Context) ([]ListActiveSubscriptionsRow, error)
	// Catalog page: companies with their job counts, most active first. The job count
	// is read from the denormalized companies.job_count column (maintained by
	// cmd/recount-companies), so this read does not join jobs. Ordered by job_count
	// DESC, name — the same ordering the sidebar company typeahead consumes. An empty
	// `search` short-circuits the ILIKE, so the same prepared statement serves both
	// the full list and a name search (`search` is a case-insensitive substring of the
	// name). Each facet param is a text[] filtered by array overlap (&&): an empty
	// array short-circuits to no constraint, non-empty values are OR-ed within the
	// facet, and the facets AND together (and with the name search). `remote_regions`
	// is the job-derived facet scoped to remote jobs (see RefreshCompanyFacets), a
	// subset of `regions`. The name search also matches the slug, so a hyphenated slug
	// query ("ge-vernova") finds the company even though its name has a space ("GE
	// Vernova"). CountCompanies MUST keep an identical WHERE so the filtered total
	// matches the page.
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	// All companies with their current collection membership. cmd/import-collections
	// reads this to know the existing company slugs (the match target) and each
	// company's current tags (so it can reconcile only the tags it manages, leaving any
	// others untouched).
	ListCompanyCollections(ctx context.Context) ([]ListCompanyCollectionsRow, error)
	// Slim keyset page of companies for the sitemap, cursored by the slug primary key
	// (first chunk keyed by the empty string, which sorts before every slug).
	ListCompanySitemap(ctx context.Context, arg ListCompanySitemapParams) ([]ListCompanySitemapRow, error)
	// Drives the sync worker: every connection still authorized.
	ListConnectedGmailUsers(ctx context.Context) ([]ListConnectedGmailUsersRow, error)
	ListEmailsByGroup(ctx context.Context, arg ListEmailsByGroupParams) ([]ListEmailsByGroupRow, error)
	// One row per normalized subject: count, newest receipt, distinct sender names,
	// and the newest message's original subject for display. An optional search term
	// (empty = no filter) matches a message's subject, sender, or body — a group
	// surfaces when any of its messages matches.
	ListInboxGroups(ctx context.Context, arg ListInboxGroupsParams) ([]ListInboxGroupsRow, error)
	// Dense activity series over [from, to] at the given granularity. A daily
	// generate_series builds the gap-free calendar; the LEFT JOIN fills each day's
	// counts (missing days → 0), and date_trunc(unit, ...) rolls those days up to the
	// requested bucket (day/week/month) so empty buckets still appear as zeros. `unit`
	// is a caller-validated date_trunc field (day/week/month), never raw user input.
	ListJobActivity(ctx context.Context, arg ListJobActivityParams) ([]ListJobActivityRow, error)
	// Id-only projection of ListJobsByIDAfter, used as the corruption-degrade path:
	// when a full SELECT * batch faults on a corrupted TOAST value (SQLSTATE XX001),
	// the scan re-reads the same window as bare ids (id is never toasted, so this
	// never faults) and then fetches each row individually to isolate and skip the
	// unreadable one.
	ListJobIDsAfter(ctx context.Context, arg ListJobIDsAfterParams) ([]int64, error)
	// Id-only projection of ListJobsUpdatedAfter — the corruption-degrade path for the
	// incremental (`reindex --since`) scan, mirroring ListJobIDsAfter.
	ListJobIDsUpdatedAfter(ctx context.Context, arg ListJobIDsUpdatedAfterParams) ([]int64, error)
	// The freshest open jobs for the sitemap: only the fields a URL needs, newest id
	// first. Ordering by id DESC (served by jobs_open_id_idx) reads the most recently
	// inserted rows, which sit at the physical end of the heap — a sequential, cache-warm
	// scan. Enumerating the whole 2.5M-row catalogue per request is heap-bound and far
	// too slow (and pollutes the buffer cache), so the sitemap ships the freshest slice;
	// fuller coverage needs a precomputed narrow table, not a live scan.
	ListJobSitemapFreshest(ctx context.Context, rowLimit int32) ([]ListJobSitemapFreshestRow, error)
	// Newest-added first: created_at is when the job entered the catalogue (stable
	// across re-ingests), so fresh ingests surface on top regardless of how old the
	// platform's posted_at is. id breaks ties within one ingest batch.
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	// duplicate_of IS NULL collapses role-cluster reposts to their canonical row, matching
	// the /jobs list so a company page shows one card per role, not every repost.
	ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error)
	// Keyset scan for the reindex command: pages by the immutable primary key, so
	// concurrent inserts/updates (which shift posted_at ordering) cannot make the
	// scan skip or repeat rows the way OFFSET pagination would.
	ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error)
	// Keyset scan over one provider's rows, for cmd/backfill-justjoin: pages by the immutable
	// primary key (concurrent writes can't skip or repeat rows) filtered to a single source. Returns
	// closed rows too — a one-time backfill of a missing description fills open and closed alike.
	ListJobsBySourceAfter(ctx context.Context, arg ListJobsBySourceAfterParams) ([]Job, error)
	// Incremental keyset scan for `reindex --since`: like ListJobsByIDAfter but only
	// rows changed at or after the cutoff. Every write path (UpsertJob, the close
	// sweeps, SetJobEnrichment, UpdateJobFacets) stamps updated_at = now(), so this
	// captures new, re-crawled, closed, and re-enriched jobs — enough to bring an
	// index current without re-pushing the whole table. Returns closed rows too, so
	// the caller deletes a freshly-closed job from the index.
	ListJobsUpdatedAfter(ctx context.Context, arg ListJobsUpdatedAfterParams) ([]Job, error)
	// Id-only projection of ListOpenJobsPostedAfter — the corruption-degrade path for the
	// freshness-scoped semantic scan, mirroring ListJobIDsAfter.
	ListOpenJobIDsPostedAfter(ctx context.Context, arg ListOpenJobIDsPostedAfterParams) ([]int64, error)
	// Freshness-scoped keyset scan for `reindex --semantic --posted-within`: open jobs
	// whose effective posting date (COALESCE(posted_at, created_at) — the same date
	// jobview derives and the search doc's posted_ts encodes) is at or after the cutoff.
	// The in-engine embedder cannot embed the whole open catalogue in reasonable time, so
	// the semantic index covers only this fresh window; being a swap rebuild it also drops
	// jobs that have since aged out. Open-only (closed_at IS NULL): a swap rebuild never
	// holds closed jobs, so unlike ListJobsUpdatedAfter there is nothing to delete. Served
	// by jobs_open_enrich_freshness_idx (COALESCE(posted_at, created_at) DESC WHERE open).
	ListOpenJobsPostedAfter(ctx context.Context, arg ListOpenJobsPostedAfterParams) ([]Job, error)
	// The moderator review queue: every pending report, newest first, with the reporter's email
	// and the reported job's slug and title so the moderator can judge it and link to it.
	ListPendingReports(ctx context.Context) ([]ListPendingReportsRow, error)
	// The moderator review queue: every pending submission, newest first, with the submitter's
	// email so the moderator can judge provenance.
	ListPendingSubmissions(ctx context.Context) ([]ListPendingSubmissionsRow, error)
	// The open postings sharing a role cluster (company_slug + role_fingerprint) with the
	// anchor job — the "N openings across cities" list for a collapsed role. Each copy keeps
	// its own location and apply URL, so a seeker picks their city; the anchor itself is
	// included (it is one of the openings). Ordered by location. An empty-fingerprint anchor
	// clusters with no one and returns nothing.
	ListRoleClusterCopies(ctx context.Context, arg ListRoleClusterCopiesParams) ([]ListRoleClusterCopiesRow, error)
	// A user's saved searches, most recently updated first (the "My filters" picker order).
	ListSavedSearches(ctx context.Context, userID int64) ([]SavedSearch, error)
	// "My submissions": one user's submissions, newest first, whatever their status.
	// LEFT JOIN the minted job (present only once approved) to surface its public_slug,
	// so the UI can link an approved submission straight to its live vacancy page.
	ListSubmissionsByUser(ctx context.Context, submittedBy int64) ([]ListSubmissionsByUserRow, error)
	// The caller's subscriptions joined to each saved search's display name and query,
	// newest first — the "My subscriptions" view.
	ListSubscriptions(ctx context.Context, userID int64) ([]ListSubscriptionsRow, error)
	// Every board currently failing or cooled down, worst first — the operator's
	// "what's broken" query and the source of the per-run summary log.
	ListUnhealthyBoards(ctx context.Context) ([]ListUnhealthyBoardsRow, error)
	// Every job the caller has analyzed, newest first, joined to the job for display. Powers
	// the Tracking → AI fit tab. Includes closed jobs (surfaced with a badge). The stored
	// staleness stamps ride along so the handler can flag rows whose CV/job/model has since
	// changed, and the analysis blob carries the overall score + verdict the list shows.
	ListUserJobAnalyses(ctx context.Context, userID int64) ([]ListUserJobAnalysesRow, error)
	// A user's job interactions joined with the job rows, most recently touched
	// first (GREATEST ignores NULLs; viewed_at is always set). filter narrows to
	// viewed-only/saved/applied subsets; 'all' is every interaction, 'viewed' is
	// the passive history (rows neither saved nor applied). Closed jobs stay
	// listed: a user's history must not shrink when a posting closes.
	ListUserJobs(ctx context.Context, arg ListUserJobsParams) ([]ListUserJobsRow, error)
	// Every public_slug the user has interacted with (viewed_at is always set, so
	// any interaction row counts as viewed). Used by the SPA to dim already-seen
	// cards in the browse list without authenticating the public job-read path.
	// Closed jobs are included: dimming a closed posting that still shows in a
	// history surface is correct, and the browse list filters closed jobs itself.
	ListViewedJobSlugs(ctx context.Context, userID int64) ([]string, error)
	// Mark a job as applied for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or updates applied_at in place, and
	// seeds stage='applied' only when the stage is unset (an advanced stage survives
	// a re-apply, via COALESCE). When (and only when) applied_at transitions from
	// unset to set, bump the job's materialized applied_count in the same statement;
	// `prior` sees the pre-upsert applied_at, so a re-apply never re-bumps.
	MarkJobApplied(ctx context.Context, arg MarkJobAppliedParams) (MarkJobAppliedRow, error)
	// Record one expired probe: increment the strike counter and, in the same write,
	// close the job (closed_at) once it reaches the threshold the caller owns — the
	// two-strike grace that absorbs a transient death signal. Returns the new strike
	// count and closed_at so the worker can log the outcome.
	MarkLivenessExpired(ctx context.Context, arg MarkLivenessExpiredParams) (MarkLivenessExpiredRow, error)
	// Stamp notified_at on the jobs that were just delivered for a subscription, so
	// they leave the pending queue and are never sent again.
	MarkMatchesNotified(ctx context.Context, arg MarkMatchesNotifiedParams) (int64, error)
	// Mark a pending report dismissed with an optional reason, recording the deciding
	// moderator. Scoped to status='pending' (see MarkReportResolved). The job is not touched.
	MarkReportDismissed(ctx context.Context, arg MarkReportDismissedParams) (JobReport, error)
	// Mark a pending report resolved, recording the deciding moderator. Scoped to
	// status='pending' so a concurrent second decision affects no row (the service maps 0 rows
	// to ErrAlreadyDecided). The optional job close is a separate write (CloseJobByID).
	MarkReportResolved(ctx context.Context, arg MarkReportResolvedParams) (JobReport, error)
	// Mark a pending submission approved, recording the deciding moderator and the minted job.
	// Scoped to status='pending' so a concurrent second decision affects no row (the service
	// maps 0 rows to ErrAlreadyDecided). The job is minted by the service before this runs.
	MarkSubmissionApproved(ctx context.Context, arg MarkSubmissionApprovedParams) (JobSubmission, error)
	// Mark a pending submission rejected with an optional reason, recording the deciding
	// moderator. Scoped to status='pending' (see MarkSubmissionApproved). No job is created.
	MarkSubmissionRejected(ctx context.Context, arg MarkSubmissionRejectedParams) (JobSubmission, error)
	// Completion: the post was processed (jobs written, or no vacancy found). Run in
	// the same transaction as the extracted jobs' UpsertJob calls.
	MarkTelegramPostExtracted(ctx context.Context, arg MarkTelegramPostExtractedParams) error
	// Denormalize each company's curated-collection set onto its jobs, so the search
	// facet (jobs.collections) reflects current membership. Run by cmd/import-collections
	// after it writes companies.collections. updated_at is bumped so `reindex --since`
	// picks the changed rows up; the IS DISTINCT FROM guard skips unchanged rows, making
	// re-runs idempotent and cheap.
	PropagateCollectionsToJobs(ctx context.Context) (int64, error)
	// Second half of the atomic rebuild: recompute every active day from jobs. `added`
	// counts jobs by their created_at day; `removed` counts jobs by their CURRENT
	// closed_at day (NULL = still open, excluded). Days are UTC calendar dates
	// (AT TIME ZONE 'UTC') so buckets are stable regardless of session timezone. The
	// FULL OUTER JOIN yields one row per day that saw either an add or a removal.
	RebuildJobDailyStats(ctx context.Context) (int64, error)
	// The per-company slice of the role-duplicate recompute. Canon = min(id) among the
	// company's open rows sharing a role_fingerprint; the canon and any singleton/empty-fp
	// row get duplicate_of NULL, the other reposts point to the canon. Rows are never
	// deleted, so the reality counts are untouched. Scoped to one company_slug so it locks
	// only that company's rows briefly; the (company_slug, role_fingerprint) index makes the
	// aggregation a range scan. The IS DISTINCT FROM guard makes re-runs cheap and
	// idempotent, and a closed canon fails over to the next min(id) on the next run.
	RecomputeRoleDuplicatesForCompany(ctx context.Context, company string) (int64, error)
	// Count a failed crawl: bump consecutive_failures, record the error, stamp the run,
	// and RETURN the new failure count so the caller can compute the cooldown (the backoff
	// policy lives in Go, not here). The cooldown itself is applied by SetBoardCooldown.
	RecordBoardFailure(ctx context.Context, arg RecordBoardFailureParams) (int32, error)
	// A successful crawl clears the failure state and stamps freshness. Upsert so a
	// first-ever crawl creates the row.
	RecordBoardSuccess(ctx context.Context, arg RecordBoardSuccessParams) error
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed entry is never reprocessed within the same run.
	RecordEnrichmentFailure(ctx context.Context, arg RecordEnrichmentFailureParams) (RecordEnrichmentFailureRow, error)
	// Record (or refresh) a user's view of a job. Idempotent on (user_id, job_id):
	// the first view creates the row, a repeat view touches viewed_at. Returns the
	// row so the caller learns the current applied_at in the same round-trip.
	// When (and only when) the row is created for the first time — no prior
	// interaction existed — bump the job's materialized view_count in the same
	// statement. All WITH sub-statements see one snapshot, so `prior` reflects the
	// pre-upsert state regardless of execution order; a repeat view never re-bumps.
	RecordJobView(ctx context.Context, arg RecordJobViewParams) (RecordJobViewRow, error)
	// Count a failed delivery for a subscription's claimed jobs: bump attempts, record
	// the error, and dead-letter (set failed_at) once attempts reach the max. claimed_at
	// is left in place — its expiry gates the retry to a later pass and doubles as the
	// crash reaper, mirroring enrichment_outbox.
	RecordMatchDeliveryFailure(ctx context.Context, arg RecordMatchDeliveryFailureParams) error
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally left
	// in place — its expiry gates the retry to a later run and doubles as the crash reaper,
	// so a failed entry is never reprocessed within the same run. Mirrors
	// RecordEnrichmentFailure.
	RecordSemanticFailure(ctx context.Context, arg RecordSemanticFailureParams) (RecordSemanticFailureRow, error)
	// Record that a job matched a subscription. The PK (subscription_id, job_id) makes
	// this idempotent — re-scanning an already-recorded match is a no-op — so the
	// worker can re-scan recent jobs freely without ever delivering twice. Returns the
	// affected row count (1 = newly recorded, 0 = already known).
	RecordSubscriptionMatch(ctx context.Context, arg RecordSubscriptionMatchParams) (int64, error)
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed post is never reprocessed within the same run.
	RecordTelegramPostFailure(ctx context.Context, arg RecordTelegramPostFailureParams) (RecordTelegramPostFailureRow, error)
	// Recompute every company's denormalized state in one set-based pass: the open-job
	// count plus the facet arrays derived from those open jobs — regions/countries from
	// the jobs geography columns, remote_regions from those same regions but scoped to
	// remote jobs (work_mode='remote'), and domains/company_types/company_sizes from the
	// jobs.enrichment JSONB. Each array is the distinct union across the company's open
	// jobs (closed_at IS NULL), aggregated with a stable ORDER BY so the guard below
	// compares deterministically. A company with no open jobs (or no remote/enriched
	// jobs) is zeroed/emptied via COALESCE. The per-column `IS DISTINCT FROM` guard skips
	// rows already current, so re-running rewrites nothing and the affected-rows count
	// reports real churn. This is cmd/recount-companies' whole job; run periodically
	// (eventual consistency). The facet aggregates are each their own non-correlated
	// GROUP BY so the row-multiplying unnest of one array never distorts another's count.
	RefreshCompanyFacets(ctx context.Context) (int64, error)
	// Release the lease on a subscription's claimed jobs without counting an attempt,
	// so a soft-skipped delivery (e.g. Telegram not yet linked) is retried promptly on
	// a later pass instead of waiting out the lease.
	ReleaseMatchClaim(ctx context.Context, arg ReleaseMatchClaimParams) error
	// A healthy (not-expired) probe clears any accumulated strikes, so only CONSECUTIVE
	// expired probes can close a job. Guarded to the non-zero case so probing an
	// already-clean job does not churn the row.
	ResetLivenessStrikes(ctx context.Context, id int64) error
	// The job-reality repost/mass-posting counts for one role cluster: how many postings
	// of the same role (by role_fingerprint within a company) exist of any status
	// (repost_count = repost history) and how many are still open (mass_count = concurrent
	// mass-posting). A NULL/empty fingerprint is excluded so unfingerprinted rows never
	// cluster together; a lookup miss means a unique role (count 1). Used by the
	// incremental index push and the single-job detail read.
	RoleClusterCount(ctx context.Context, arg RoleClusterCountParams) (RoleClusterCountRow, error)
	// The whole-catalogue role-cluster counts in one aggregate pass, for the reindex to
	// build its (company_slug, role_fingerprint) -> counts lookup once. Only clusters with
	// more than one posting are returned (singletons are the count-1 default a lookup miss
	// already implies), keeping the map small. NULL/empty fingerprints are excluded.
	RoleClusterCountsAll(ctx context.Context) ([]RoleClusterCountsAllRow, error)
	// Save (bookmark) a job for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or refreshes saved_at in place.
	SaveJob(ctx context.Context, arg SaveJobParams) (UserJob, error)
	// Orphan-job liveness (probe-orphan-job-liveness): open jobs whose source is NOT a
	// registered ATS board provider — the sources no ingest run re-crawls and the sweep
	// therefore never closes (telegram, habr_career, geekjob, …). The caller passes the
	// ATS provider set from the sources registry; <> ALL excludes them, so a new adapter
	// never silently becomes a probe target. Closed jobs are skipped (already not open).
	SelectOrphanLivenessCandidates(ctx context.Context, atsProviders []string) ([]SelectOrphanLivenessCandidatesRow, error)
	// Apply the Go-computed cooldown window to a board (called only when the backoff
	// policy says to cool down).
	SetBoardCooldown(ctx context.Context, arg SetBoardCooldownParams) error
	// Replace a company's collection set. The import worker computes the full set in Go
	// (preserving unmanaged tags) and writes it here; updated_at is bumped for parity
	// with the other write paths.
	SetCompanyCollections(ctx context.Context, arg SetCompanyCollectionsParams) error
	SetGmailStatus(ctx context.Context, arg SetGmailStatusParams) error
	SetGmailSynced(ctx context.Context, arg SetGmailSyncedParams) error
	// Targeted enrichment write used by the enrichment command: set only the payload
	// and the provenance stamp, touching no raw source field. Kept separate from
	// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
	SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error
	// Publish a saved search as a board: set its public slug and (optional) author label,
	// owner-scoped, bumping updated_at. The service decides the slug (keeping an existing
	// one on re-share, minting a fresh one otherwise), so this sets it verbatim; a
	// collision with another board's slug raises a UNIQUE violation the service retries.
	// author_label is set verbatim (NULL clears it → anonymous). No matching owner-scoped
	// row returns no row (→ ErrNotFound).
	SetSavedSearchPublicSlug(ctx context.Context, arg SetSavedSearchPublicSlugParams) (SavedSearch, error)
	// Pause/resume a subscription, scoped to its owner. No matching owner-scoped row
	// returns no row (the handler maps that to 404).
	SetSubscriptionActive(ctx context.Context, arg SetSubscriptionActiveParams) (Subscription, error)
	// Cache the derived CV ATS review for the user (keyed to their stored CV).
	SetUserATSAnalysis(ctx context.Context, arg SetUserATSAnalysisParams) error
	// Record (or replace) the user's stored-résumé pointer, stamping the upload time.
	// Owner-scoped by id; the object key is derived from the id, never client input.
	// Also clears any cached ATS review so a new CV is never scored with a stale one.
	SetUserResume(ctx context.Context, arg SetUserResumeParams) error
	// Persist the user's derived CV embedding vector plus the identity of the embedder
	// that produced it (so a model change can mark the vector stale). Never the raw CV text.
	SetUserResumeEmbedding(ctx context.Context, arg SetUserResumeEmbeddingParams) error
	// Persist the user's derived structured résumé, stamped with the producing LLM model
	// and the résumé upload time it was derived from (passed in, not now(), so the stamp
	// matches the CV the background extraction actually read). Never the raw CV text.
	// The `resume_uploaded_at = $4` guard makes the write monotonic: a slow background
	// extraction for a since-superseded CV (its stamp no longer equals the current upload
	// time) matches no row and is dropped, so a late writer can't clobber a newer CV's
	// structure with an already-stale stamp (which Store.Structured would then hide forever).
	SetUserResumeStructured(ctx context.Context, arg SetUserResumeStructuredParams) error
	// Record that a batch of jobs' content is embedded under the given model. Run in the
	// same transaction as DeleteSemanticEntriesBatch on the success path, so a crash between
	// the index write and this stamp is safely retried (idempotent re-embed). The stamp
	// copies each job's CURRENT content_hash (nullable-safe: a NULL content_hash stamps NULL
	// so NULL IS DISTINCT FROM NULL stays false and the job is not re-enqueued forever).
	// Caveat: if an ingest commits a new content_hash in the tiny window between the embed
	// (which read the old content) and this stamp, the stamp records the NEW hash while the
	// vector reflects the old one — so the enqueue predicate sees a match and does NOT
	// re-enqueue it next run; that job carries a one-revision-stale vector until its content
	// changes AGAIN (which re-enqueues it). The window is one embed-duration and the drift
	// self-corrects on the next real change, so this is accepted over threading the exact
	// embedded hash through a nullable text[] per batch.
	StampSemanticEmbeddedBatch(ctx context.Context, arg StampSemanticEmbeddedBatchParams) error
	// The per-company slice of the cross-source aggregator suppression. An open aggregator
	// posting is marked duplicate_of an open CANONICAL ATS (non-aggregator) posting of the
	// same company, equal normalized title, and compatible country (countries overlap, or
	// either side empty — the geography dictionary is sparse, so an unresolved side must not
	// veto). The ATS row is never touched, so it stays canonical. Candidate aggregator rows
	// are those that are canonical OR already point at a non-aggregator row (i.e. suppressed
	// by THIS pass) — an aggregator repost pointed at another aggregator by the role pass is
	// left alone. A candidate with no ATS twin resolves to NULL, so a closed twin releases
	// its aggregator copy back into search/embedding/enrichment. min(id) picks a stable
	// target; the IS DISTINCT FROM guard makes re-runs cheap and idempotent. Run AFTER
	// RecomputeRoleDuplicatesForCompany so ATS reposts have already collapsed to their canon.
	SuppressAggregatorDuplicatesForCompany(ctx context.Context, arg SuppressAggregatorDuplicatesForCompanyParams) (int64, error)
	// Rebuild the companies catalogue from jobs. The companies table is derivable
	// from jobs (slug = company_slug, name = company), so after a slug-builder change
	// re-keys jobs, this re-keys companies to match. DISTINCT ON collapses a slug's
	// name variants; ON CONFLICT folds collisions and refreshes existing rows.
	SyncCompaniesFromJobs(ctx context.Context) error
	// Liveness refresh for a hydrating source's already-ingested posting (see source-ingest): the
	// crawl re-listed the offer but fetched no fresh content (detail is fetched only for new
	// offers), so refresh last_seen_at and reopen if it had been closed — WITHOUT touching the
	// content columns. A full upsert of the content-less listing would re-derive the deterministic
	// facets from an empty description and wipe the row's hydrated description/skills. This is the
	// reopen half of UpsertJob's ON CONFLICT, minus every content write. RETURNING company_slug so
	// the caller records the company into the crawled-set that scopes the post-run unseen sweep —
	// exactly as UpsertJob's write path does — otherwise a company whose offers were all touched
	// (not newly saved) would drop out of the sweep and its removed offers would never close.
	TouchJob(ctx context.Context, arg TouchJobParams) (string, error)
	// Set an application's stage and/or notes for a user, idempotently. Upserts the
	// (user, job) row (viewed_at defaults). Partial update: a NULL param leaves that
	// column unchanged (COALESCE keeps the existing value), so the caller can set the
	// stage, the notes, or both in one call. Returns the row.
	TrackJob(ctx context.Context, arg TrackJobParams) (UserJob, error)
	// Clear a job's dismissed mark without deleting the interaction row, so view/
	// apply/save history survives. No interaction row -> pgx.ErrNoRows; the handler
	// treats that as "already not dismissed", never as a failure. This is the undo
	// path for a swipe-left decision.
	UndismissJob(ctx context.Context, arg UndismissJobParams) (UserJob, error)
	// Clear a job's saved mark without deleting the interaction row, so view and
	// apply history survive unsaving. No interaction row -> pgx.ErrNoRows; the
	// handler treats that as "already not saved", never as a failure.
	UnsaveJob(ctx context.Context, arg UnsaveJobParams) (UserJob, error)
	// Remove a job from the board: drop every pipeline mark, keep viewed_at so the
	// job remains in the user's view history.
	UntrackJob(ctx context.Context, arg UntrackJobParams) (UserJob, error)
	// Targeted description rewrite for cmd/backfill-justjoin: sets the description and the refreshed
	// content_hash (recomputed in Go from the row's indexed fields with the new description) so the
	// row re-indexes. Stamps updated_at so `reindex --since` also captures it. Only the description
	// and hash move; the deterministic facets are re-derived separately by cmd/backfill-derive.
	UpdateJobDescription(ctx context.Context, arg UpdateJobDescriptionParams) (int64, error)
	// One-off backfill (cmd/backfill-derive): rewrite every deterministic dictionary
	// facet column — countries, regions, work_mode, skills, seniority, category, plus the
	// synthetic enrichment facets posting_language, employment_type, education_level,
	// english_level, and experience_years_min — from the row's raw content
	// (title/location/description) in one
	// pass, replacing the
	// three separate per-facet backfill writes. The facets are a pure function of the
	// raw fields, so this is idempotent. updated_at is deliberately left untouched
	// (like UpdateJobSlugs) so a backfill does not churn every row's timestamp. COALESCE
	// maps a nil array arg to '{}' for the NOT NULL array columns. work_mode is written
	// as given by the caller, which preserves an already-set (possibly
	// adapter-structured) value.
	UpdateJobFacets(ctx context.Context, arg UpdateJobFacetsParams) error
	// One-off backfill for a deliberate slug-builder change (see the UpsertJob note on
	// why slugs are otherwise immutable). public_slug/company_slug are deterministic
	// from the row's immutable fields, so recomputing and rewriting them is idempotent.
	UpdateJobSlugs(ctx context.Context, arg UpdateJobSlugsParams) error
	// Moderator edit of a hand-curated job, addressed by public_slug and scoped to
	// created_by IS NOT NULL so this path can only rewrite a moderator-authored posting,
	// never an automated-source (ingest/telegram) one — regardless of the declared source.
	// The partial merge (nil = unchanged) and facet re-derivation happen in the service; this
	// query writes the resulting full field set, so geography/skills/company_slug stay
	// consistent with the edited content. The source identity (url/external_id/public_slug)
	// is deliberately NOT updatable here. The company row is upserted when a slug is present,
	// so "a company's jobs" stays resolvable. updated_by records the acting moderator. Returns
	// no row when the slug is missing or not a manual job (the caller maps that to 404).
	// closed_at is deliberately NOT touched: an edit is a content fix, not a lifecycle change.
	// Reopening a closed posting is the re-create (same-URL UpsertManualJob) path's job, so a
	// content edit never resurrects a job the sweep/liveness worker closed.
	UpdateManualJob(ctx context.Context, arg UpdateManualJobParams) (Job, error)
	// Overwrite a saved search's name and/or query, scoped to its owner, bumping
	// updated_at. Partial update: a NULL param leaves that column unchanged (COALESCE),
	// so the caller can rename, overwrite the filters, or both in one call. An empty
	// query string is a real value (not NULL), so "save the unfiltered view" is honored.
	// No matching owner-scoped row returns no row (the handler maps that to 404).
	UpdateSavedSearch(ctx context.Context, arg UpdateSavedSearchParams) (SavedSearch, error)
	// Apply one external-dataset company-info record, matched by slug. A new slug is
	// inserted as a reference row (is_reference = true) with no jobs; an existing slug
	// (job-backed or a prior reference) has only its company-info columns refreshed —
	// name, job_count, collections, is_reference, and the job-derived facet arrays are
	// left untouched. Idempotent: re-running the same record rewrites the same values.
	UpsertCompanyInfo(ctx context.Context, arg UpsertCompanyInfoParams) error
	// Idempotent by (user_id, gmail_msg_id): a re-sync of the same message is a no-op.
	UpsertEmail(ctx context.Context, arg UpsertEmailParams) error
	// Connect (or reconnect) a user's Gmail: store the encrypted refresh token and
	// mark connected, preserving the sync cursor on reconnect.
	UpsertGmailConnection(ctx context.Context, arg UpsertGmailConnectionParams) error
	// Single atomic write: upsert the company (only when the slug is non-empty,
	// via the WHERE on the SELECT) and the job together, keeping the "one write =
	// one job" property of the pipeline's write path.
	// The enrichment columns are deliberately NOT written here: ingest carries no
	// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
	// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
	// enrichment worker) is the sole writer of those columns.
	// countries/regions ARE written here: they are source facts parsed from the
	// location, not enrichment. COALESCE maps a nil arg to '{}', so a location that
	// yields no geography stores empty arrays (the columns are NOT NULL).
	// content_hash is the incremental-index change signal (internal/jobhash): the
	// `existing` CTE captures the row's pre-update hash (snapshot from before this
	// statement), so RETURNING can report whether the write inserted a new row
	// (`inserted`) or changed its searchable content (`changed`, true on insert and
	// for a legacy NULL hash). A re-ingest that only bumps last_seen_at reports both
	// false and needs no re-push to the search index.
	// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
	// at insert and is the row's stable public identity. Re-ingest of the same
	// (source, external_id) must not rewrite it, so external links stay valid even
	// if the slug builder changes later (that would be a deliberate migration).
	UpsertJob(ctx context.Context, arg UpsertJobParams) (UpsertJobRow, error)
	// Moderator-authored write: the hand-curated analogue of UpsertJob. source is the
	// posting's real origin (e.g. 'workatastartup'), supplied by the moderator and
	// defaulting to 'manual'; the dedup key is (source, external_id = url), so re-POSTing
	// the same URL updates the row idempotently instead of duplicating it. The manual
	// provenance is recorded by created_by (set here, NULL for every automated source) —
	// not by the source value. created_by is stamped once at insert; updated_by is
	// (re)written on the conflict update. Like UpsertJob, public_slug is minted once and
	// never rewritten, and the enrichment columns are left to SetJobEnrichment. The conflict
	// reopens a previously closed posting (closed_at = NULL) since the moderator is
	// re-asserting it.
	UpsertManualJob(ctx context.Context, arg UpsertManualJobParams) (Job, error)
	// Link (or relink) a user's Telegram chat, captured from the inbound /start. One
	// row per user; relinking from a different chat overwrites the chat_id.
	UpsertTelegramLink(ctx context.Context, arg UpsertTelegramLinkParams) error
	// Create-or-replace the cached analysis for a (user, job). The composite PRIMARY KEY
	// makes it idempotent: a recompute overwrites the analysis, model, and both staleness
	// stamps. created_at is deliberately NOT re-bumped on conflict, so it records the
	// FIRST-analysis time — the fit-analysis quota counts distinct jobs a user first
	// analyzed within a rolling window, and a recompute must not re-age its row into it.
	// analysis is the sanitized jobfit.Analysis JSON.
	UpsertUserJobAnalysis(ctx context.Context, arg UpsertUserJobAnalysisParams) error
	// Create-or-replace the user's one profile. The PRIMARY KEY (user_id) makes this an
	// idempotent upsert: first save inserts, later saves overwrite specializations/skills/
	// location_preferences and bump updated_at. All fields are already normalized by the
	// service; location_preferences is a validated JSONB block or NULL (no preferences).
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error)
	// Apply one yc-oss directory entry, matched by slug. A new slug is inserted as a
	// reference row (is_reference = true) with no jobs; an existing slug (job-backed or a
	// prior reference) has its company-info columns plus the curated yc_batch/yc_status
	// facets refreshed — name, job_count, collections, is_reference, and the job-derived
	// facet arrays (regions/remote_regions/countries/domains/company_types/company_sizes)
	// are left untouched. Idempotent: re-running the same entry rewrites the same values.
	UpsertYCCompany(ctx context.Context, arg UpsertYCCompanyParams) error
}

var _ Querier = (*Queries)(nil)
