// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Resolve a presented token (by its SHA-256 hash) to the owning user id, enforcing
	// expiry and touching last_used_at in one atomic statement. No row means the key is
	// unknown, revoked, or expired; the caller treats pgx.ErrNoRows as 401.
	AuthenticateAPIKey(ctx context.Context, tokenHash string) (int64, error)
	// Claim a batch of live, unleased entries for OPEN jobs, freshest job first, by
	// stamping claimed_at. The jobs join lets the claim order by posting freshness and
	// skip closed jobs, so LLM budget goes to live postings users will actually see.
	// Freshness is COALESCE(posted_at, created_at): jobs without a source post date
	// (telegram/linksource and some ATS) fall back to ingest time, so they rank by
	// recency instead of starving behind every dated job under NULLS LAST. FOR UPDATE OF o
	// locks only outbox rows (a bare FOR UPDATE would also lock jobs, making concurrent
	// claim waves contend); SKIP LOCKED lets concurrent workers take disjoint rows; the
	// lease predicate reclaims entries whose worker died (stale claimed_at), so no
	// separate reaper process is needed.
	ClaimEnrichmentBatch(ctx context.Context, arg ClaimEnrichmentBatchParams) ([]ClaimEnrichmentBatchRow, error)
	// Lease a batch of pending, live matches for active subscriptions by stamping
	// claimed_at, oldest-claimable first, ordered by subscription so the worker can
	// group a subscription's matches into one digest. FOR UPDATE OF m locks only match
	// rows; SKIP LOCKED lets overlapping passes take disjoint rows so a digest is sent
	// at most once; the lease predicate reclaims rows whose sender died (stale
	// claimed_at), so no separate reaper is needed. The digest is sent OUTSIDE this
	// claim's transaction, so no network call is held inside a row lock.
	ClaimSubscriptionMatches(ctx context.Context, arg ClaimSubscriptionMatchesParams) ([]ClaimSubscriptionMatchesRow, error)
	// Claim a batch of pending posts by stamping claimed_at. SKIP LOCKED lets
	// concurrent workers take disjoint rows; the lease predicate reclaims posts whose
	// worker died (stale claimed_at), so no separate reaper process is needed.
	// Oldest post first so a backlog drains in posting order.
	ClaimTelegramPosts(ctx context.Context, arg ClaimTelegramPostsParams) ([]ClaimTelegramPostsRow, error)
	// Reset a tracked job to the wishlist: drop stage and applied state, keep saved/viewed/notes.
	ClearJobProgress(ctx context.Context, arg ClearJobProgressParams) (UserJob, error)
	// Unpublish a board: clear the slug and author label, owner-scoped. Returns the
	// affected row count: 1 for an owned row (whether or not it was shared — unshare is an
	// idempotent no-op when already private), 0 when missing or not the caller's (→ 404).
	ClearSavedSearchPublicSlug(ctx context.Context, arg ClearSavedSearchPublicSlugParams) (int64, error)
	// Soft-close one job now (see job-lifecycle): a moderator resolving a report with
	// close_job=true. The third writer of closed_at, alongside the ingest sweep and the
	// liveness probe. WHERE closed_at IS NULL keeps it idempotent — a second close on an
	// already-closed job is a no-op, never an error, so it never fights the report's own
	// status guard. A later ingest upsert may legitimately reopen a board job (reopen-on-
	// reappear); that is the lifecycle's existing behavior, not a conflict.
	CloseJobByID(ctx context.Context, id int64) (int64, error)
	// Stream-driven close (see job-lifecycle): a self-closing feed source (e.g. jobtech)
	// learns of a removed posting from its incremental stream and closes it by identity,
	// rather than relying on the post-run unseen sweep (which it opts out of, since an
	// incremental stream re-reports only changed ads and so never refreshes last_seen_at
	// for the still-open ones). WHERE closed_at IS NULL keeps it idempotent; a later
	// upsert of the same (source, external_id) reopens it if the posting reappears.
	CloseJobBySourceExternalID(ctx context.Context, arg CloseJobBySourceExternalIDParams) (int64, error)
	// Post-ingest sweep (see job-lifecycle spec): close every open job of ONE source not
	// seen since the cutoff. Scoped by source because ingest runs per provider — a
	// greenhouse run must not close jobs another provider owns and didn't crawl. The
	// caller owns the grace window (cutoff = now() - window) and the "run ingested
	// something" guard, so a failed crawl never mass-closes that source's catalogue.
	CloseUnseenJobs(ctx context.Context, arg CloseUnseenJobsParams) (int64, error)
	// The slug ending every full chunk of `chunk_size` companies (ordered by slug),
	// excluding the final row, so the sitemap index can list each company sub-sitemap's
	// keyset cursor.
	CompanySitemapBoundaries(ctx context.Context, chunkSize int64) ([]string, error)
	// Total companies matching the same optional name + facet filters as ListCompanies,
	// so search/filter pagination reports the filtered total. Keep this WHERE identical
	// to ListCompanies.
	CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error)
	CountJobs(ctx context.Context) (int64, error)
	// Per-stage application counts for the Pipeline snapshot. An application is any
	// row the user applied to or staged (saved-only rows are excluded); a row with
	// applied_at set but no stage groups under a NULL stage. The Go layer folds these
	// rows into the pipeline buckets.
	CountMyJobsByStage(ctx context.Context, userID int64) ([]CountMyJobsByStageRow, error)
	// How many saved searches a user has — the per-user cap is enforced against this in
	// the service before a create.
	CountSavedSearches(ctx context.Context, userID int64) (int64, error)
	// How many profiles a user has — the per-user cap is enforced against this in the
	// service before a create.
	CountSearchProfiles(ctx context.Context, userID int64) (int64, error)
	// Per-filter row counts for the my-jobs tabs, in one aggregate pass. "all" is
	// every interaction row; "viewed" is the view-only subset (neither saved nor
	// applied), matching the ListUserJobs filter. "board" counts jobs on the Kanban
	// board (saved, applied, or stage set), matching the ListUserJobs board filter.
	CountUserJobs(ctx context.Context, userID int64) (CountUserJobsRow, error)
	// Create an API key for a user. The caller passes the SHA-256 token_hash and the
	// display token_prefix; the plaintext token is shown once and never stored.
	// expires_at NULL means the key never expires. Returns display fields only, never
	// the hash.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	// File a user complaint about a job into the moderation queue as 'pending'. The partial
	// unique index on (reported_by, job_id) WHERE status='pending' rejects a second open report
	// of the same job by the same user (the repository maps that unique violation to a 409).
	CreateReport(ctx context.Context, arg CreateReportParams) (JobReport, error)
	// Create a saved search for a user. The UNIQUE (user_id, name) constraint rejects a
	// duplicate name (surfaced by the repository as a duplicate-name error). Returns the row.
	CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error)
	// Create a profile for a user. The UNIQUE (user_id, name) constraint rejects a
	// duplicate name (surfaced by the repository as a duplicate-name error). Specializations
	// and skills are already normalized by the service. Returns the row.
	CreateSearchProfile(ctx context.Context, arg CreateSearchProfileParams) (SearchProfile, error)
	// Insert a user-contributed vacancy into the moderation queue as 'pending'. The partial
	// unique index on lower(url) WHERE status='pending' rejects a second pending submission of
	// the same URL (the repository maps that unique violation to a 409).
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (JobSubmission, error)
	// Subscribe one of the caller's saved searches to a delivery channel. The SELECT
	// from saved_searches enforces ownership in the same statement: a saved_search_id
	// the caller does not own yields no row (sqlc :one returns ErrNoRows, mapped to
	// 404). A second subscription for the same (saved_search, channel) violates the
	// UNIQUE constraint (surfaced as a 409). Returns the created row.
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// Register a new account. email is stored as given (the handler lowercases it);
	// the unique index on lower(email) rejects duplicates regardless of case. role is
	// returned so the new account's wire shape carries it (always 'user' at creation).
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Link a provider identity to an account (first OAuth sign-in). The composite
	// primary key rejects a duplicate identity.
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error
	// Revoke (delete) a key, scoped to its owner so a user can only delete their own.
	// Returns the affected row count: 0 means the key does not exist or is not the
	// caller's (the handler maps that to 404).
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
	DeleteEnrichmentEntry(ctx context.Context, id int64) error
	// Drop companies no longer referenced by any job — the stale rows left behind
	// when a slug-builder change re-keys jobs onto new slugs.
	DeleteOrphanCompanies(ctx context.Context) (int64, error)
	// Delete a saved search, scoped to its owner so a user can only delete their own.
	// Returns the affected row count: 0 means it does not exist or is not the caller's
	// (the handler maps that to 404).
	DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error)
	// Delete a profile, scoped to its owner so a user can only delete their own. Returns
	// the affected row count: 0 means it does not exist or is not the caller's (the
	// handler maps that to 404).
	DeleteSearchProfile(ctx context.Context, arg DeleteSearchProfileParams) (int64, error)
	// Unsubscribe, scoped to its owner. Returns the affected row count: 0 means it
	// does not exist or is not the caller's (the handler maps that to 404). The match
	// ledger cascades away with the subscription.
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error)
	// Unlink Telegram. Returns the affected row count: 0 means there was no link.
	DeleteTelegramLink(ctx context.Context, userID int64) (int64, error)
	// Dismiss (swipe away) a job for a user in the swipe deck. Idempotent and
	// independent of a prior view: it inserts the row (viewed_at defaults) or
	// refreshes dismissed_at in place.
	DismissJob(ctx context.Context, arg DismissJobParams) (UserJob, error)
	// Transactional-outbox enqueue for the ingest write path: queue this one job for
	// enrichment, gated on the same condition the backfill uses (unenriched or below the
	// target schema version), so an already-enriched job is not re-queued. Idempotent via
	// the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
	// job's UpsertJob so a newly ingested job is queued atomically with its write.
	EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error)
	// Idempotent backfill: enqueue every OPEN job that is unenriched or below the target
	// schema version. Closed jobs (closed_at IS NOT NULL) are skipped — a dead posting no
	// user will see should not consume LLM budget. ON CONFLICT keeps exactly one entry per
	// (job_id, target_version), so running this every command invocation never duplicates
	// work.
	EnqueuePendingJobs(ctx context.Context, targetVersion int32) (int64, error)
	// Job ids the user has already judged (saved or dismissed) — the swipe deck's
	// exclusion set. Ordered most-recently-judged first and capped ($2) so the deck's
	// `id NOT IN (...)` search filter stays bounded; the overflow risk is only an
	// occasional re-shown long-ago-judged job, never a correctness problem.
	ExcludedJobIDs(ctx context.Context, arg ExcludedJobIDsParams) ([]int64, error)
	// SELECT * (not an explicit column list) so the generated row stays db.Company as
	// the table grows columns (e.g. collections); an explicit subset makes sqlc emit a
	// distinct row type and breaks the company-detail handler on every new column.
	GetCompany(ctx context.Context, slug string) (Company, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetJobBySlug(ctx context.Context, publicSlug string) (Job, error)
	// Slim slug->id lookup for the view/apply interaction path, which needs only the
	// internal id (the user_jobs FK) and must not drag the wide description/enrichment
	// columns over the wire on every silent view. GetJobBySlug (SELECT *) stays for the
	// public detail handler that renders the whole row.
	GetJobIDBySlug(ctx context.Context, publicSlug string) (int64, error)
	// The display fields for the jobs in a digest, freshest first.
	GetJobsForDigest(ctx context.Context, jobIds []int64) ([]GetJobsForDigestRow, error)
	// Public read of a shared board by its slug — no auth, no owner-scoping. Exposes only
	// the board's display fields; owner columns (user_id) are never selected. A NULL slug
	// never equals the param, so private sets are unreachable. No row → 404.
	GetPublicBoardBySlug(ctx context.Context, publicSlug pgtype.Text) (GetPublicBoardBySlugRow, error)
	// Load a single report by id for the review path. The resolve/dismiss flow guards the
	// status in the service; the Mark* queries are additionally scoped to status='pending' as
	// defense-in-depth against a concurrent second decision.
	GetReport(ctx context.Context, id int64) (JobReport, error)
	// Fetch one of a user's saved searches, owner-scoped. Used by the share use case to
	// read the current name/public_slug before deciding whether to keep an existing slug
	// or mint a new one. No matching row (wrong id or another user's) returns no row (the
	// service maps that to ErrNotFound).
	GetSavedSearch(ctx context.Context, arg GetSavedSearchParams) (SavedSearch, error)
	// Load a single submission by id for the review path. The approve/reject flow guards the
	// status in the service; the Mark* queries are additionally scoped to status='pending' as
	// defense-in-depth against a concurrent second decision.
	GetSubmission(ctx context.Context, id int64) (JobSubmission, error)
	// The delivery context for one subscription: channel + destination, the saved
	// search name (for the digest heading), and the user's linked Telegram chat (NULL
	// when unlinked → the worker soft-skips telegram delivery rather than failing it).
	GetSubscriptionForDelivery(ctx context.Context, id int64) (GetSubscriptionForDeliveryRow, error)
	// The caller's linked Telegram chat (link-status endpoint + delivery resolution).
	GetTelegramLink(ctx context.Context, userID int64) (TelegramLink, error)
	// Login lookup. Case-insensitive on email; returns password_hash so the handler
	// can verify the password (and reject accounts that have none). role feeds the
	// post-login wire shape.
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	// Profile lookup for the authenticated user. Never selects password_hash. role is
	// included so /auth/me can tell a client whether to surface moderator-only UI.
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// OAuth sign-in fast path: resolve a provider identity straight to its user.
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (GetUserByIdentityRow, error)
	// Slim role lookup for the RequireRole authorization middleware: it runs on every
	// request to a role-gated endpoint and needs only the role, so it does not drag the
	// full user row (the GetJobIDBySlug precedent for a hot-path read).
	GetUserRole(ctx context.Context, id int64) (string, error)
	// Crawl write path: store a fetched post once. ON CONFLICT DO NOTHING makes
	// re-crawling idempotent — a stored post (pending, done, or dead-lettered) is
	// never reset. extracted_at is non-NULL when the ingest prefilter already
	// decided the post holds no vacancy, so it is recorded but never queued.
	InsertTelegramPost(ctx context.Context, arg InsertTelegramPostParams) (int64, error)
	// The id ending every full chunk of `chunk_size` open jobs (ordered by id),
	// excluding the final row, so the sitemap index can list each sub-sitemap's keyset
	// cursor without the client walking the whole catalogue.
	JobSitemapBoundaries(ctx context.Context, chunkSize int64) ([]int64, error)
	// A user's API keys, newest first. Metadata only — never the token_hash.
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error)
	// Every active subscription with the data the matching worker needs: the saved
	// search query to translate into a filter, plus identity/channel for fan-out. The
	// worker groups these by canonical(query) so each distinct filter hits the search
	// index once regardless of how many subscriptions share it.
	ListActiveSubscriptions(ctx context.Context) ([]ListActiveSubscriptionsRow, error)
	// Catalog page: companies with their job counts, most active first. The job count
	// is read from the denormalized companies.job_count column (maintained by
	// cmd/recount-companies), so this read does not join jobs. Ordered by job_count
	// DESC, name — the same ordering the sidebar company typeahead consumes. An empty
	// `search` short-circuits the ILIKE, so the same prepared statement serves both
	// the full list and a name search (`search` is a case-insensitive substring of the
	// name). Each facet param is a text[] filtered by array overlap (&&): an empty
	// array short-circuits to no constraint, non-empty values are OR-ed within the
	// facet, and the facets AND together (and with the name search). CountCompanies
	// MUST keep an identical WHERE so the filtered total matches the page.
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	// All companies with their current collection membership. cmd/import-collections
	// reads this to know the existing company slugs (the match target) and each
	// company's current tags (so it can reconcile only the tags it manages, leaving any
	// others untouched).
	ListCompanyCollections(ctx context.Context) ([]ListCompanyCollectionsRow, error)
	// Slim keyset page of companies for the sitemap, cursored by the slug primary key
	// (first chunk keyed by the empty string, which sorts before every slug).
	ListCompanySitemap(ctx context.Context, arg ListCompanySitemapParams) ([]ListCompanySitemapRow, error)
	// Slim keyset page for the sitemap: only the fields a sitemap URL needs, open jobs
	// only, cursored by the immutable primary key so a chunk is a bounded index scan
	// (never a deep OFFSET over millions of rows).
	ListJobSitemap(ctx context.Context, arg ListJobSitemapParams) ([]ListJobSitemapRow, error)
	// Newest-added first: created_at is when the job entered the catalogue (stable
	// across re-ingests), so fresh ingests surface on top regardless of how old the
	// platform's posted_at is. id breaks ties within one ingest batch.
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error)
	// Keyset scan for the reindex command: pages by the immutable primary key, so
	// concurrent inserts/updates (which shift posted_at ordering) cannot make the
	// scan skip or repeat rows the way OFFSET pagination would.
	ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error)
	// Incremental keyset scan for `reindex --since`: like ListJobsByIDAfter but only
	// rows changed at or after the cutoff. Every write path (UpsertJob, the close
	// sweeps, SetJobEnrichment, UpdateJobFacets) stamps updated_at = now(), so this
	// captures new, re-crawled, closed, and re-enriched jobs — enough to bring an
	// index current without re-pushing the whole table. Returns closed rows too, so
	// the caller deletes a freshly-closed job from the index.
	ListJobsUpdatedAfter(ctx context.Context, arg ListJobsUpdatedAfterParams) ([]Job, error)
	// The moderator review queue: every pending report, newest first, with the reporter's email
	// and the reported job's slug and title so the moderator can judge it and link to it.
	ListPendingReports(ctx context.Context) ([]ListPendingReportsRow, error)
	// The moderator review queue: every pending submission, newest first, with the submitter's
	// email so the moderator can judge provenance.
	ListPendingSubmissions(ctx context.Context) ([]ListPendingSubmissionsRow, error)
	// A user's saved searches, most recently updated first (the "My filters" picker order).
	ListSavedSearches(ctx context.Context, userID int64) ([]SavedSearch, error)
	// A user's search profiles, most recently updated first (the profile picker order).
	ListSearchProfiles(ctx context.Context, userID int64) ([]SearchProfile, error)
	// "My submissions": one user's submissions, newest first, whatever their status.
	// LEFT JOIN the minted job (present only once approved) to surface its public_slug,
	// so the UI can link an approved submission straight to its live vacancy page.
	ListSubmissionsByUser(ctx context.Context, submittedBy int64) ([]ListSubmissionsByUserRow, error)
	// The caller's subscriptions joined to each saved search's display name and query,
	// newest first — the "My subscriptions" view.
	ListSubscriptions(ctx context.Context, userID int64) ([]ListSubscriptionsRow, error)
	// A user's job interactions joined with the job rows, most recently touched
	// first (GREATEST ignores NULLs; viewed_at is always set). filter narrows to
	// viewed-only/saved/applied subsets; 'all' is every interaction, 'viewed' is
	// the passive history (rows neither saved nor applied). Closed jobs stay
	// listed: a user's history must not shrink when a posting closes.
	ListUserJobs(ctx context.Context, arg ListUserJobsParams) ([]ListUserJobsRow, error)
	// Every public_slug the user has interacted with (viewed_at is always set, so
	// any interaction row counts as viewed). Used by the SPA to dim already-seen
	// cards in the browse list without authenticating the public job-read path.
	// Closed jobs are included: dimming a closed posting that still shows in a
	// history surface is correct, and the browse list filters closed jobs itself.
	ListViewedJobSlugs(ctx context.Context, userID int64) ([]string, error)
	// Mark a job as applied for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or updates applied_at in place, and
	// seeds stage='applied' only when the stage is unset (an advanced stage survives
	// a re-apply, via COALESCE).
	MarkJobApplied(ctx context.Context, arg MarkJobAppliedParams) (UserJob, error)
	// Record one expired probe: increment the strike counter and, in the same write,
	// close the job (closed_at) once it reaches the threshold the caller owns — the
	// two-strike grace that absorbs a transient death signal. Returns the new strike
	// count and closed_at so the worker can log the outcome.
	MarkLivenessExpired(ctx context.Context, arg MarkLivenessExpiredParams) (MarkLivenessExpiredRow, error)
	// Stamp notified_at on the jobs that were just delivered for a subscription, so
	// they leave the pending queue and are never sent again.
	MarkMatchesNotified(ctx context.Context, arg MarkMatchesNotifiedParams) (int64, error)
	// Mark a pending report dismissed with an optional reason, recording the deciding
	// moderator. Scoped to status='pending' (see MarkReportResolved). The job is not touched.
	MarkReportDismissed(ctx context.Context, arg MarkReportDismissedParams) (JobReport, error)
	// Mark a pending report resolved, recording the deciding moderator. Scoped to
	// status='pending' so a concurrent second decision affects no row (the service maps 0 rows
	// to ErrAlreadyDecided). The optional job close is a separate write (CloseJobByID).
	MarkReportResolved(ctx context.Context, arg MarkReportResolvedParams) (JobReport, error)
	// Mark a pending submission approved, recording the deciding moderator and the minted job.
	// Scoped to status='pending' so a concurrent second decision affects no row (the service
	// maps 0 rows to ErrAlreadyDecided). The job is minted by the service before this runs.
	MarkSubmissionApproved(ctx context.Context, arg MarkSubmissionApprovedParams) (JobSubmission, error)
	// Mark a pending submission rejected with an optional reason, recording the deciding
	// moderator. Scoped to status='pending' (see MarkSubmissionApproved). No job is created.
	MarkSubmissionRejected(ctx context.Context, arg MarkSubmissionRejectedParams) (JobSubmission, error)
	// Completion: the post was processed (jobs written, or no vacancy found). Run in
	// the same transaction as the extracted jobs' UpsertJob calls.
	MarkTelegramPostExtracted(ctx context.Context, arg MarkTelegramPostExtractedParams) error
	// Denormalize each company's curated-collection set onto its jobs, so the search
	// facet (jobs.collections) reflects current membership. Run by cmd/import-collections
	// after it writes companies.collections. updated_at is bumped so `reindex --since`
	// picks the changed rows up; the IS DISTINCT FROM guard skips unchanged rows, making
	// re-runs idempotent and cheap.
	PropagateCollectionsToJobs(ctx context.Context) (int64, error)
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed entry is never reprocessed within the same run.
	RecordEnrichmentFailure(ctx context.Context, arg RecordEnrichmentFailureParams) (RecordEnrichmentFailureRow, error)
	// Record (or refresh) a user's view of a job. Idempotent on (user_id, job_id):
	// the first view creates the row, a repeat view touches viewed_at. Returns the
	// row so the caller learns the current applied_at in the same round-trip.
	RecordJobView(ctx context.Context, arg RecordJobViewParams) (UserJob, error)
	// Count a failed delivery for a subscription's claimed jobs: bump attempts, record
	// the error, and dead-letter (set failed_at) once attempts reach the max. claimed_at
	// is left in place — its expiry gates the retry to a later pass and doubles as the
	// crash reaper, mirroring enrichment_outbox.
	RecordMatchDeliveryFailure(ctx context.Context, arg RecordMatchDeliveryFailureParams) error
	// Record that a job matched a subscription. The PK (subscription_id, job_id) makes
	// this idempotent — re-scanning an already-recorded match is a no-op — so the
	// worker can re-scan recent jobs freely without ever delivering twice. Returns the
	// affected row count (1 = newly recorded, 0 = already known).
	RecordSubscriptionMatch(ctx context.Context, arg RecordSubscriptionMatchParams) (int64, error)
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed post is never reprocessed within the same run.
	RecordTelegramPostFailure(ctx context.Context, arg RecordTelegramPostFailureParams) (RecordTelegramPostFailureRow, error)
	// Recompute every company's denormalized state in one set-based pass: the open-job
	// count plus the facet arrays derived from those open jobs — regions/countries from
	// the jobs geography columns, and domains/company_types/company_sizes from the
	// jobs.enrichment JSONB. Each array is the distinct union across the company's open
	// jobs (closed_at IS NULL), aggregated with a stable ORDER BY so the guard below
	// compares deterministically. A company with no open jobs (or no enriched jobs) is
	// zeroed/emptied via COALESCE. The per-column `IS DISTINCT FROM` guard skips rows
	// already current, so re-running rewrites nothing and the affected-rows count reports
	// real churn. This is cmd/recount-companies' whole job; run periodically (eventual
	// consistency). The facet aggregates are each their own non-correlated GROUP BY so
	// the row-multiplying unnest of one array never distorts another's count.
	RefreshCompanyFacets(ctx context.Context) (int64, error)
	// Release the lease on a subscription's claimed jobs without counting an attempt,
	// so a soft-skipped delivery (e.g. Telegram not yet linked) is retried promptly on
	// a later pass instead of waiting out the lease.
	ReleaseMatchClaim(ctx context.Context, arg ReleaseMatchClaimParams) error
	// A healthy (not-expired) probe clears any accumulated strikes, so only CONSECUTIVE
	// expired probes can close a job. Guarded to the non-zero case so probing an
	// already-clean job does not churn the row.
	ResetLivenessStrikes(ctx context.Context, id int64) error
	// Save (bookmark) a job for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or refreshes saved_at in place.
	SaveJob(ctx context.Context, arg SaveJobParams) (UserJob, error)
	// Orphan-job liveness (probe-orphan-job-liveness): open jobs whose source is NOT a
	// registered ATS board provider — the sources no ingest run re-crawls and the sweep
	// therefore never closes (telegram, habr_career, geekjob, …). The caller passes the
	// ATS provider set from the sources registry; <> ALL excludes them, so a new adapter
	// never silently becomes a probe target. Closed jobs are skipped (already not open).
	SelectOrphanLivenessCandidates(ctx context.Context, atsProviders []string) ([]SelectOrphanLivenessCandidatesRow, error)
	// Replace a company's collection set. The import worker computes the full set in Go
	// (preserving unmanaged tags) and writes it here; updated_at is bumped for parity
	// with the other write paths.
	SetCompanyCollections(ctx context.Context, arg SetCompanyCollectionsParams) error
	// Targeted enrichment write used by the enrichment command: set only the payload
	// and the provenance stamp, touching no raw source field. Kept separate from
	// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
	SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error
	// Publish a saved search as a board: set its public slug and (optional) author label,
	// owner-scoped, bumping updated_at. The service decides the slug (keeping an existing
	// one on re-share, minting a fresh one otherwise), so this sets it verbatim; a
	// collision with another board's slug raises a UNIQUE violation the service retries.
	// author_label is set verbatim (NULL clears it → anonymous). No matching owner-scoped
	// row returns no row (→ ErrNotFound).
	SetSavedSearchPublicSlug(ctx context.Context, arg SetSavedSearchPublicSlugParams) (SavedSearch, error)
	// Pause/resume a subscription, scoped to its owner. No matching owner-scoped row
	// returns no row (the handler maps that to 404).
	SetSubscriptionActive(ctx context.Context, arg SetSubscriptionActiveParams) (Subscription, error)
	// Rebuild the companies catalogue from jobs. The companies table is derivable
	// from jobs (slug = company_slug, name = company), so after a slug-builder change
	// re-keys jobs, this re-keys companies to match. DISTINCT ON collapses a slug's
	// name variants; ON CONFLICT folds collisions and refreshes existing rows.
	SyncCompaniesFromJobs(ctx context.Context) error
	// Set an application's stage and/or notes for a user, idempotently. Upserts the
	// (user, job) row (viewed_at defaults). Partial update: a NULL param leaves that
	// column unchanged (COALESCE keeps the existing value), so the caller can set the
	// stage, the notes, or both in one call. Returns the row.
	TrackJob(ctx context.Context, arg TrackJobParams) (UserJob, error)
	// Clear a job's dismissed mark without deleting the interaction row, so view/
	// apply/save history survives. No interaction row -> pgx.ErrNoRows; the handler
	// treats that as "already not dismissed", never as a failure. This is the undo
	// path for a swipe-left decision.
	UndismissJob(ctx context.Context, arg UndismissJobParams) (UserJob, error)
	// Clear a job's saved mark without deleting the interaction row, so view and
	// apply history survive unsaving. No interaction row -> pgx.ErrNoRows; the
	// handler treats that as "already not saved", never as a failure.
	UnsaveJob(ctx context.Context, arg UnsaveJobParams) (UserJob, error)
	// Remove a job from the board: drop every pipeline mark, keep viewed_at so the
	// job remains in the user's view history.
	UntrackJob(ctx context.Context, arg UntrackJobParams) (UserJob, error)
	// One-off backfill (cmd/backfill-derive): rewrite every deterministic dictionary
	// facet column — countries, regions, work_mode, skills, seniority, category, plus the
	// synthetic enrichment facets posting_language, employment_type, education_level,
	// experience_years_min, and remote_unspecified — from the row's raw content
	// (title/location/description) in one
	// pass, replacing the
	// three separate per-facet backfill writes. The facets are a pure function of the
	// raw fields, so this is idempotent. updated_at is deliberately left untouched
	// (like UpdateJobSlugs) so a backfill does not churn every row's timestamp. COALESCE
	// maps a nil array arg to '{}' for the NOT NULL array columns. work_mode is written
	// as given by the caller, which preserves an already-set (possibly
	// adapter-structured) value.
	UpdateJobFacets(ctx context.Context, arg UpdateJobFacetsParams) error
	// One-off backfill for a deliberate slug-builder change (see the UpsertJob note on
	// why slugs are otherwise immutable). public_slug/company_slug are deterministic
	// from the row's immutable fields, so recomputing and rewriting them is idempotent.
	UpdateJobSlugs(ctx context.Context, arg UpdateJobSlugsParams) error
	// Moderator edit of a hand-curated job, addressed by public_slug and scoped to
	// created_by IS NOT NULL so this path can only rewrite a moderator-authored posting,
	// never an automated-source (ingest/telegram) one — regardless of the declared source.
	// The partial merge (nil = unchanged) and facet re-derivation happen in the service; this
	// query writes the resulting full field set, so geography/skills/company_slug stay
	// consistent with the edited content. The source identity (url/external_id/public_slug)
	// is deliberately NOT updatable here. The company row is upserted when a slug is present,
	// so "a company's jobs" stays resolvable. updated_by records the acting moderator. Returns
	// no row when the slug is missing or not a manual job (the caller maps that to 404).
	// closed_at is deliberately NOT touched: an edit is a content fix, not a lifecycle change.
	// Reopening a closed posting is the re-create (same-URL UpsertManualJob) path's job, so a
	// content edit never resurrects a job the sweep/liveness worker closed.
	UpdateManualJob(ctx context.Context, arg UpdateManualJobParams) (Job, error)
	// Overwrite a saved search's name and/or query, scoped to its owner, bumping
	// updated_at. Partial update: a NULL param leaves that column unchanged (COALESCE),
	// so the caller can rename, overwrite the filters, or both in one call. An empty
	// query string is a real value (not NULL), so "save the unfiltered view" is honored.
	// No matching owner-scoped row returns no row (the handler maps that to 404).
	UpdateSavedSearch(ctx context.Context, arg UpdateSavedSearchParams) (SavedSearch, error)
	// Overwrite a profile's name, specializations, and/or skills, scoped to its owner,
	// bumping updated_at. Partial update: a NULL param leaves that column unchanged
	// (COALESCE), so the caller can rename, re-specialize, replace skills, or any
	// combination in one call. No matching owner-scoped row returns no row (the handler
	// maps that to 404).
	UpdateSearchProfile(ctx context.Context, arg UpdateSearchProfileParams) (SearchProfile, error)
	// Single atomic write: upsert the company (only when the slug is non-empty,
	// via the WHERE on the SELECT) and the job together, keeping the "one write =
	// one job" property of the pipeline's write path.
	// The enrichment columns are deliberately NOT written here: ingest carries no
	// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
	// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
	// enrichment worker) is the sole writer of those columns.
	// countries/regions ARE written here: they are source facts parsed from the
	// location, not enrichment. COALESCE maps a nil arg to '{}', so a location that
	// yields no geography stores empty arrays (the columns are NOT NULL).
	// content_hash is the incremental-index change signal (internal/jobhash): the
	// `existing` CTE captures the row's pre-update hash (snapshot from before this
	// statement), so RETURNING can report whether the write inserted a new row
	// (`inserted`) or changed its searchable content (`changed`, true on insert and
	// for a legacy NULL hash). A re-ingest that only bumps last_seen_at reports both
	// false and needs no re-push to the search index.
	// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
	// at insert and is the row's stable public identity. Re-ingest of the same
	// (source, external_id) must not rewrite it, so external links stay valid even
	// if the slug builder changes later (that would be a deliberate migration).
	UpsertJob(ctx context.Context, arg UpsertJobParams) (UpsertJobRow, error)
	// Moderator-authored write: the hand-curated analogue of UpsertJob. source is the
	// posting's real origin (e.g. 'workatastartup'), supplied by the moderator and
	// defaulting to 'manual'; the dedup key is (source, external_id = url), so re-POSTing
	// the same URL updates the row idempotently instead of duplicating it. The manual
	// provenance is recorded by created_by (set here, NULL for every automated source) —
	// not by the source value. created_by is stamped once at insert; updated_by is
	// (re)written on the conflict update. Like UpsertJob, public_slug is minted once and
	// never rewritten, and the enrichment columns are left to SetJobEnrichment. The conflict
	// reopens a previously closed posting (closed_at = NULL) since the moderator is
	// re-asserting it.
	UpsertManualJob(ctx context.Context, arg UpsertManualJobParams) (Job, error)
	// Link (or relink) a user's Telegram chat, captured from the inbound /start. One
	// row per user; relinking from a different chat overwrites the chat_id.
	UpsertTelegramLink(ctx context.Context, arg UpsertTelegramLinkParams) error
}

var _ Querier = (*Queries)(nil)
