// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: screening_answers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScreeningAnswers = `-- name: GetScreeningAnswers :one
SELECT user_id, authorized_countries, visa_sponsorship_needed, desired_salary_amount, desired_salary_currency, desired_salary_period, notice_period_days, willing_to_relocate, age_18_or_older, updated_at FROM screening_answers
WHERE user_id = $1
`

// The caller's single screening-answers record, keyed by user_id. No matching row means
// the candidate has not stated any screening answer yet.
func (q *Queries) GetScreeningAnswers(ctx context.Context, userID int64) (ScreeningAnswer, error) {
	row := q.db.QueryRow(ctx, getScreeningAnswers, userID)
	var i ScreeningAnswer
	err := row.Scan(
		&i.UserID,
		&i.AuthorizedCountries,
		&i.VisaSponsorshipNeeded,
		&i.DesiredSalaryAmount,
		&i.DesiredSalaryCurrency,
		&i.DesiredSalaryPeriod,
		&i.NoticePeriodDays,
		&i.WillingToRelocate,
		&i.Age18OrOlder,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScreeningAnswers = `-- name: UpsertScreeningAnswers :one
INSERT INTO screening_answers (
    user_id, authorized_countries, visa_sponsorship_needed,
    desired_salary_amount, desired_salary_currency, desired_salary_period,
    notice_period_days, willing_to_relocate, age_18_or_older
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE
SET authorized_countries    = EXCLUDED.authorized_countries,
    visa_sponsorship_needed = EXCLUDED.visa_sponsorship_needed,
    desired_salary_amount   = EXCLUDED.desired_salary_amount,
    desired_salary_currency = EXCLUDED.desired_salary_currency,
    desired_salary_period   = EXCLUDED.desired_salary_period,
    notice_period_days      = EXCLUDED.notice_period_days,
    willing_to_relocate     = EXCLUDED.willing_to_relocate,
    age_18_or_older         = EXCLUDED.age_18_or_older,
    updated_at               = now()
RETURNING user_id, authorized_countries, visa_sponsorship_needed, desired_salary_amount, desired_salary_currency, desired_salary_period, notice_period_days, willing_to_relocate, age_18_or_older, updated_at
`

type UpsertScreeningAnswersParams struct {
	UserID                int64       `json:"user_id"`
	AuthorizedCountries   []string    `json:"authorized_countries"`
	VisaSponsorshipNeeded pgtype.Bool `json:"visa_sponsorship_needed"`
	DesiredSalaryAmount   pgtype.Int4 `json:"desired_salary_amount"`
	DesiredSalaryCurrency pgtype.Text `json:"desired_salary_currency"`
	DesiredSalaryPeriod   pgtype.Text `json:"desired_salary_period"`
	NoticePeriodDays      pgtype.Int4 `json:"notice_period_days"`
	WillingToRelocate     pgtype.Bool `json:"willing_to_relocate"`
	Age18OrOlder          pgtype.Bool `json:"age_18_or_older"`
}

// Create-or-replace the caller's one screening-answers record. Full-replace, mirroring
// UpsertUserProfile: the service reads the current row, merges caller-provided fields over
// it (omitted fields keep their stored value), and writes the merged result back whole —
// so the SQL layer stays a plain upsert and the partial-update semantics live in Go, where
// they are unit-testable without a database.
func (q *Queries) UpsertScreeningAnswers(ctx context.Context, arg UpsertScreeningAnswersParams) (ScreeningAnswer, error) {
	row := q.db.QueryRow(ctx, upsertScreeningAnswers,
		arg.UserID,
		arg.AuthorizedCountries,
		arg.VisaSponsorshipNeeded,
		arg.DesiredSalaryAmount,
		arg.DesiredSalaryCurrency,
		arg.DesiredSalaryPeriod,
		arg.NoticePeriodDays,
		arg.WillingToRelocate,
		arg.Age18OrOlder,
	)
	var i ScreeningAnswer
	err := row.Scan(
		&i.UserID,
		&i.AuthorizedCountries,
		&i.VisaSponsorshipNeeded,
		&i.DesiredSalaryAmount,
		&i.DesiredSalaryCurrency,
		&i.DesiredSalaryPeriod,
		&i.NoticePeriodDays,
		&i.WillingToRelocate,
		&i.Age18OrOlder,
		&i.UpdatedAt,
	)
	return i, err
}
