// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: semantic.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSemanticBatch = `-- name: ClaimSemanticBatch :many
WITH claimable AS (
    SELECT o.id, o.job_id
    FROM semantic_outbox o
    JOIN jobs j ON j.id = o.job_id
    WHERE o.failed_at IS NULL
      AND (o.claimed_at IS NULL
           OR o.claimed_at < now() - make_interval(secs => $1::int))
    ORDER BY COALESCE(j.posted_at, j.created_at) DESC, j.id DESC
    FOR UPDATE OF o SKIP LOCKED
    LIMIT $2
)
UPDATE semantic_outbox o
SET claimed_at = now()
FROM claimable c
JOIN jobs j ON j.id = c.job_id
WHERE o.id = c.id
RETURNING o.id, o.job_id, (j.closed_at IS NOT NULL OR j.duplicate_of IS NOT NULL)::boolean AS closed
`

type ClaimSemanticBatchParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimSemanticBatchRow struct {
	ID     int64 `json:"id"`
	JobID  int64 `json:"job_id"`
	Closed bool  `json:"closed"`
}

// Claim a batch of live, unleased entries, freshest job first, by stamping claimed_at.
// Unlike ClaimEnrichmentBatch this does NOT filter unindexable jobs out: a closed OR
// non-canonical (duplicate_of) entry is the removal signal, so the worker must receive
// it and branch on `closed` (true = remove the document). The jobs join supplies both
// the freshness order and that flag. Freshness is
// COALESCE(posted_at, created_at): jobs without a source post date fall back to ingest
// time so they rank by recency instead of starving under NULLS LAST. FOR UPDATE OF o
// locks only outbox rows (a bare FOR UPDATE would also lock jobs, making concurrent
// claim waves contend); SKIP LOCKED lets concurrent workers take disjoint rows; the
// lease predicate reclaims entries whose worker died (stale claimed_at), so no separate
// reaper process is needed.
// Join jobs off the claimable CTE (not the UPDATE target o, which Postgres forbids in
// FROM) so the removal branch gets the job's closed flag without a second query.
func (q *Queries) ClaimSemanticBatch(ctx context.Context, arg ClaimSemanticBatchParams) ([]ClaimSemanticBatchRow, error) {
	rows, err := q.db.Query(ctx, claimSemanticBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimSemanticBatchRow{}
	for rows.Next() {
		var i ClaimSemanticBatchRow
		if err := rows.Scan(&i.ID, &i.JobID, &i.Closed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearSemanticEmbeddedBatch = `-- name: ClearSemanticEmbeddedBatch :exec
UPDATE jobs
SET semantic_embedded_model = NULL,
    semantic_embedded_hash  = NULL,
    semantic_embedding      = NULL
WHERE id = ANY($1::bigint[])
`

// Clear a batch of jobs' embed provenance AND their durable vector after their documents
// are removed from jobs_semantic (closed-job path). Run in the same transaction as
// DeleteSemanticEntriesBatch. Dropping semantic_embedding keeps Postgres consistent with
// the index: a closed job has no vector in either place.
func (q *Queries) ClearSemanticEmbeddedBatch(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, clearSemanticEmbeddedBatch, ids)
	return err
}

const deleteSemanticEntriesBatch = `-- name: DeleteSemanticEntriesBatch :exec
DELETE FROM semantic_outbox
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteSemanticEntriesBatch(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, deleteSemanticEntriesBatch, ids)
	return err
}

const enqueuePendingSemanticJobs = `-- name: EnqueuePendingSemanticJobs :execrows
INSERT INTO semantic_outbox (job_id, target_model)
SELECT id, $1::text
FROM jobs
WHERE (
        closed_at IS NULL AND duplicate_of IS NULL
        AND (semantic_embedded_model IS DISTINCT FROM $1::text
             OR semantic_embedded_hash IS DISTINCT FROM content_hash)
        AND category <> ALL(COALESCE($2::text[], '{}'))
      )
   OR ((closed_at IS NOT NULL OR duplicate_of IS NOT NULL) AND semantic_embedded_model IS NOT NULL)
ON CONFLICT (job_id, target_model) DO NOTHING
`

type EnqueuePendingSemanticJobsParams struct {
	TargetModel       string   `json:"target_model"`
	ExcludeCategories []string `json:"exclude_categories"`
}

// Idempotent backfill for the incremental semantic-embedding queue. Enqueues two
// kinds of outstanding work at the target embedder model:
//  1. OPEN jobs whose stored vector is missing, content-stale, or model-stale —
//     i.e. semantic_embedded_model differs from the target OR semantic_embedded_hash
//     differs from the job's current content_hash. Jobs whose derived category is in
//     exclude_categories (enrich.NonTechCategories) are skipped so embed budget stays
//     on technical roles; category is NOT NULL DEFAULT ”, so an empty/unrecognized
//     category is never excluded (empty string <> ALL keeps the row).
//  2. UNINDEXABLE jobs that still carry an embed stamp (were embedded while open and
//     canonical) — a job now closed OR a non-canonical repost (duplicate_of set) — so
//     the worker removes their document from jobs_semantic and clears the stamp. This
//     mirrors the facet index: the full reindex --semantic also drops reposts (shared
//     splitJobs), so the incremental path must not re-add them.
//
// ON CONFLICT keeps exactly one entry per (job_id, target_model), so running this every
// command invocation never duplicates work.
func (q *Queries) EnqueuePendingSemanticJobs(ctx context.Context, arg EnqueuePendingSemanticJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueuePendingSemanticJobs, arg.TargetModel, arg.ExcludeCategories)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobsByIDs = `-- name: GetJobsByIDs :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at, countries, regions, work_mode, liveness_strikes, skills, seniority, category, created_by, updated_by, posting_language, employment_type, education_level, experience_years_min, collections, content_hash, english_level, cities, view_count, applied_count, role_fingerprint, semantic_embedded_model, semantic_embedded_hash, duplicate_of, is_tech, semantic_embedding
FROM jobs
WHERE id = ANY($1::bigint[])
`

// Batch-load the persisted rows the embed worker builds documents from. A corrupted
// row (SQLSTATE XX001) aborts the whole scan; the worker then retries the batch one id
// at a time to isolate and dead-letter the bad row.
func (q *Queries) GetJobsByIDs(ctx context.Context, ids []int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
			&i.Countries,
			&i.Regions,
			&i.WorkMode,
			&i.LivenessStrikes,
			&i.Skills,
			&i.Seniority,
			&i.Category,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.PostingLanguage,
			&i.EmploymentType,
			&i.EducationLevel,
			&i.ExperienceYearsMin,
			&i.Collections,
			&i.ContentHash,
			&i.EnglishLevel,
			&i.Cities,
			&i.ViewCount,
			&i.AppliedCount,
			&i.RoleFingerprint,
			&i.SemanticEmbeddedModel,
			&i.SemanticEmbeddedHash,
			&i.DuplicateOf,
			&i.IsTech,
			&i.SemanticEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSemanticFailure = `-- name: RecordSemanticFailure :one
UPDATE semantic_outbox
SET attempts   = attempts + 1,
    last_error = $1,
    failed_at  = CASE
                     WHEN attempts + 1 >= $2::int THEN now()
                     ELSE NULL
                 END
WHERE id = $3
RETURNING attempts, failed_at
`

type RecordSemanticFailureParams struct {
	LastError   string `json:"last_error"`
	MaxAttempts int32  `json:"max_attempts"`
	ID          int64  `json:"id"`
}

type RecordSemanticFailureRow struct {
	Attempts int32              `json:"attempts"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

// Count a failed attempt: bump attempts, record the error, and dead-letter (set
// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally left
// in place — its expiry gates the retry to a later run and doubles as the crash reaper,
// so a failed entry is never reprocessed within the same run. Mirrors
// RecordEnrichmentFailure.
func (q *Queries) RecordSemanticFailure(ctx context.Context, arg RecordSemanticFailureParams) (RecordSemanticFailureRow, error) {
	row := q.db.QueryRow(ctx, recordSemanticFailure, arg.LastError, arg.MaxAttempts, arg.ID)
	var i RecordSemanticFailureRow
	err := row.Scan(&i.Attempts, &i.FailedAt)
	return i, err
}

const setSemanticEmbedding = `-- name: SetSemanticEmbedding :exec
UPDATE jobs
SET semantic_embedding = $1::real[]
WHERE id = $2
`

type SetSemanticEmbeddingParams struct {
	Embedding []float32 `json:"embedding"`
	ID        int64     `json:"id"`
}

// Persist one job's semantic vector — the durable copy of what was just upserted into
// the jobs_semantic index. Called once per embedded job inside the SAME transaction as
// StampSemanticEmbeddedBatch on the open-job success path, so the stamp and the vector
// commit together (a job is never marked embedded without its vector reaching Postgres).
// Postgres thus becomes the source of truth for the vector: the nightly pg_dump backs it
// up and reindex can rehydrate Meili from it without re-embedding. Idempotent by primary key.
func (q *Queries) SetSemanticEmbedding(ctx context.Context, arg SetSemanticEmbeddingParams) error {
	_, err := q.db.Exec(ctx, setSemanticEmbedding, arg.Embedding, arg.ID)
	return err
}

const stampSemanticEmbeddedBatch = `-- name: StampSemanticEmbeddedBatch :exec
UPDATE jobs
SET semantic_embedded_model = $1::text,
    semantic_embedded_hash  = content_hash
WHERE id = ANY($2::bigint[])
`

type StampSemanticEmbeddedBatchParams struct {
	Model string  `json:"model"`
	Ids   []int64 `json:"ids"`
}

// Record that a batch of jobs' content is embedded under the given model. Run in the
// same transaction as DeleteSemanticEntriesBatch on the success path, so a crash between
// the index write and this stamp is safely retried (idempotent re-embed). The stamp
// copies each job's CURRENT content_hash (nullable-safe: a NULL content_hash stamps NULL
// so NULL IS DISTINCT FROM NULL stays false and the job is not re-enqueued forever).
// Caveat: if an ingest commits a new content_hash in the tiny window between the embed
// (which read the old content) and this stamp, the stamp records the NEW hash while the
// vector reflects the old one — so the enqueue predicate sees a match and does NOT
// re-enqueue it next run; that job carries a one-revision-stale vector until its content
// changes AGAIN (which re-enqueues it). The window is one embed-duration and the drift
// self-corrects on the next real change, so this is accepted over threading the exact
// embedded hash through a nullable text[] per batch.
func (q *Queries) StampSemanticEmbeddedBatch(ctx context.Context, arg StampSemanticEmbeddedBatchParams) error {
	_, err := q.db.Exec(ctx, stampSemanticEmbeddedBatch, arg.Model, arg.Ids)
	return err
}
